Stitch/Home/View/ProjectItem/ProjectsListItemView.swift
If preview window does not take up whole space for project's icon, use preview window color + 20% black on the remaining space.
=> Use 20% darker background for project thumbnails

Stitch/Graph/Node/Port/Model/Field/FocusedUserEditField.swift, Stitch/Graph/Node/Title/Util/NodeTitleActions.swift, Stitch/Graph/Node/Title/View/CanvasItemTitleView.swift, Stitch/Graph/Node/Title/View/NodeTitleTextField.swift, Stitch/Graph/Node/View/LayerRowOnGraphView.swift, Stitch/Graph/Node/View/NodeView.swift
https://github.com/StitchDesign/Stitch/assets/18562836/82af75ea-1e58-4e80-95b9-a33960973932
=> Fix canvas-editing of a node's title

Stitch/Graph/LayerInspector/LayerInspectorActions.swift, Stitch/Graph/LayerInspector/LayerInspectorPortView.swift, Stitch/Graph/LayerInspector/LayerInspectorState.swift
Also removes duplicate display of Text input.
=> Only select one property at a time; better property hit area

Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingView.swift, Stitch/Graph/Node/Port/View/PortView.swift, Stitch/Graph/Node/Title/View/CanvasItemTitleView.swift, Stitch/Graph/Node/View/CanvasItemSelectedViewModifier.swift, Stitch/Graph/Node/View/LayerRowOnGraphView.swift, Stitch/Graph/Node/View/NodeView.swift
=> Node UI refresh: left title alignment, body spacing, input background color

Stitch/Graph/Node/Port/Model/PortValue/Type/Shapes/ShapeUtils.swift
Fixes small regression from #37
=> Only apply stroke to shape layer when stroke position is specified

Stitch/Graph/LayerInspector/LayerInspectorActions.swift, Stitch/Graph/Node/Util/NodeCreatedAction.swift, Stitch/Graph/PrototypePreview/Frame/View/FloatingWindowView.swift, Stitch/Graph/Sidebar/View/SidebarListView.swift
https://github.com/StitchDesign/Stitch/assets/18562836/e197f072-2f1e-4372-9f8f-7e6a404eb2bd
=> Adjust 'graph center' by width of LayerInspector view, when adding layer property to graph

Stitch/Graph/LLMRecording/LLMActions/LLMActionParsing.swift
This json of LLM Actions are now parsed appropriately:
```json
[{"node":"Drag Interaction (00524B)","action":"Add Node"},{"node":"Drag Interaction (00524B)","translation":{"y":-228,"x":-450},"port":"","action":"Move Node"},{"action":"Add Node","node":"Rectangle (FBA115)"},{"action":"Set Input","nodeType":"Anchor","value":"0.5, 0.5","field":{"port":"Anchoring","node":"Rectangle (FBA115)"}},{"node":"Rectangle (FBA115)","port":"Position","action":"Add Layer Input"},{"node":"Rectangle (FBA115)","port":"Position","action":"Move Node","translation":{"x":538,"y":-137}},{"action":"Add Edge","from":{"port":"Position","node":"Drag Interaction (00524B)"},"to":{"node":"Rectangle (FBA115)","port":"Position"}}]
=> Use patch vs layer and input vs output context for smarter parsing of labeled outputs on a patch node

Stitch/Graph/LLMRecording/LLMActions/LLMActionParsing.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/JSON/JSONUtils.swift
https://github.com/StitchDesign/Stitch/assets/18562836/68c704da-2856-4b33-ba8b-4e1913e1d35a
=> Smarter handling of layer ids in LLMSetInput

Stitch/Graph/Node/Layer/Type/GroupLayerNode.swift, Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift, Stitch/Graph/PrototypePreview/Layer/View/GeneratePreview.swift, Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift
=> Use StitchSpacing with LayerGroup

Stitch/Graph/Node/Port/Util/PortValue/Coercers.swift
=> Smarter duck-typing of a string to a layer-size

Stitch/Graph/Node/Layer/Type/SFSymbolLayerNode.swift, Stitch/Graph/Node/Layer/Type/TextFieldLayerNode.swift, Stitch/Graph/Node/Layer/Type/TextLayerNode.swift, Stitch/Graph/Node/Model/RowData/LayerInputType.swift
=> Adding default SF Symbol

Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/Node/Port/Util/InputEdit/InputCommittedActions.swift, Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift, Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift, Stitch/Graph/View/Gesture/GraphGestureView.swift, Stitch/Graph/View/GraphBaseView.swift
https://github.com/user-attachments/assets/2e28e77c-3b5c-458e-b506-54d5c810f22f
=> Hide and show inputs specific to a LayerGroup's orientation

Stitch/Graph/Node/Model/Definition/StitchNodeNames.swift
=> updating node color descriptions

Stitch.xcodeproj/project.pbxproj
To be `app.stitchdesign.stitchTests`
=> Update test target bundle ID

Stitch/Graph/Node/Patch/Type/Loop/LoopBuilder.swift
=> change loop builder type to number

Stitch.xcodeproj/project.pbxproj, Stitch/App/Serialization/DocumentLoading/DirectoryObserver.swift, Stitch/App/ViewModel/StitchEnvironment.swift, stitch.xcworkspace/xcshareddata/swiftpm/Package.resolved
Replaces in-house logic with a better 3P library.
=> Fixed first-run crash caused by directory observer

Stitch/Graph/LayerInspector/PaddingFlyoutView.swift, Stitch/Graph/Node/Model/RowData/LayerInputType.swift, Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
=> Fix input view UI label

Stitch.xcodeproj/project.pbxproj, Stitch/Graph/Node/Port/Model/Field/FieldGroupType.swift, Stitch/Graph/Node/Port/Model/Field/FieldValue.swift, Stitch/Graph/Node/Port/Model/Field/NodeRowType.swift, Stitch/Graph/Node/Port/Model/Field/SingleDropdownKind.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Layer/LayerDimensionUtils.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Layer/StitchSpacingUtils.swift, Stitch/Graph/Node/Port/Util/Field/FieldValueUtils.swift, Stitch/Graph/Node/Port/Util/Field/FieldViewModelTypeUtils.swift, Stitch/Graph/Node/Port/Util/PortValue/Parsers.swift, Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift, Stitch/Graph/Node/Port/View/Field/OutputValueView.swift, Stitch/Graph/Node/Port/ViewModel/FieldGroupTypeViewModel.swift, Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift
Note the bug where we always seem to open the project with spacing = 0 ?
https://github.com/user-attachments/assets/c44f4da9-71ba-4de3-9810-f4975e4af053
=> Property sidebar: StitchSpacing now uses Textfield + Dropdown view

Stitch/Graph/Node/Patch/ViewModel/PatchNodeViewModel.swift
=> sort node types by alphabetical order

Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonSizeModifier.swift, Stitch/Graph/ViewModel/GraphUI.swift
=> Use .frame(width:height:alignment) when LayerInspector disabled

Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift, Stitch/Graph/View/ContentView.swift, Stitch/Graph/ViewModel/GraphDelegate.swift, Stitch/Graph/ViewModel/GraphState.swift
Issues:
* Port view models were incorrectly updating in full screen mode
* Incorrect logic for determining if nodes were visible
=> Improved perf by fixing row view model visibility status

Stitch/App/Serialization/DocumentLoading/DocumentLoader.swift, Stitch/App/View/StitchNavStack.swift, Stitch/Graph/PrototypePreview/Frame/View/FloatingWindowView.swift, Stitch/Graph/PrototypePreview/Frame/View/FullScreenPreviewViewWrapper.swift, Stitch/Graph/PrototypePreview/Frame/View/PreviewContent.swift, Stitch/Graph/PrototypePreview/Frame/ViewModel/PreviewWindowSizing.swift, Stitch/Graph/Util/GraphActions.swift, Stitch/Graph/Util/ProjectThumbnailActions.swift, Stitch/Graph/View/ContentView.swift, Stitch/Graph/View/ProjectNavigationView.swift, Stitch/Graph/View/StitchProjectView.swift, Stitch/Graph/ViewModel/GraphState.swift
The result of various attempts to fix image imports in image layers, albeit unsuccessfully.
=> Thumbnail creation cleanup

Stitch/Graph/Edge/Util/PortActions.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowViewModel.swift, Stitch/Graph/Node/ViewModel/NodeViewModel.swift, Stitch/Graph/PrototypePreview/Layer/Util/LayerHoveredActions.swift, Stitch/Graph/ViewModel/GraphState.swift, Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
Main issue here was removing old logic that relied on sorted layer input rows, which are no longer a factor with the layer inspector.
Also some other changes here to fix edge highlight colors.
=> Fixed layer UI connections

Stitch/Graph/Node/Port/Util/PortValue/Coercers.swift
=> Duck-type non-empty strings to number 1

Stitch/Graph/LayerInspector/LayerInspectorActions.swift, Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/Node/Layer/Model/LayerNodeData.swift, Stitch/Graph/Node/Layer/Util/LayerUtils.swift, Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift, Stitch/Graph/Node/Model/Definition/NodeDefinition.swift, Stitch/Graph/Node/Model/SchemaNodesUtil.swift, Stitch/Graph/Node/Patch/Util/PatchDefaultNodeExtensions.swift, Stitch/Graph/Node/Patch/ViewModel/PatchNodeViewModel.swift, Stitch/Graph/Node/Port/View/PortValuesPreviewView.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverSchemaObserverIdentifiable.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowViewModel.swift, Stitch/Graph/Node/Title/View/MathExpressionSubmenuButtonView.swift, Stitch/Graph/Node/Util/NodeViewModelUtils.swift, Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift, Stitch/Graph/Node/ViewModel/NodeViewModel.swift, Stitch/Graph/Node/ViewModel/NodeViewModelType.swift, Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift
Caused by a race condition where multiple fake reference objects would be created for some view models.
=> Fixed issue where inspector fields may not initialize properly

Stitch.xcodeproj/project.pbxproj, Stitch/Graph/LayerInspector/FlyoutUtils.swift, Stitch/Graph/LayerInspector/LayerInspectorState.swift, Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/Node/Patch/Type/Interaction/Keyboard/KeyPressActions.swift, Stitch/Graph/Node/Port/Util/Field/OldTabKeyPressActions.swift, Stitch/Graph/Node/Port/Util/Field/TabKeyPressActions.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowViewModel.swift, Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift
https://github.com/user-attachments/assets/10f5b563-7221-4cd8-9d0b-573bc5f98d6a
=> Property sidebar: ignore collapsed sections and blocked out fields when tabbing

Stitch/Graph/Node/Layer/Model/LayerNodeData.swift, Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift, Stitch/Graph/Node/Port/Util/Field/TabKeyPressActions.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowViewModel.swift, Stitch/Graph/Node/ViewModel/NodeViewModel.swift
Allows us to add layer node outputs to graph and see them live update in layer inspector again. 
https://github.com/user-attachments/assets/dade4d68-6af5-4d73-a034-c97187812409
=> Property sidebar: support layer node outputs

Stitch/App/FeatureFlags.swift, Stitch/Graph/Edge/Model/PortEdgeData.swift, Stitch/Graph/Node/Layer/Model/LayerNodeData.swift, Stitch/Graph/Node/Layer/Type/ShapeLayerNode.swift, Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowViewModel.swift, Stitch/Graph/Node/Util/NodeViewModelUtils.swift, Stitch/Graph/Node/ViewModel/NodeViewModel.swift, Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonSizeModifier.swift, Stitch/Graph/Sidebar/View/SidebarItem/SidebarListItemView.swift, Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift, Stitch/Graph/Toolbar/View/TopBarButtonView.swift, Stitch/Graph/View/GraphBaseView.swift
Accidentally reverted from recent merges.
=> Removed inspector feature flag

Stitch/Graph/Node/Layer/Type/3DModelLayerNode/PreviewModel3DLayer.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/AR/StitchEntity.swift, TestFlight/WhatToTest.en-US.txt
=> Fixed 3d model layer mutations (#153)

Stitch/Graph/Node/Model/GraphCopyable.swift, Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarSelectedItemsDuplicated.swift, Stitch/Graph/Util/NodeSelection/CopyAndPasteNodesActions.swift, Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift, Stitch/Graph/ViewModel/GraphUI.swift, stitch.xcworkspace/xcshareddata/swiftpm/Package.resolved
https://github.com/user-attachments/assets/cf925261-a8c2-4375-852b-635e9a67a6c9
https://github.com/user-attachments/assets/f544a5c1-99e7-4b84-878f-f0fb07a9a805
https://github.com/user-attachments/assets/e58ca2bb-0c6b-4a31-953d-c0ed5b689197
=> Property sidebar: duplicate layers and layer groups via sidebar, patch nodes and group nodes via

Stitch/Graph/Node/Model/GraphCopyable.swift, Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarSelectedItemsDuplicated.swift, Stitch/Graph/Util/NodeSelection/CopyAndPasteNodesActions.swift, Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift, Stitch/Graph/ViewModel/GraphUI.swift, stitch.xcworkspace/xcshareddata/swiftpm/Package.resolved
Was supposed to be for feature branch.
=> Revert property sidebar fix for layer inspector

Stitch/Graph/LayerInspector/LayerInspectorState.swift, Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/Node/Port/Util/Field/TabKeyPressActions.swift, Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
https://github.com/user-attachments/assets/4643b8ba-aa41-4e42-8ebf-8f5875d00187
=> Property sidebar: list shadow flyout in layer effects section rather than as separate header

Stitch/Graph/LayerInspector/LayerInspectorPortView.swift, Stitch/Graph/Node/Util/NodeDeletedAction.swift, stitch.xcworkspace/xcshareddata/swiftpm/Package.resolved
https://github.com/user-attachments/assets/021e5d25-eeab-4cc6-ac70-602947533d2a
=> Remove 'already on canvas' row icon when row's canvas item is deleted

Stitch/Graph/LayerInspector/LayerInspectorPortView.swift, Stitch/Graph/LayerInspector/LayerInspectorState.swift, Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
=> Layer inspector V1: more Figma spec work: better section padding, alignment and handling of safe areas

Stitch/Graph/LayerInspector/LayerInspectorState.swift, Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/LayerInspector/PaddingFlyoutView.swift, Stitch/Graph/View/ContentView.swift
=> Property sidebar: Flyout now respects safe area

Stitch/Graph/LayerInspector/LayerInspectorState.swift, Stitch/Graph/LayerInspector/LayerInspectorView.swift
=> Move Unknown section inputs to Common

Stitch.xcodeproj/project.pbxproj, Stitch/Graph/LayerInspector/LayerInspectorState.swift, Stitch/Graph/LayerInspector/OpenFlyoutView.swift, Stitch/Graph/LayerInspector/PaddingFlyoutView.swift, Stitch/Graph/View/ContentView.swift
We respect keyboard safe area near the bottom; but don't move up if we don't need to. 
https://github.com/user-attachments/assets/94537486-c179-4d33-a197-d3d58a9c14e6
=> Property sidebar: flyout respects keyboard safe area if near bottom

Stitch/Graph/Node/Patch/Type/Media/Model3DImportNode.swift, Stitch/Graph/Node/Patch/Type/Pack/MatrixPackNode.swift, Stitch/Graph/Node/Patch/Type/Pack/PackNode.swift, Stitch/Graph/Node/Patch/Type/Unpack/UnpackNode.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/AR/ARUtils.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/AR/SIMDExtensions.swift, Stitch/Graph/Node/Port/Util/PortValue/PortValueDefaults.swift, Stitch/Graph/Node/View/Util/NodeConstants.swift
* Misc cleanup 
* Contains work for 3D matrix extensions/conversions
=> Matrix Updates

Stitch/Graph/Node/Port/View/Field/InputView/LayerNamesDropDownChoiceView.swift
=> Exclude A from B's pinTo choices if A already pinned to B

Stitch/Graph/Node/Port/View/Field/InputView/LayerNamesDropDownChoiceView.swift, Stitch/Graph/Node/Port/View/Field/Media/VideoDisplayView.swift, Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommon.swift, Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonSizeModifier.swift, Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewWindowCoordinateSpaceReader.swift, Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift, Stitch/Graph/PrototypePreview/Layer/ViewModel/LayerViewModel.swift
[A pinned to B, B pinned to C.stitch.zip](https://github.com/user-attachments/files/16640360/A.pinned.to.B.B.pinned.to.C.stitch.zip)
=> Pinning: position of A when A is pinned to B and B is pinned to C

Stitch/Graph/Node/Port/Util/InputEdit/InputCommittedActions.swift
A silly misplaced bracket on my part.
=> Allow user to select an interaction id when on non-layer dropdown

Stitch.xcodeproj/project.pbxproj, Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Stitch/Graph/Node/Eval/OperationEvaluationHelpers.swift, Stitch/Graph/Node/Eval/PatchEvaluateExtensions.swift, Stitch/Graph/Node/Eval/PatchNodeType.swift, Stitch/Graph/Node/Model/Definition/PatchNodeDefinitionKinds.swift, Stitch/Graph/Node/Model/Definition/StitchNodeNames.swift, Stitch/Graph/Node/Patch/Type/ARRaycastingNode.swift, Stitch/Graph/Node/Patch/Type/Media/ARAnchorNode.swift, Stitch/Graph/Node/Patch/Type/Media/Model3DImportNode.swift, Stitch/Graph/Node/Patch/Type/Pack/MatrixPackNode.swift, Stitch/Graph/Node/Patch/Type/Pack/PackNode.swift, Stitch/Graph/Node/Patch/Type/Pack/TransformPackNode.swift, Stitch/Graph/Node/Patch/Type/Unpack/MatrixUnpackNode.swift, Stitch/Graph/Node/Patch/Type/Unpack/UnpackNode.swift, Stitch/Graph/Node/Patch/Util/PatchDescription.swift, Stitch/Graph/Node/Patch/Util/PatchUtils.swift, Stitch/Graph/Node/Port/Util/Field/FieldViewModelTypeUtils.swift, Stitch/Graph/Node/Port/Util/Field/PortValueEdit.swift, Stitch/Graph/Node/Port/Util/PortValue/CoercerUtils.swift, Stitch/Graph/Node/Port/Util/PortValue/Coercers.swift, Stitch/Graph/Node/Port/Util/PortValue/PortValueDefaults.swift, Stitch/Graph/Node/Port/Util/PortValue/PortValueDisplay.swift, Stitch/Graph/Node/Port/Util/PortValue/PortValueUtils.swift, Stitch/Graph/Node/Util/NodeTypeUtils.swift, Stitch/Graph/Node/View/Util/NodeConstants.swift
Work to make StitchMatrix internal only + refactor the Pack + Unpack nodes only use the new StitchTransform. 
Tested with HomePod demo 
https://github.com/user-attachments/assets/16d2bcef-c7f4-47e4-a30b-0d2efc0c91ad
=> Transform Work

Stitch/Graph/Node/Model/Definition/StitchNodeNames.swift
=> Update transform node descriptions

Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingView.swift
https://github.com/user-attachments/assets/6a211d01-7fd8-4024-97c9-e6258f7a9b5c
=> Accept e.g. FILL or Fill for the 'fill' dropdown option

Stitch.xcodeproj/project.pbxproj, Stitch/App/Serialization/Util/File/StitchDocumentUtil.swift, Stitch/Graph/Model/SchemaVersions.swift, Stitch/Graph/Node/Patch/Type/ARRaycastingNode.swift, Stitch/Graph/Node/Patch/Type/Animation/BouncyConverterNode.swift, Stitch/Graph/Node/Patch/Type/Data/ArrayAppendNode.swift, Stitch/Graph/Node/Patch/Type/Data/JSONArrayNode.swift, Stitch/Graph/Node/Patch/Type/Data/JSONObjectNode.swift, Stitch/Graph/Node/Patch/Type/Interaction/Keyboard/KeyboardNode.swift, Stitch/Graph/Node/Patch/Type/Loop/LoopBuilder.swift, Stitch/Graph/Node/Patch/Type/Math/ModNode.swift, Stitch/Graph/Node/Patch/Type/Pulse/WhenPrototypeStartsNode.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Shapes/CustomShape.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Shapes/HoleShapeMaskView.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Shapes/JSON/JSONShapeCommand.swift, Stitch/Graph/Node/Port/Util/PortValue/PortValuesUtils.swift, Stitch/Graph/PrototypePreview/Frame/Util/PreviewWindowDeviceUtils.swift, stitch.xcworkspace/xcshareddata/swiftpm/Package.resolved
Fixes issue where we would miss version enforcement in SSK.
=> Moved schema typealiases to Stitch repo

Stitch/Graph/LayerInspector/LayerInspectorPortView.swift, Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
https://github.com/user-attachments/assets/5bb3f008-b443-4707-a564-3448e1d1a46e
=> Property sidebar: show add to canvas button on hover

Stitch.xcodeproj/project.pbxproj, Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift, Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/LayerPaddingModifier.swift, Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonModifierWithoutFrame.swift, Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonSizeModifier.swift, Stitch/Graph/PrototypePreview/Layer/ViewModel/LayerViewModel.swift
=> Introduce padding vs margin preview modifiers for individual layers

Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/AR/SIMDExtensions.swift
https://github.com/user-attachments/assets/4d9141d6-39cc-4494-8dc2-19c0a901895b
=> Change matrix init function to use degrees, not radians

Stitch/Graph/Util/GraphUIActions.swift
=> updated node search logic

Stitch/Graph/Node/Patch/Type/Media/SoundImportNode.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Sound/StitchSoundFile.swift
https://github.com/user-attachments/assets/11fe3f18-896f-4aee-b0d4-51bb8053e088
=> Fft metering for sound file player

Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Sound/StitchSoundFile.swift
https://github.com/user-attachments/assets/29e9e17e-670b-45e8-9e37-173fbb9ee4b4
=> improved fft scaling

Stitch/App/Shortcut/ProjectsHomeCommands.swift, Stitch/App/View/StitchRootView.swift, Stitch/Graph/LayerInspector/FlyoutUtils.swift, Stitch/Graph/Util/GraphUIActions.swift, Stitch/Graph/ViewModel/GraphUI.swift
https://github.com/user-attachments/assets/090107a4-2f5c-417c-ab9f-97736bb5b7be
https://github.com/user-attachments/assets/fc2f026e-699c-4620-9a55-ef182ff58a6f
=> `Cmd + / ` to toggle preview window, `Cmd + .` to toggle sidebars

Stitch/Graph/Node/Eval/MediaEvalOpObservable.swift, Stitch/Graph/Node/Patch/Type/CoreMLClassifyNode.swift, Stitch/Graph/Node/Patch/Type/CoreMLDetectionNode.swift, Stitch/Graph/Node/Patch/Type/Media/ARAnchorNode.swift, Stitch/Graph/Node/Patch/Type/Media/GrayscaleNode.swift, Stitch/Graph/Node/Patch/Type/Media/ImageNode.swift, Stitch/Graph/Node/Patch/Type/Media/ImageToBase64StringNode.swift, Stitch/Graph/Node/Patch/Type/Media/Model3DImportNode.swift, Stitch/Graph/Node/Patch/Type/Media/SoundImportNode.swift, Stitch/Graph/Node/Patch/Type/Media/VideoImportNode.swift, Stitch/Graph/Node/Patch/Type/QRCodeDetection.swift
Main issue here was attributed to not updating row values with the updated port value struct containing the media object.
=> Fixed issue where media would display as "none"

Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Sound/StitchSoundFile.swift
https://github.com/user-attachments/assets/3181ef0f-03fc-4e25-a96b-1d0b9ccfc343
=> Updating audio jump logic

Stitch/App/Serialization/Util/File/StitchDocumentUtil.swift
Resolves https://github.com/StitchDesign/Stitch/issues/244
https://github.com/user-attachments/assets/8650a9d7-3573-4990-9d8c-10eafd877d90
=> Allow for / to be used in project sharing

Stitch/Graph/LayerInspector/LayerInspectorView.swift
Fixes an issue where the scroll bar was too close to the edge of the window.
=> Fixed scrollview padding around layer inspector

Stitch/Graph/Node/Patch/Type/Math/LengthNode.swift
https://github.com/user-attachments/assets/8ae80153-9f31-474a-aa9d-d4348c773b84
=> adding correct logic for calculating length of numbers and strings

Stitch/Graph/Node/Patch/Type/Math/SoulverNode.swift, Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift, Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingView.swift, Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingViewWrapper.swift, Stitch/Graph/Node/Port/View/Field/InputView/FieldValueNumberView.swift
Adds some default text to show what soulver can do on node creation
=> Soulver default text

Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
The issue was caused by updating logic on schema changes, specifically when a layer port was in unpacked mode. We would update values for both packed and unpacked observers even with upstream connections.
The fix was introducing logic to only update port values for the specific mode's observers, rather than always update everything.
=> Fixed issue where fields changed on unpacked layer ports

Stitch/Graph/Node/Patch/Type/Math/LengthNode.swift
=> Add string op logic for length node

Stitch/Graph/LayerInspector/GenericFlyoutView.swift, Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
Issue caused by not setting node delegate.
=> Fixed undo unpacked layer node deletion

Stitch/Graph/Node/Patch/Type/Media/SoundImportNode.swift
Fulfills requirements 2 and 3 of: https://github.com/StitchDesign/Stitch/issues/294
=> Update Sound Output Label Text

Stitch/Graph/Node/Port/Model/Field/FieldValue.swift
https://github.com/user-attachments/assets/1b5045f1-b815-4872-a34f-a991853b271b
=> Fix layer dimension field use with adjustment bar

Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerView.swift
=> Placeholder image when no image present

Stitch/Graph/Node/Patch/Type/Interaction/DragInteractionPatchNode.swift
https://github.com/user-attachments/assets/1722b242-62c7-4f61-b342-5d06d3b73133
=> Drag: reset position output to zero prototype restarts

Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift, Stitch/Graph/ViewModel/GraphUI.swift
https://github.com/user-attachments/assets/2db3fdba-c349-48c1-801d-2c31cff8530a
=> Select option-dragged node when drag starts

Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
https://github.com/user-attachments/assets/c2697d07-988b-4ced-a1c2-6d5d78ddf1f2
=> 0.1 second duration of linear animation for inspector row button

Stitch/App/Util/ProjectAlertActions.swift, Stitch/Home/View/ProjectsHomeView.swift
Resolves https://github.com/StitchDesign/Stitch/issues/310
https://github.com/user-attachments/assets/ac65db16-1a4b-4618-9121-1ee597a47116
=> Fix App Settings Done Button

Stitch/Graph/Node/Layer/Type/VideoLayerNode.swift, Stitch/Graph/Node/Layer/Type/VisualMediaLayerNode.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Import/MediaImportUtils.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Models/StitchMediaObject.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Video/StitchVideoDelegate.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Video/StitchVideoPlayer.swift, Stitch/Graph/Node/Port/View/Field/InputView/ScrubbedVideoView.swift, Stitch/Graph/Node/Port/View/Field/Media/VideoDisplayView.swift, Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewVideo.swift
https://github.com/user-attachments/assets/53b99641-9c32-4f8f-9878-1983cd06d658
=> Add Volume Output to Video Layer Node

Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/CameraFeed/Reference/StitchAVCaptureSession.swift
https://github.com/user-attachments/assets/7f82dd37-972c-48a6-8d1a-7ff7ee6712a7
=> Camera orientation iphone fix

Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupCreated.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarListItemSelectionHelpers.swift, Stitch/Graph/Sidebar/View/SidebarItem/SidebarListItemView.swift, Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemGestureRecognizerView.swift
Appears to resolve intermittent issue where sidebar layers could become unresponsive to clicks.
=> Prefer SwiftUI Tap Gesture for sidebar layer

Stitch/Graph/Sidebar/Util/Gesture/LegacySidebarActions.swift, Stitch/Graph/Sidebar/View/SidebarItem/SidebarListItemView.swift
https://github.com/user-attachments/assets/f0ce3643-67e9-4730-8481-758525cb0eee
=> Focus the dragged layer

Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift
https://github.com/user-attachments/assets/aa589584-d6d5-4b7b-81fa-692e17f79e77
=> Select from top to clicked item if shift-click done while no other layers selected

Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift
https://github.com/user-attachments/assets/2a3b38bf-747f-4a96-8606-669e0547360c
=> Close Flyout when we focused layers change

Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemSwipeInnerView.swift
https://github.com/user-attachments/assets/5b848eda-4ab8-454f-9c50-4c2fc76f96ac
=> Do not fade swipe menu out when swipe menu closes

Stitch/Graph/Node/Port/Model/Field/FocusedUserEditField.swift, Stitch/Graph/Sidebar/View/SidebarItem/SidebarListLabelView.swift
https://github.com/user-attachments/assets/f4a00725-a215-4485-bdc6-7a344f815a88
=> Double-tap to edit sidebar layer's name

Stitch/Graph/Util/GraphActions.swift, Stitch/Graph/View/StitchProjectView.swift, Stitch/Graph/ViewModel/GraphState.swift, Stitch/Home/View/ProjectItem/ProjectsListItemBlurView.swift, Stitch/Home/View/ProjectItem/ProjectsListItemLoadedView.swift, Stitch/Home/View/ProjectItem/ProjectsListItemView.swift
Necessary change after async support for GraphState (plus it looks better).
=> Moved project loading UI to icon

Stitch/Graph/Node/Model/GraphCopyable.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarSelectedItemsDuplicated.swift
Regression with latest concurrency changes.
=> Fixed Option + drag sidebar dupe

Stitch/Graph/LayerInspector/LayerInspectorState.swift
=> Move sfSymbol, color, image, video etc. inputs higher in the layer inspector list

Stitch/Graph/Edge/View/ExistingEdgesView.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowViewModel.swift, Stitch/Graph/Node/View/NodesView.swift
Improvement due to an improved filter on "all inputs" that constrains data to just connected ones.
=> Reduced render count of edges view

Stitch/Graph/LayerInspector/GenericFlyoutView.swift, Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift
Do not assume layer input is unpacked in flyout row UI
=> Fix adjustment bar with inspector flyout fields

Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift, Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingView.swift, Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingViewReadOnly.swift, Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingViewWrapper.swift, Stitch/Graph/Node/Port/View/Field/InputView/FieldValueNumberView.swift
https://github.com/user-attachments/assets/239fff10-1ae5-4d1c-bbad-a15be7112801
=> Show picker for layer dimension, spacing etc. fields 

Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuSearchBar.swift
https://github.com/user-attachments/assets/a1ff10fd-9ed1-4697-9dde-25334d751507
=> More quickly focus the insert node menu search-bar when menu comes on-screen

Stitch/App/FeatureFlags.swift, Stitch/App/Serialization/DocumentEncodableUtil.swift, Stitch/App/Serialization/DocumentLoading/DocumentEncodable.swift, Stitch/App/Serialization/DocumentLoading/StitchFileManager.swift, Stitch/App/Serialization/Model/StitchDocumentEncodable.swift, Stitch/App/Serialization/StitchFileManagerProject.swift, Stitch/App/Serialization/Util/File/StitchDocumentURLUtils.swift, Stitch/App/Serialization/Util/File/StitchDocumentUtil.swift, Stitch/App/Serialization/Util/File/StitchFolderUtil.swift, Stitch/App/Shortcut/ProjectsHomeCommands.swift, Stitch/App/StitchApp.swift, Stitch/App/System/StitchSystemUtil.swift, Stitch/App/Util/Action/GraphReducer.swift, Stitch/App/Util/URL/URLExtensionUtils.swift, Stitch/App/View/StitchRootView.swift, Stitch/App/ViewModel/StitchStore.swift, Stitch/Graph/Menu/FileImportView.swift, Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenu.swift, Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuSearchBar.swift, Stitch/Graph/Node/Model/StitchClipboardContent.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift, Stitch/Graph/Sidebar/View/iPadProjectSidebarView.swift, Stitch/Graph/Util/GraphActions.swift, Stitch/Graph/Util/KeyBindingActions.swift, Stitch/Graph/Util/NodeSelection/CopyAndPasteNodesActions.swift, Stitch/Home/Util/ProjectDestructiveActions.swift
1. Changes existing logic to rely on encoders more, fixing URL getters that used to assume a top-level document
2. Removes `currentGraph` invocations which would often lead to getting the wrong graph state instance
3. Improves organization of files saved to temporary storage
4. Introduces logic to regularly delete files in temporary storage, including project files on project close as well as all temporary files each time the app launches
=> Improved media support for components and temp file handling

Stitch/Graph/Node/Eval/LoopLengths.swift, Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewSidebarHighlightModifier.swift, Stitch/Graph/Sidebar/Util/SidebarIcons.swift, Stitch/Graph/Sidebar/View/SidebarItem/SidebarListLabelView.swift
=> Use SFSymbol in sidebar layer

Stitch/Graph/StitchAI/StitchAIEvents.swift, Stitch/Graph/StitchAI/StitchAIPromptView.swift, Stitch/Graph/View/ContentView.swift
(forgot to add this to this pr): https://github.com/StitchDesign/Stitch/pull/428
=> stitch ai generation status

Stitch/Graph/LayerInspector/FlyoutUtils.swift, Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingView.swift, Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingViewWrapper.swift, Stitch/Graph/Node/Port/View/NodeInputOutputView.swift, Stitch/Graph/PrototypePreview/Layer/View/Type/TextField/PreviewTextFieldLayerUtils.swift
https://github.com/user-attachments/assets/fa6947f9-a12a-4f10-98fe-027883e7b82d
=> Auto-focus the clicked field when opening flyout

Stitch/Graph/LayerInspector/GenericFlyoutView.swift, Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/Node/Port/Util/Field/TabKeyPressActions.swift, Stitch/Graph/View/ContentView.swift
Note: still need to fix shadow flyout TABing?
https://github.com/user-attachments/assets/ed8b36bd-5f56-427e-a4eb-3fbed13847c8
=> Enable TABing with Flyouts

Stitch/Graph/Node/Port/Model/PortValue/Type/Shapes/ShapeUtils.swift, Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonModifierWithoutFrame.swift, Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift
=> Apply corner radius to layer group background and stroke

Stitch/Graph/Node/Title/Util/NodeTitleActions.swift, Stitch/Graph/Node/View/NodeTag/NodeTagMenuButtonsView.swift, Stitch/Graph/Node/View/NodeView.swift, Stitch/Graph/Sidebar/Util/Gesture/SidebarListItemActions.swift, Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemGestureRecognizerView.swift, Stitch/Graph/ViewModel/GraphUI.swift
https://github.com/user-attachments/assets/f76c4c1a-c8dc-40b0-a239-9e6841760900
=> Sidebar item right click option to hide layer; fix layer hiding via node tag menu; visually indicate hidden layer items on canvas

Stitch/Graph/Sidebar/Util/Gesture/SidebarListItemActions.swift, Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemGestureRecognizerView.swift
https://github.com/user-attachments/assets/ac26daca-b979-4e61-84e0-de0d07690470
=> Hide multiple layers via sidebar item right click

Stitch/Graph/StitchAI/LLMRecording/LLMActions/LLMActionRecording.swift
removes +0000 from llm json file names
=> fixed date format

Stitch/Graph/LayerInspector/LayerInspectorView.swift
=> Adding padding to right side and bottom of inspector

Stitch.xcodeproj/project.pbxproj, Stitch/Graph/LayerInspector/LayerInspectorPortView.swift, Stitch/Graph/LayerInspector/LayerInspectorState.swift, Stitch/Graph/Node/Model/RowData/LayerInputType.swift, Stitch/Graph/Node/Port/Model/Field/FieldGroupType.swift, Stitch/Graph/Node/Port/Model/Field/FieldValue.swift, Stitch/Graph/Node/Port/Model/Field/NodeRowType.swift, Stitch/Graph/Node/Port/Model/Field/SingleDropdownKind.swift, Stitch/Graph/Node/Port/Util/Field/FieldValueUtils.swift, Stitch/Graph/Node/Port/Util/Field/FieldViewModelTypeUtils.swift, Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift, Stitch/Graph/Node/Port/View/Field/InputView/LayerGroupOrientationDropDownChoiceView.swift, Stitch/Graph/Node/Port/View/Field/OutputValueView.swift, Stitch/Graph/Node/Port/ViewModel/FieldGroupTypeViewModel.swift
https://github.com/user-attachments/assets/c06a089b-9b97-4e80-83cb-8f57ace02f0e
=> Introduce segmented picker for layer group AutoLayout

Stitch/Graph/Node/Model/RowData/LayerInputType.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Layer/LayerDimensionUtils.swift, Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift, Stitch/Graph/Node/Port/View/Field/InputView/LayerGroupOrientationDropDownChoiceView.swift, Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewLayerSizeModifier.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupCreated.swift
=> Filter the options shown in layer dimension dropdown

Stitch/Graph/Node/Patch/Type/Delay/DelayNode.swift
https://github.com/user-attachments/assets/f926be83-1307-4c38-8812-4c168826d443
=> Delay node: immediately update output if value change did not conform to delay style

Stitch/App/Shortcut/ProjectsHomeCommands.swift, Stitch/App/Shortcut/ShortcutsUtils.swift
https://github.com/user-attachments/assets/2d851cc3-e380-4f84-a205-d01558b55273
=> Option + X to add splitter i.e. value node to graph

Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/Node/Layer/Type/HitAreaLayerNode.swift, Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewHitAreaLayer.swift
=> Add `scale` input to Hit Area layer; improve padding on inspector bottom

Stitch/Graph/PrototypePreview/Layer/View/GeneratePreview.swift, Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift
Resolves a regression with interactions on groups.
=> Smarter handling of hit area on empty layer groups

Stitch/App/Serialization/DocumentEncodableUtil.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift, Stitch/Graph/Node/Util/NodeDeletedAction.swift
Reverts #435 and improves logic to check for other nodes in graph.
=> Media deletes only when unused

Stitch/Graph/LayerInspector/GenericFlyoutView.swift, Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
https://github.com/user-attachments/assets/22158d77-ff69-4e13-a9a2-bb310a1e3a46
=> Fix adding individual fields to the canvas

Stitch/Graph/Node/Model/RowData/LayerInputType.swift
=> Use proper start color and anchor for Radial Gradient

Stitch/App/View/AppSettingsView.swift, Stitch/Graph/Node/Port/ViewModel/FieldGroupTypeViewModel.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowViewModel.swift, Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift, Stitch/Graph/StitchAI/LLMRecording/LLMActions/LLMActions.swift, Stitch/Graph/StitchAI/StitchAIConstants.swift, Stitch/Graph/StitchAI/StitchAIDataModel.swift, Stitch/Graph/StitchAI/StitchAIEvents.swift, Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift
PR containing work for: 
1) Schema updates 
2) System prompt updates 
3) Field value update logic (thanks to @pianostringquartet)
https://github.com/user-attachments/assets/89fa1ca8-4a55-442c-92b9-d7677d094bb1
=> WIP Stitch AI

Stitch.xcodeproj/project.pbxproj, Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Stitch/Graph/Sidebar/Util/Gesture/LegacySidebarActions.swift
=> Improved perf of sidebar drag with long range of items

Stitch/Graph/Sidebar/Model/Gesture/SidebarSelectionState.swift, Stitch/Graph/Sidebar/Util/Gesture/LegacySidebarActions.swift, Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemSwipeView.swift, Stitch/Graph/Util/NodeSelection/NodeSelectionUtil.swift, Stitch/Graph/ViewModel/GraphDelegate.swift, Stitch/Graph/ViewModel/GraphState.swift, Stitch/Graph/ViewModel/GraphUI.swift
Resolves issue where opacity was no longer updating when the sidebar lost focus.
=> Fixed sidebar focus UI polish regression

Stitch/Graph/LayerInspector/LayerInspectorView.swift
=> Less trailing padding and smaller width on inspector on iPad

Stitch/Graph/Sidebar/View/SidebarItem/SidebarListLabelView.swift
=> Smarter handling of debug id in sidebar layer

Stitch/App/Serialization/DocumentLoading/DocumentLoader.swift, Stitch/Graph/Node/Component/ComponentNavBarView.swift, Stitch/Graph/Node/Component/StitchMasterComponent.swift, Stitch/Graph/Node/Title/Util/NodeTitleActions.swift, Stitch/Graph/Node/Title/View/CanvasItemTitleView.swift, Stitch/Graph/Util/DocumentEncoder.swift, Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
Just in the node canvas item for now.
=> Support for component title edits

Stitch/Graph/Node/Patch/Type/ConvertPositionNode.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Anchoring/Anchoring.swift, Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/LayerSizeReader.swift, Stitch/Graph/PrototypePreview/Layer/ViewModel/LayerViewModel.swift
=> Use GeometryReader for proper ConvertPosition patch node logic

Stitch/Graph/Node/Patch/Type/Shape/LayerInfoNode.swift, Stitch/Graph/Node/Port/Util/NodeRowObserverUtil.swift
https://github.com/user-attachments/assets/8a1e006e-47d6-44e3-8ed0-e73ab764fabb
=> Update ConvertPosition node when its assigned layer has an input update

Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingView.swift
Currently we use app theme color.
=> Highlight currently focused field

Stitch/Graph/Node/Port/Util/PortValue/CoercerUtilHelpers/NumberCoercers.swift, Stitch/Graph/Node/Port/Util/PortValue/CoercerUtils.swift, Stitch/Graph/Node/Port/Util/PortValue/Coercers.swift
=> Pass graph-time to coercers, but do not pulse if graph-time is zero

Stitch/Graph/Util/PrototypeActions.swift, Stitch/Graph/ViewModel/GraphState.swift
https://github.com/user-attachments/assets/da1c5561-092c-4857-bdc5-78d212e80e3e
=> Restart graph time and frame count upon graph reset

Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuWrapper.swift, Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift, Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingViewWrapper.swift, Stitch/Graph/Node/Port/View/Field/InputView/FieldValueNumberView.swift, Stitch/Graph/Node/Port/View/Field/ValueButton/NumberValueButtonView.swift, Stitch/Graph/Node/View/NodeViewType.swift, Stitch/Graph/Node/View/NodesOnlyView.swift, Stitch/Graph/ViewModel/GraphUI.swift
Caused some render cycles and really isn't used.
=> Removed AdjustmentBarSessionId for perf

Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputUnpackedPortObserver.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
This PR cuts render cycles in half for fields views.
=> Improved perf with fields debouncer

Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingView.swift, Stitch/Graph/Node/View/NodeView.swift
https://github.com/user-attachments/assets/ac7fb0a6-f6f9-408b-adf5-622268a206e2
=> Increase hit area on LayerDimension chevron and CanvasItem's tag menu

Stitch.xcodeproj/project.pbxproj, Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Stitch/Graph/Sidebar/Model/Gesture/SidebarSelectionState.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupCreated.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarListItemSelectionActions.swift, Stitch/Graph/Sidebar/ViewModel/ProjectSidebarObservable.swift, Stitch/Graph/Sidebar/ViewModel/SidebarItemSwipable.swift
A few issues with identifying correct grouping candidates along with selection logic too frequently grabbing secondarily selected elements.
=> Fixed sidebar grouping + selection regressions

Stitch/Graph/Node/Port/Util/TypeChange/NodeTypeChangedHelpers.swift
Caused by recent throttling perf improvement.
=> Fixed node type change inputs regression

Stitch/Graph/Node/Port/Model/Field/FieldValue.swift, Stitch/Graph/Node/Port/Model/Field/LayerDimensionField.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Layer/StitchSpacingUtils.swift, Stitch/Graph/Node/Port/Util/PortValue/PortValueDisplay.swift, Stitch/Graph/Node/Port/ViewModel/NumberFormatterObserver.swift
This reverts commit 63eab35b8513ca3c8b6e75a6c9ad9c5f129f8f58.
Very marginal perf loss here so ok to keep.
=> Revert "Disabled number formatter for perf (#524)"

Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift, Stitch/Graph/ViewModel/GraphState.swift, Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
Two scenarios fixed:
1. On node deletion with downstream layer input
2. Outputs on graph initialization
=> Fixed port color regressions

Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/Node/Layer/Type/GroupLayerNode.swift, Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonSizeModifier.swift, Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift
=> Support shadows on layer groups with non-clear backgrounds

Stitch/Graph/ViewModel/GraphUI.swift
This fixes a regression where we crash because clipboard data encounters an unknown node. This issue is caused by out of date layer data for `LayerNodeViewModel`. The fix is using sidebar data for finding group data.
In the future we should remove the group ID property in `LayerNodeEntity`.
=> Fixed crash from sidebar duplication after drag

Stitch/Graph/Node/Port/Model/PortValue/Type/Shapes/JSON/JSONShapeCommandParsing.swift
Use a custom key-decoding strategy to handle e.g. when json used "X" instead of "x" for key.
Note: may be better alternatives for perf? e.g. manually implement Decodable on ShapeCommand
=> Parse ShapeCommand JSON's x and y keys even if capitalized

Stitch/Graph/Node/Patch/Type/Shape/JSONToShapeNode.swift, Stitch/Graph/Node/Patch/Util/PatchUtils.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Shapes/JSON/JSONShapeCommandParsing.swift
https://github.com/user-attachments/assets/e4991853-af5b-4360-9787-e477737c9025
=> Reintroduce JSON-To-Shape patch node; clickable error output

Stitch/Graph/Node/Port/View/Field/InputView/EditJSONEntry.swift
https://github.com/user-attachments/assets/002e7482-a4eb-4bce-9031-4a3ccf267a8d
=> Persist project when editable json popover closes

Stitch/Graph/Node/Patch/Type/ConvertPositionNode.swift, Stitch/Graph/Node/Patch/Type/Shape/LayerInfoNode.swift
=> Report looped layers' info in LayerInfo patch node

Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
https://github.com/user-attachments/assets/f6cac0e0-d27b-4a3f-9102-f0a074ba8e1e
https://github.com/user-attachments/assets/6778f89b-77f0-4208-b1f6-9590456b8577
=> Do not reset sidebar selections after duplicating layer nodes

Stitch/App/Serialization/DocumentLoading/DocumentEncodable.swift, Stitch/App/System/StitchSystemViewModel.swift, Stitch/App/ViewModel/StitchStore.swift, Stitch/App/ViewModel/StitchUndoManager.swift, Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/Node/Component/ComponentNavBarView.swift, Stitch/Graph/Node/Component/StitchComponentViewModel.swift, Stitch/Graph/Node/Component/StitchMasterComponent.swift, Stitch/Graph/Node/Model/GraphCopyable.swift, Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift, Stitch/Graph/PrototypePreview/Layer/Util/LayerNodesSorting.swift, Stitch/Graph/Sidebar/Util/Gesture/LegacySidebarActions.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarSelectedItemsDuplicated.swift, Stitch/Graph/Util/GraphActions.swift, Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift, Stitch/Graph/ViewModel/GraphState.swift, Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
https://github.com/user-attachments/assets/0ddea06d-7067-4a28-8c03-8e259862cb13
https://github.com/user-attachments/assets/c5733b08-0cbe-468d-a60d-f7e68a80f6a5
=> Insert duplicated layer nodes after first layer node in original selection

Stitch/Graph/Node/Model/GraphCopyable.swift, Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift, Stitch/Graph/Util/NodeSelection/CopyAndPasteNodesActions.swift, Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
https://github.com/user-attachments/assets/0cc6965e-0dd9-4d28-aa55-af2b230a9396
=> Stagger duplicated nodes, center copy-pasted nodes

Stitch/App/View/StitchRootView.swift, Stitch/Graph/Menu/FileImportView.swift, Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuWrapper.swift, Stitch/Graph/Node/Group/GroupNodeCreationActions.swift, Stitch/Graph/Node/Util/NodeCreatedAction.swift, Stitch/Graph/Util/GraphUIActions.swift, Stitch/Graph/View/GraphBaseView.swift, Stitch/Graph/ViewModel/GraphUI.swift
https://github.com/user-attachments/assets/3ace37be-d30b-42e5-9d75-2357f779528d
=> Keep node menu in center of graph

Stitch/Graph/Gesture/Model/GraphMultigesture.swift, Stitch/Graph/Gesture/Util/GraphUIScrollActions.swift, Stitch/Graph/Gesture/Util/GraphUIZoomedActions.swift, Stitch/Graph/Gesture/View/GraphMovementViewModifier.swift, Stitch/Graph/Gesture/ViewModel/GraphMovementObserver.swift, Stitch/Graph/Node/Port/View/NodeInputOutputView.swift, Stitch/Graph/Node/Port/View/PortView.swift, Stitch/Graph/Node/View/NodesView.swift, Stitch/Graph/Node/ViewModel/NodePageData.swift, Stitch/Graph/View/Gesture/GraphBackgroundGestureView.swift, Stitch/Graph/View/GraphBaseView.swift, Stitch/Graph/ViewModel/GraphUI.swift, Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
This PR significantly improves perf for logic used to create edges. The solution entails smarter control for when we update port locations by blacklisting updates during graph panning and zooming gestures.
=> Improved perf impact from port location updates

Stitch/Graph/Node/View/NodeView.swift
=> Apply color to visual effect view in canvas background view

Stitch.xcodeproj/project.pbxproj, Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Stitch/Graph/Node/Eval/PatchEvaluateExtensions.swift, Stitch/Graph/Node/Model/Definition/PatchNodeDefinitionKinds.swift, Stitch/Graph/Node/Model/Definition/StitchNodeNames.swift, Stitch/Graph/Node/Patch/Type/Animation/SpringConverterPatches.swift, Stitch/Graph/Node/Patch/Util/PatchDescription.swift, Stitch/Graph/Node/Patch/Util/PatchUtils.swift
https://github.com/user-attachments/assets/27683b5e-6c99-43e7-b8ef-fd185b3c9a33
=> Introduce spring converter nodes for easier use of spring animation node

Stitch.xcodeproj/project.pbxproj, Stitch/App/Shortcut/PatchNodeShortcutKeys.swift, Stitch/App/Shortcut/ProjectsHomeCommands.swift, Stitch/App/Shortcut/ShortcutsUtils.swift
=> Introduce additional patch node shortcuts

Stitch/Graph/LayerInspector/FlyoutUtils.swift, Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingView.swift, Stitch/Graph/Node/Title/View/CanvasItemTitleView.swift, Stitch/Graph/Node/Title/View/NodeTitleTextField.swift, Stitch/Graph/Node/View/NodeView.swift, Stitch/Graph/PrototypePreview/Layer/View/Type/TextField/PreviewTextFieldLayerUtils.swift, Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift, Stitch/Graph/Util/GraphUIActions.swift
https://github.com/user-attachments/assets/079542ff-13da-4efc-a7e9-2fb10d90a14b
=> Tap node body to defocus field

Stitch/Graph/LayerInspector/ShadowFlyoutView.swift, Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
Fixes recent regression from UI perf work.
=> Show shadow input in inspector

Stitch/Graph/Node/Patch/Type/Math/MathExpressionNode.swift, Stitch/Graph/Node/Patch/ViewModel/PatchNodeViewModel.swift
https://github.com/user-attachments/assets/f50e26b7-0357-4748-8601-aa0a915516d8
=> Ignore numbers in MathExpression formula; fix inputs

Stitch/App/View/ViewUtil/StitchHostingController.swift, Stitch/Graph/Edge/Util/EdgeEditingActions.swift, Stitch/Graph/Node/Patch/Type/Interaction/Keyboard/KeyPressActions.swift, Stitch/Graph/Node/Patch/Type/Interaction/Keyboard/KeyboardNode.swift, Stitch/Graph/PrototypePreview/Frame/View/PreviewContent.swift
Resolves a keyboard patch node regression.
=> Listen for key commands on PreviewContent ie preview window

Stitch/Graph/LayerInspector/LayerInspectorActions.swift, Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6699
=> Fixed regression where layer input wouldn't appear

Stitch/Graph/Node/Title/Util/NodeTitleActions.swift, Stitch/Graph/Node/View/NodeViewType.swift, Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift
https://github.com/StitchDesign/Stitch--Old/issues/6702
=> Fixed port locations regression on node title edit

Stitch/Graph/Node/Patch/ViewModel/PatchNodeViewModel.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6705.
Issue doesn't appear to be a new regression—here we were incorrectly creating new objects for input row observers when in-place syncing should have taken place.
=> Fixed bug where edges wouldn't appear for new math expression inputs

Stitch/Graph/Node/Patch/ViewModel/PatchNodeViewModel.swift, Stitch/Graph/View/SelectionBox/ExpansionBoxView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6701.
=> Fixed selection box fill color regression

Stitch/App/Shortcut/ProjectsHomeCommands.swift, Stitch/App/Shortcut/ShortcutsUtils.swift, Stitch/Graph/Node/Group/GroupNodeCreationActions.swift, Stitch/Graph/Node/Group/GroupNodeDestructionActions.swift, Stitch/Graph/Node/View/NodeTag/NodeTagMenuButtonsView.swift
Similar to how CMD+G groups layers and CMD+Delete ungroups layers in the sidebar.
https://github.com/user-attachments/assets/d1addb86-14ad-4c83-881c-70bb50993b7d
=> Use CMD+G to group nodes, CMD+Delete to ungroup nodes

Stitch/Graph/Node/View/NodesOnlyView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6710
=> Fixed regression where nodes in group couldn't be selected

Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6708
=> Fixed node selection box regression on node drag

Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewImage.swift
(Green border was debug.)
https://github.com/user-attachments/assets/0f112794-10c0-4cb5-acca-e27d760340ff
=> Better hit areas on images with fitStyle = .fit

Stitch/Graph/Node/Model/GraphCopyable.swift, Stitch/Graph/Node/Model/NodeEntity.swift, Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift, Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
https://github.com/user-attachments/assets/97b2ccdd-1d5a-44d3-baf3-f7ed99b88a6d
=> Stagger 'inputs on canvas' when duplicating a layer

Stitch/Graph/LayerInspector/GenericFlyoutView.swift, Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
https://github.com/user-attachments/assets/07d7a26a-904c-4484-b61a-6846657ac4db
=> Be able to select individual flyout rows on iPad

Stitch.xcodeproj/project.pbxproj, Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupCreated.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6715
=> Fixed various layer grouping bugs

Stitch/Graph/Node/Port/View/Field/InputView/LayerNamesDropDownChoiceView.swift
=> Show nesting level in layer choice dropdown

Stitch/Graph/LayerInspector/ShadowFlyoutView.swift
https://github.com/user-attachments/assets/eb8afcab-e6ee-4365-a6b1-907607abf755
=> Add individual shadow inputs to the canvas

Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
https://github.com/user-attachments/assets/f675f5ac-3643-45ad-a23a-67c0bbc5c9ee
=> Do not show 'add to canvas' button for shadow row on inspector

Stitch/Graph/Node/Port/Util/Field/TabKeyPressActions.swift
https://github.com/user-attachments/assets/c856c791-6fc5-4eaa-9fed-d19bba96ce89
=> Support tabbing in shadow flyout

Stitch/Graph/Node/Patch/Type/Pack/MoveToPackNode.swift, Stitch/Graph/Node/Patch/Type/Pack/PackNode.swift, Stitch/Graph/Node/Patch/Type/Pack/PackNodeHelpers.swift, Stitch/Graph/Node/Patch/Type/Unpack/UnpackNode.swift, Stitch/Graph/Node/Patch/Util/PatchUtils.swift
We no longer include the generic Pack and Unpack nodes in the patch list.
=> Prefer specifically Patck and Unpack nodes to their generic version

Stitch/App/Serialization/DocumentLoading/StitchFileManager.swift, Stitch/Graph/Node/Util/NodeDeletedAction.swift, Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PinningUtils.swift
https://github.com/user-attachments/assets/3cf69fba-8dfa-4902-bc9e-502cc8b0ed25
=> When layer deleted, remove its layerId from inputs

Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift, Stitch/Graph/Node/ViewModel/NodeViewModel.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6745
=> Fixed layer inspector regressions from perf changes

Stitch/Graph/PrototypePreview/Frame/View/NativeScrollGestureView.swift, Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift
https://github.com/user-attachments/assets/87e07253-b303-4259-bc9c-df0daf4e7e7a
=> Disable or enable ScrollView clipping according to Group's clipped input

Stitch/Graph/Node/Util/NodeDeletedAction.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6753
=> When layer's canvas output deleted, remove reference from connected downstream inputs

Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift, Stitch/Graph/Node/Port/View/Field/InputView/ReadOnlyEntry.swift, Stitch/Graph/Node/Port/View/Field/OutputValueView.swift, Stitch/Graph/Node/Port/View/NodeInputOutputView.swift, Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift
=> Layer inspector: do not go out of bounds with a multifield output

Stitch/Graph/StitchAI/GraphPrompting/UI/StitchAIErrorModalView.swift
Fixing how we paste an error message int he stitch ai modal. 
New example:
```
Message: The data couldn’t be read because it is missing.
User Prompt: Find the square root of e times 2 to power of 99
Response: {
"id": "chatcmpl-An8pYXknkZTa541sGHjRggfmW8uWS",
"object": "chat.completion",
"created": 1736275380,
"model": "ft:gpt-4o-2024-08-06:adammenges::AdhLWSuL",
"choices": [
{
"index": 0,
"message": {
"role": "assistant",
"content": "{\"steps\":[{\"node_name\":\"multiply || Patch\",\"node_id\":\"B6D719AB-55E4-40F0-88A0-13730D183B3F\",\"step_type\":\"add_node\"},{\"node_id\":\"8D8AF67A-9533-457B-8AA6-522213906C8D\",\"node_name\":\"value || Patch\",\"step_type\":\"add_node\"},{\"step_type\":\"set_input\",\"port\":0,\"value\":2.71828,\"node_id\":\"8D8AF67A-9533-457B-8AA6-522213906C8D\"},{\"fr …
```
=> fix copy and paste formatting

Stitch/Graph/Util/GraphUIActions.swift
https://github.com/user-attachments/assets/224899d9-655d-4a06-bb06-27f6a7ff9160
=> ensure we prioritize the node titles over descriptions when searching 

Stitch/Graph/Util/GraphUIActions.swift
=> match boolean nodes to string queries

Stitch/Graph/Util/GraphUIActions.swift
=> search fixes

Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift
throws a network error to the ui if we either: 
* have 3 consecutive request timeout errors
* encounter a network connectivity error directly
=> adding logic for network connectivity alerts in the ai request

Stitch/Graph/Node/Port/View/Field/WirelessPortView.swift, Stitch/Graph/Sidebar/Util/JumpToCanvasItem.swift
https://github.com/user-attachments/assets/18ff3c62-02c2-4801-bba4-3d47c4ceb08a
=> Click wireless receiver's icon to jump to its assigned broadcaster

Stitch/Graph/LayerInspector/GenericFlyoutView.swift, Stitch/Graph/Node/Port/View/Field/NodeFieldsView.swift, Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
=> Resolve flyout and inspector UI regressions

Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift, Stitch/Graph/Node/Port/View/Field/NodeFieldsView.swift
=> Labels for individual 3D Transform fields on canvas

Stitch/Graph/LayerInspector/GenericFlyoutView.swift, Stitch/Graph/LayerInspector/LayerInspectorActions.swift
Second half of video shows adding one field for every sidebar-selected layer. 
https://github.com/user-attachments/assets/51c508b1-9259-49d3-ac38-f6728296fa6c
=> Add input field for every layer selected in sidebar

Stitch/Graph/PrototypePreview/Layer/ViewModel/LayerViewModel.swift, TestFlight/WhatToTest.en-US.txt
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6798
=> Fixed camera feed stutters

Stitch.xcodeproj/project.pbxproj, Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6805
=> Support for single-node cycles

Stitch/Graph/Node/View/StitchUIScrollView.swift
Validated iPad is good too.
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6796
=> Fixed scroll wheel regression with canvas panning

Stitch/Graph/Node/View/StitchUIScrollView.swift, Stitch/Graph/ViewModel/GraphUI.swift
Sort of fixes a regression here. CMD + scroll is much worse now with our new scroll logic. Will improve another day, for now it's better than nothing.
=> Re-added support for a worse CMD + scroll

Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
https://github.com/user-attachments/assets/c051027f-1d71-4ddb-bc72-7e6a8147b98e
=> Do not rely on delegate to re-render inspector output view

Stitch/Graph/Node/Port/Model/Field/FieldValue.swift, Stitch/Graph/Node/Port/ViewModel/NumberFormatterObserver.swift
Follow up from https://github.com/StitchDesign/Stitch/pull/690
=> Allow more decimal places in UI fields using FieldValue

Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/CameraFeed/Reference/CameraFeedManager.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/CameraFeed/Util/CameraUtil.swift
Adds back a check that possibly saves crashes on iPad.
=> Reverts camera feed creation logic

Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/CameraFeed/Reference/CameraFeedActor.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/CameraFeed/Util/CameraOrientation.swift
https://github.com/user-attachments/assets/18c76191-f517-450c-9fae-5073767218c7
https://github.com/user-attachments/assets/5688729e-ff62-4a8d-a1ef-df4fe5a4ce5b
=> Fix camera patch orientation

Stitch/Graph/Node/Port/View/Field/NodeFieldsView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6813
=> better color for group label

Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/AR/ARUtils.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6806
=> Improved reliability of AR transform updates

Stitch.xcodeproj/project.pbxproj, Stitch/Graph/Menu/InsertNodeMenu/Model/InsertNodeMenuState.swift, Stitch/Graph/Node/Model/Definition/StitchNodeNames.swift, Stitch/Graph/StitchAI/DatasetRecording/LLMActionRecording.swift, Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift, Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift, Stitch/Graph/StitchAI/GraphPrompting/API/ProccessInfo+Extension.swift, Stitch/Graph/StitchAI/GraphPrompting/API/SupabaseManager.swift, Stitch/Graph/StitchAI/GraphPrompting/UI/JSONEditorView.swift, Stitch/Graph/StitchAI/SYSTEM_PROMPT.txt, Stitch/Graph/StitchAI/StitchStructuredOutputSchema.json, Stitch/Graph/StitchAI/SupabaseManager.swift, Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift, Stitch/Graph/Toolbar/View/TopBarButtonView.swift, Stitch/Graph/Util/GraphUIActions.swift, Stitch/Graph/View/ContentView.swift, Stitch/Graph/ViewModel/GraphState.swift, Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
To Test: 
1) Make a test example via the llm actions flow; and verify that it is in the Supabase table
2) Generate some JSON from Open AI, THEN start the llm actions flow to add to the graph
We need to also verify that al JSON is formatted correctly in the Supabase entries
=> Edit Mode for StitchAI / Some Schema Updates

Stitch/Graph/Node/Port/View/Field/OutputValueView.swift, Stitch/Graph/PrototypePreview/Frame/View/FloatingWindowView.swift, Stitch/Graph/PrototypePreview/Frame/View/FullScreenPreviewViewWrapper.swift, Stitch/Graph/PrototypePreview/Frame/View/PreviewContent.swift
Todo?: smarter place to listen for keys?
https://github.com/user-attachments/assets/36a371d8-f60e-4aca-a5fc-9615867ffa20
=> Listen for keys via PreviewContent's UIKitWrapper even when preview window offscreen

.env, .gitignore, Stitch.xcodeproj/project.pbxproj, Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Stitch/App/FeatureFlags.swift, Stitch/Graph/Menu/InsertNodeMenu/Model/InsertNodeMenuState.swift, Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuSearchBar.swift, Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift, Stitch/Graph/StitchAI/GraphPrompting/API/Secrets.swift, Stitch/Graph/StitchAI/GraphPrompting/API/SupabaseManager.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepActionToStateChange.swift, StitchTests/supabaseMangerTests.swift, ci_scripts/ci_pre_xcodebuild.sh
* Set up working Xcode cloud based infra for API keys (Nick)
* Retry if LLM attempted to change the node type of a non-patch or suggested a node type not possible for that patch (Chris)
=> Xcode Cloud workflow changes + Some Retry Logic

Stitch/App/View/Component/StitchTextEditingField.swift, Stitch/Graph/Edge/Util/PortActions.swift, Stitch/Graph/Edge/Util/PortDragActions.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/JSON/JSONUtils.swift, Stitch/Graph/Node/Port/Util/InputEdit/InputCommittedActions.swift, Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift, Stitch/Graph/Node/Util/NodeKindUtils.swift, Stitch/Graph/StitchAI/GraphPrompting/API/SupabaseManager.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StateChangeToStepAction.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepActionToStateChange.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StitchAIDataModel.swift, Stitch/Graph/StitchAI/GraphPrompting/UI/JSONEditorView.swift
Uploading Screen Recording 2025-01-25 at 7.45.02 PM.mov…
=> LLM Correction UI; create SetInput action when textfield disappears

Stitch/Graph/Menu/NumberAdjustmentBar/AdjustmentBarPopoverView.swift, Stitch/Graph/Menu/NumberAdjustmentBar/WideAdjustmentBarView.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/CameraFeed/Util/CameraUtil.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift, Stitch/Graph/Node/Port/Util/InputEdit/InputCommittedActions.swift, Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift, Stitch/Graph/Node/Port/Util/InputEdit/PickerActions.swift, Stitch/Graph/Node/Port/View/Field/InputView/AnchorEntitiesDropdownView.swift, Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingView.swift, Stitch/Graph/Node/Port/View/Field/InputView/EditJSONEntry.swift, Stitch/Graph/Node/Port/View/Field/InputView/LayerNamesDropDownChoiceView.swift
Also removes some redundant input-editing methods.
=> Create LLMSetInput action when dropdown used

Stitch/Graph/Node/Port/Util/PortValue/CoercerUtilHelpers/NumberCoercers.swift
=> Coerce number-jsons to numbers

Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenu.swift, Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift
https://github.com/user-attachments/assets/a2570609-6b2a-4451-8edc-cf03478f7988
=> Logic to cancel an in-progress AI request if the insert node menu is dismissed

Stitch/Graph/StitchAI/SYSTEM_PROMPT.txt
=> layers can never have their type changed

Stitch/Graph/Node/Port/Model/PortValue/Type/JSON/JSONUtils.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/LLMValueParsingUtils.swift, Stitch/Graph/StitchAI/GraphPrompting/UI/EditBeforeSubmitModalView.swift
Adding back some debug statements as well.
=> If string JSONFriendlyFormat but not a string node type, attempt to parse as a json

Stitch/Graph/Node/Layer/Type/Media/3DModelLayerNode/PreviewModel3DLayer.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6838.
=> Fixed bug where 3D model entities wouldn't remove from a reality view

Stitch/Graph/Node/View/StitchUIScrollView.swift
Previously this was getting stopped in the middle of the animation because some nodes were going off screen and caught by the border check. 
https://github.com/user-attachments/assets/151f73f8-678c-49f9-a729-76f19419548e
=> Disable border checking for 1 second after we jump to a canvas item

Stitch/Graph/LayerInspector/Model/LayerInspectorSection.swift
=> Place Text Font input above Text Size input

Stitch/Graph/StitchAI/DatasetRecording/LLMActionPositionNodeUtil.swift
=> cycles check logic fix 

Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift, Stitch/Graph/Node/Port/View/Field/OutputValueView.swift, Stitch/Graph/Node/Util/NodeMediaUtils.swift
Gets fields working again after recent changes.
=> Fixed media fields view regression

Stitch/Graph/Node/Patch/Type/Loop/LoopReverseNode.swift
=> display default user visible type

Stitch/Graph/Node/Patch/Type/Interaction/DragInteractionPatchNode.swift
https://github.com/user-attachments/assets/d9d39ee3-c560-431c-86e4-66f1e3960003
=> Enable input on drag interaction now actually enables or disables drag

Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StateChangeToStepAction.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/Step.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepActionToStateChange.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepTypeAction.swift, Stitch/Graph/StitchAI/GraphPrompting/UI/EditBeforeSubmitModalView.swift, Stitch/Graph/StitchAI/StitchAISystemPrompt.swift, Stitch/Graph/StitchAI/StitchStructuredOutputSchema.json
* Some prompt change
* NodeType / ValueType updates
* Step Parsing updates with Elliot 
**Make sure to re-run the `setup_secrets.sh` script in the shared folder to update to the new model **
=> New Model Changes

Stitch/Graph/Node/Patch/Type/DeviceMotionNode.swift, Stitch/Graph/Node/Util/NodeCreatedAction.swift, Stitch/Graph/ViewModel/GraphState.swift
Resolves bug where motion managers were broken upon project reopen.
=> Create motion manager in device motion eval

Stitch/Graph/Node/View/StitchUIScrollView.swift, Stitch/Graph/Util/GraphUIActions.swift, Stitch/Graph/ViewModel/GraphUI.swift
https://github.com/user-attachments/assets/c8e126c5-5f4e-445c-b52b-f1e8e21d833c
=> Smoother zooming out when using shortcut keys near max-zoom-out level

Stitch.xcodeproj/project.pbxproj, Stitch/App/ViewModel/StitchStore.swift, Stitch/Graph/ViewModel/HomescreenProjectSelectionState.swift, Stitch/Home/View/ProjectItem/ProjectsListItemLoadedView.swift, Stitch/Home/View/ProjectItem/ProjectsListItemView.swift, Stitch/Home/View/ProjectsHomeView.swift
Need proper UI for this + project searchbar.
Instead of 'Delete' button at top of homescreen we'd make the right-click menu on a given project read e.g. "Delete 20 Projects" or "Share 8 Projects" etc.
https://github.com/user-attachments/assets/ee8b713d-b098-4138-9cfb-b2463057bd65
=> Debug Mode: select multiple projects on the homescreen

Stitch/Graph/StitchAI/DatasetRecording/LLMActionHelpers.swift, Stitch/Graph/StitchAI/DatasetRecording/LLMActionRecording.swift, Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift, Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift, Stitch/Graph/StitchAI/GraphPrompting/API/SupabaseManager.swift
Fixing flows for sending augmentation flag to supabase
=> Augmentation state flag fix

Stitch/Graph/Util/GraphUIActions.swift
https://github.com/user-attachments/assets/206df5e0-c4ff-4629-882e-e98f92289c36
=> add logic for old origami node search (when prototype start)

Stitch/Graph/Util/GraphUIActions.swift
https://github.com/user-attachments/assets/1a2ad3d7-17d5-4558-ae9c-ff6af3a6e584
=> prioritize node titles over node descriptions

Stitch/App/Serialization/Model/StitchFileError.swift, Stitch/Graph/Menu/InsertNodeMenu/Util/InsertNodeMenuActions.swift, Stitch/Graph/Node/Util/NodeCreatedAction.swift
https://github.com/user-attachments/assets/db3dd413-737f-4702-9b65-2138c95c32d1
=> Camera or reality view duplicate alert

Stitch/Graph/Util/GraphUIActions.swift
=> add logic for text split -> text split

Stitch/Graph/StitchAI/GraphPrompting/DataModel/OpenAIResponseStructs.swift
Solution was to modify our steps examples to include a connection getting created.
=> Improved Stitch AI connection creation accuracy

Stitch/App/Serialization/DocumentLoading/DocumentLoader.swift, Stitch/App/Serialization/FileDropHandling.swift, Stitch/App/Serialization/Util/File/StitchCustomURL.swift, Stitch/App/Shortcut/ProjectsHomeCommands.swift, Stitch/App/View/StitchRootModifier.swift, Stitch/Home/Util/ProjectCreatedActions.swift, Stitch/Home/View/ProjectsHomeViewWrapper.swift
https://github.com/user-attachments/assets/06379c2f-d16b-4256-af9f-b04c2a230218
=> Update preview window size when project first imported

Stitch/Graph/Node/Patch/Type/Interaction/DragInteractionPatchNode.swift
https://github.com/user-attachments/assets/b8d5c802-2cf7-4c90-93ec-8d12d4f5daff
=> Graph reset and open trigger Drag's start input

Stitch/App/Util/TypeExtension/UIDeviceUtils.swift
=> Mac device info node support

Stitch/Graph/Node/Model/RowData/LayerInputType.swift
https://github.com/user-attachments/assets/cfc2d108-f45f-4bc2-9bfc-a24403acf0f1
=> Regenerate preview layers when orientation input changes

Stitch/Graph/Node/Eval/LoopedEval.swift, Stitch/Graph/Node/Layer/Util/Interactions.swift, Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift, Stitch/Graph/Node/ViewModel/NodeViewModel.swift
https://github.com/user-attachments/assets/a294d9c8-3e27-4199-b1d6-531d05b99bc7
=> If layer input's loop length changes, recalculate graph from layer's associated interaction patch nodes

Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift
Slight improvement to https://github.com/StitchDesign/Stitch/pull/831/files
=> When layer input loop length changes, eval associated interaction patch nodes on next graph step

Stitch/Graph/Node/Patch/Type/Media/MicrophoneFeedNode.swift, Stitch/Graph/Node/Patch/Type/Media/SpeakerNode.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Models/StitchMediaObject.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Sound/StitchAudio.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Sound/StitchMicrophone.swift
Seemingly concurrency-related issues.
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6837
=> Fixed microphone

Stitch/Graph/Edge/View/ExistingEdgesView.swift, Stitch/Graph/Model/GroupNodeType.swift, Stitch/Graph/Node/Group/GroupNodeCreationActions.swift, Stitch/Graph/Node/ViewModel/NodeViewModel.swift, Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift, Stitch/Graph/View/ProjectNavigationView.swift, Stitch/Graph/ViewModel/GraphState.swift
Tagging https://github.com/StitchDesign/Stitch--Old/issues/6899, https://github.com/StitchDesign/Stitch--Old/issues/6937, https://github.com/StitchDesign/Stitch--Old/issues/6936. Will close when fix is validated.
=> Simplified graph initialization calls for improved perf

Stitch/Graph/StitchAI/GraphPrompting/DataModel/StateChangeToStepAction.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/Step.swift
=> encode ports as strings or ints as appropriate

Stitch/Graph/Node/Patch/Type/DeviceInfoNode.swift
=> capitalize light and dark options

Stitch/Graph/Node/Patch/Type/DeviceInfoNode.swift
=> use the state's color value in device info node

Stitch/Graph/Node/Patch/Type/Value/SplitterPatchNode.swift, Stitch/Graph/Node/Port/Util/PortValue/CoercerUtilHelpers/NumberCoercers.swift, Stitch/Graph/Node/Port/Util/PortValue/Coercers.swift, Stitch/Graph/Node/Port/Util/PortValue/JSONCoercionUtils.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StitchAICodableTypes.swift, StitchTests/openAIRequestTests.swift
[JSON Conversion Examples.stitch.zip](https://github.com/user-attachments/files/18951784/JSON.Conversion.Examples.stitch.zip)
=> Smarter coercion of JSON to PortValue

Stitch/Graph/Node/Port/Util/Field/FieldValueUtils.swift
=> Use .display instead of .rawValue for FitStyle

Stitch/Graph/Node/Model/Definition/PatchNodeDefinitionKinds.swift, Stitch/Graph/Node/Patch/Type/Loop/LoopRemoveNode.swift, Stitch/Graph/Node/Patch/Util/PatchDefaultNodeExtensions.swift, Stitch/Graph/Node/Patch/Util/PatchNodeTypeExtensions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6826
https://github.com/user-attachments/assets/3deedb7a-56b0-4a14-a6c1-e572b8ff101f
https://github.com/user-attachments/assets/11e42a95-3c49-42f0-818a-e38efe3623cb
=> Fix LoopRemove node types and eval

Stitch/Graph/Node/Model/Definition/StitchNodeNames.swift
=> removing extra spaces in smooth value node description

Stitch/Graph/Node/Patch/Util/PatchNodeTypeExtensions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6841
=> Do not support node types on Delay node

Stitch/Graph/Node/Eval/PatchEvaluateExtensions.swift, Stitch/Graph/Node/Patch/Type/Logic/EqualsExactly.swift, Stitch/Graph/Node/Patch/Util/PatchNodeTypeExtensions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6959
=> Support loops and all types and additional inputs with equals exactly patch

Stitch/Graph/Node/Port/Util/PortValue/PortValueDisplay.swift
https://github.com/user-attachments/assets/ff4181b6-2a70-4af0-a781-ce6dc650be2a
=> use ordered dict for various string coercions

Stitch/Graph/Node/Eval/PatchEvaluateExtensions.swift, Stitch/Graph/Node/Patch/Type/Logic/GreaterOrEqualNode.swift, Stitch/Graph/Node/Patch/Type/Logic/GreaterThanNode.swift, Stitch/Graph/Node/Patch/Type/Logic/LessThanNode.swift, Stitch/Graph/Node/Patch/Type/Logic/LessThanOrEqualNode.swift, Stitch/Graph/Node/Patch/Util/PatchNodeTypeExtensions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6960
=> Support loops and adding-inputs on GT, GTE, LT, LTE patches

Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
https://github.com/user-attachments/assets/f78b8131-51ce-4317-aea3-9327229a6a73
=> Adjust pasted canvas items' positions according to which are actually visible at current traversal level

Stitch.xcodeproj/project.pbxproj, Stitch/Graph/Node/ViewModel/LayerEphemeralState.swift, Stitch/Graph/PrototypePreview/Layer/ViewModel/LayerViewModel.swift
https://github.com/user-attachments/assets/1628955b-d174-4f7a-bf7b-0ff3364e6f66
=> Reset layer's ephemeral state (canvas sketch lines, text field input etc.) when graph reset

Stitch/Graph/Node/Patch/Type/ConvertPositionNode.swift, Stitch/Graph/Node/Patch/Type/OptionEqualsNode.swift, Stitch/Graph/Node/Patch/Type/OptionSenderNode.swift, Stitch/Graph/Node/Patch/Type/Pulse/RestartPrototypeNode.swift, Stitch/Graph/Node/Patch/Type/Text/TextTrimNode.swift, Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift, Stitch/Graph/Node/View/StitchUIScrollHelpers.swift, Stitch/Graph/StitchAI/DatasetRecording/LLMModalViews.swift, Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift, Stitch/Graph/View/GraphBaseView.swift, Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
=> Show prompt in LLM confirmation modal; comment out various logs

Stitch/Graph/LayerInspector/GenericFlyoutView.swift, Stitch/Graph/LayerInspector/LayerMultiselect.swift, Stitch/Graph/Node/Layer/Model/LayerNodeData.swift, Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift, Stitch/Graph/Node/Port/View/Field/InputView/AnchorPopoverView.swift, Stitch/Graph/Node/Port/View/Field/InputView/BoolCheckboxView.swift, Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingView.swift, Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingViewWrapper.swift, Stitch/Graph/Node/Port/View/Field/InputView/DropDownChoiceView.swift, Stitch/Graph/Node/Port/View/Field/InputView/FieldValueNumberView.swift, Stitch/Graph/Node/Port/View/Field/InputView/LayerGroupAlignmentChoicesView.swift, Stitch/Graph/Node/Port/View/Field/InputView/LayerGroupOrientationDropDownChoiceView.swift, Stitch/Graph/Node/Port/View/Field/InputView/LayerNamesDropDownChoiceView.swift, Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerView.swift, Stitch/Graph/Node/Port/View/Field/InputView/SpecialPickerFieldValueView.swift, Stitch/Graph/Node/Port/View/Field/InputView/StitchFontDropdown.swift, Stitch/Graph/Node/Port/View/Field/ValueButton/ColorOrbValueButtonView.swift, Stitch/Graph/Node/Port/View/Field/ValueButton/StitchColorPicker/StitchColorPickerView.swift
Fixes regression where incorrect row observer getter logic was used in flyout view.
=> Flyout regression fix + InputValueView perf work

Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
=> Remove log in `NodeInputView`

Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/Node/StitchAINodeUtils.swift, Stitch/Graph/StitchAI/StitchAISystemPrompt.swift
* change timeout to 60 seconds
* add exponential backoff for retries
* removes scroll interaction patch from schema
=> Schema filter and request changes

Stitch.xcodeproj/project.pbxproj, Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Accidental merge used closed source version.
=> Updated StitchEngine dependency

Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverSchemaObserverIdentifiable.swift, Stitch/Graph/Node/View/StitchUIScrollHelpers.swift, Stitch/Graph/Node/View/StitchUIScrollView.swift
Plus more logs for scrolling for debugging a graph jumping issue.
=> Reduced render cycles caused by updating coordinate

Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
Resolves: https://github.com/StitchDesign/Stitch--Old/issues/6879
=> Set all nodes visible when traversal level changes, so that we update UI fields

Stitch/Graph/Node/Model/RowData/LayerInputType.swift
=> make the text layer default size to be auto

Stitch.xcodeproj/project.pbxproj, Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Stitch/Graph/Node/Patch/Type/Media/CameraFeedNode.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/CameraFeed/Util/CameraOrientation.swift
Confirmed works with iPad with @pianostringquartet 
https://github.com/user-attachments/assets/5a23d19f-0992-494e-9616-0fb05768b060
=> Default camera orientation fix

Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6990
=> Heterogenous-values only relevant to layer inspector inputs

Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/CameraFeed/Reference/CameraFeedActor.swift
=> fix camera mirroring on catalyst

Stitch/Graph/Node/Port/Model/Field/NodeRowType.swift, Stitch/Graph/Node/Port/Util/Field/TabKeyPressActions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6991
https://github.com/user-attachments/assets/0c40835d-9574-4e5f-bec3-b5900f3e9691
=> ShapeCommand is a special Tabbing case

Stitch/Graph/Node/Model/Definition/StitchNodeNames.swift, Stitch/Graph/Node/Patch/Type/Media/SoundImportNode.swift, Stitch/Graph/Node/Patch/Type/Media/VideoImportNode.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Sound/SoundHelpers.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Sound/StitchMicrophone.swift
* Changes various output labels to just be "Volume"
* Uses AudioKit's tap functionality for getting volume on the microphone
* Proper "Peak Volume" calculations
https://github.com/user-attachments/assets/431ed9f6-5efe-4e95-b284-08ef22f74f22
=> Volume work

Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift, Stitch/Graph/PrototypePreview/Layer/Model/LayerData.swift, Stitch/Graph/PrototypePreview/Layer/Util/LayerNodesSorting.swift, Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PinningUtils.swift, Stitch/Graph/PrototypePreview/Layer/View/GeneratePreview.swift, Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
Small things here and there like fewer assignments to publishers, removing usage of weak vars, etc.
=> Reduced render cycles from layers

Stitch/Graph/Node/Patch/ViewModel/PatchNodeViewModel.swift, Stitch/Graph/Node/View/NodeTag/NodeTagMenuButtonsView.swift, Stitch/Graph/Node/View/NodeView.swift, Stitch/Graph/Node/View/NodeViewType.swift, Stitch/Graph/Node/View/NodesOnlyView.swift, Stitch/Graph/ViewModel/GraphState.swift, Stitch/Graph/ViewModel/GraphUI.swift
Usage of graph weak var, view builders, and redundant publishing a few of our culprits.
=> Reduced render cycles caused by nodes views

Stitch/Graph/Edge/Util/EdgeEditingActions.swift, Stitch/Graph/Edge/Util/EdgeUtils.swift, Stitch/Graph/Edge/Util/PortActions.swift, Stitch/Graph/Edge/View/ExistingEdgesView.swift, Stitch/Graph/Node/Group/GroupNodeCreationActions.swift, Stitch/Graph/Node/Patch/Type/Value/SplitterTypeActions.swift, Stitch/Graph/Node/Patch/Util/WirelessReceiver.swift, Stitch/Graph/Node/Port/Util/InputEdit/InputCommittedActions.swift, Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepTypeAction.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7009
https://github.com/user-attachments/assets/50cad225-dff1-4aec-8f4b-dcc4d475ba8a
=> Only hide existing edge when we are specifically animating the equivalent possible edge

Stitch/Graph/Node/Port/Util/NodeRowObserverUtil.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverCachedViewDataExtensions.swift, Stitch/Graph/Node/Util/Movement/NodePositionUtils.swift, Stitch/Graph/Node/View/NodesOnlyView.swift, Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift, Stitch/Graph/Util/NodeSelection/NodeSelectionUtil.swift, Stitch/Graph/ViewModel/GraphUI.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7008
=> Connected canvas items should not include patch's or layer's own canvas items

Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift, Stitch/Graph/ViewModel/GraphState.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7012
=> Update Graph ConnectedEdges when input edited but not committed

Stitch/Graph/Edge/View/EdgeDrawingView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7010
=> Use gray color if actively-drawn-edge has no eligible input

Stitch/Graph/Node/Layer/Type/Media/3DModelLayerNode/Nodes/BoxLayerNode.swift, Stitch/Graph/Node/Layer/Type/Media/3DModelLayerNode/Nodes/ConeLayerNode.swift, Stitch/Graph/Node/Layer/Type/Media/3DModelLayerNode/Nodes/CylinderLayerNode.swift, Stitch/Graph/Node/Layer/Type/Media/3DModelLayerNode/Nodes/Model3DLayerNode.swift, Stitch/Graph/Node/Layer/Type/Media/3DModelLayerNode/Nodes/SphereLayerNode.swift, Stitch/Graph/Node/Layer/Type/Media/RealityView/RealityNode.swift, Stitch/Graph/Node/Layer/Type/Shapes/ShapeLayerNode.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7006
=> Do not display shadow input in inspector for 3D layers

Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift, Stitch/Graph/Node/Model/GraphCopyable.swift, Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift, Stitch/Graph/Node/View/StitchUIScrollView.swift, Stitch/Graph/Sidebar/Util/Gesture/LegacySidebarActions.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarSelectedItemsDuplicated.swift, Stitch/Graph/Sidebar/ViewModel/LayersSidebarViewModel.swift, Stitch/Graph/Sidebar/ViewModel/ProjectSidebarObservable.swift, Stitch/Graph/Sidebar/ViewModel/SidebarItemSwipable.swift, Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6815
Note: regular sidebar item duplication and copy-paste also still work. 
https://github.com/user-attachments/assets/136848cc-6d32-42f4-8f53-77c3daa315c9
https://github.com/user-attachments/assets/1a6760a2-b316-44d6-b8bd-c8c5d50a8449
https://github.com/user-attachments/assets/fd2e63e8-6a48-4af3-8441-cb00bdff3f40
=> Hold `Option` key to duplicate sidebar items during drag

Stitch/Graph/Gesture/View/GraphMovementViewModifier.swift, Stitch/Graph/Node/Model/GraphCopyable.swift, Stitch/Graph/Node/View/NodesOnlyView.swift, Stitch/Graph/Node/View/StitchUIScrollHelpers.swift, Stitch/Graph/Node/ViewModel/NodePageData.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7015
=> If infiniteCanvasCache not yet populated, do not modify visibleCanvasIds

Stitch/Graph/Node/Port/Util/InputEdit/InputCommittedActions.swift, Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7018
=> iterate through all input row observers for layer multiselect

Stitch/Graph/LayerInspector/LayerInspectorPortView.swift, Stitch/Graph/Node/Port/Util/InputEdit/InputCommittedActions.swift, Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift, Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift, Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputUnpackedPortObserver.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7022
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7021
=> Fix layer multiselect editing when field on canvas; update field observers when pack mode toggled

Stitch/Graph/Node/Eval/PatchEvaluateExtensions.swift, Stitch/Graph/Node/Model/Definition/PatchNodeDefinitionKinds.swift, Stitch/Graph/Node/Patch/Type/Math/MaxNode.swift, Stitch/Graph/Node/Patch/Type/Math/MinNode.swift, Stitch/Graph/Node/Patch/Type/Math/ModNode.swift, Stitch/Graph/Node/Patch/Util/PatchDefaultNodeExtensions.swift, Stitch/Graph/Node/Patch/Util/PatchNodeTypeExtensions.swift
[MoreMathNodes.stitch.zip](https://github.com/user-attachments/files/19349552/MoreMathNodes.stitch.zip)
[MoreMathNodes.zip](https://github.com/user-attachments/files/19349546/MoreMathNodes.zip)
=> Math nodes more types

Stitch/Graph/Node/Patch/Type/DateAndTimeFormatterNode.swift
=> Fixes time zone error in Date and Time Formatter Node

Stitch/Graph/Node/Patch/Type/DateAndTimeFormatterNode.swift
=> improved drop down labels

Stitch/Graph/Gesture/View/GraphMovementViewModifier.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7030
https://github.com/user-attachments/assets/a0058dcd-2b4f-42b9-be56-6767bfe5f8bf
=> Update row view models' fields when canvas item becomes visible

ci_scripts/ci_pre_xcodebuild.sh
=> Fixed secrets generation for Stitch AI

Stitch/App/Serialization/Model/StitchFileError.swift, Stitch/Graph/Node/Util/NodeCreatedAction.swift
=> revert camera dupe error alert

Stitch/Graph/Gesture/View/GraphMovementViewModifier.swift, Stitch/Graph/Node/Port/Util/InputEdit/InputCommittedActions.swift, Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7020
=> Immediately update field observers of edited or edit-committed input

Stitch/App/Serialization/DocumentLoading/StitchFileManager.swift, Stitch/App/Util/ProjectsUtils.swift, Stitch/App/View/StitchNavStack.swift, Stitch/App/View/StitchRootView.swift, Stitch/Graph/Menu/ProjectSettingsView.swift, Stitch/Graph/PrototypePreview/Frame/View/FullScreenGestureRecognizerView.swift, Stitch/Graph/PrototypePreview/Frame/View/FullScreenPreviewViewWrapper.swift, Stitch/Graph/View/StitchProjectView.swift, Stitch/Graph/ViewModel/StitchDocumentViewModel.swift, Stitch/Home/Util/ProjectDestructiveActions.swift, Stitch/Home/View/ProjectsHomeViewWrapper.swift
Also introduces some changes which may help with view-identity, which may be the cause of occasionally losing home-screen top bar buttons.
Some resources:
1. https://bdewey.com/til/2023/09/04/toolbar-bugs/
2. https://stackoverflow.com/questions/63956668/swiftui-toolbar-disappears-after-following-navigationlink-and-coming-back
https://github.com/user-attachments/assets/515f28f2-cf47-49e9-abc2-3de298907319
=> Proper color and hover effect on Catalyst home-screen top bar buttons

Stitch/Graph/Sidebar/Util/JumpToCanvasItem.swift, Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7038
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7040
=> Smarter type for GroupNodeBreadcrumbs

Stitch/Graph/Sidebar/Util/SidebarIcons.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7042
=> Separate icons for Text vs TextField layers

Stitch/Graph/Node/Layer/Type/Shapes/ShapeLayerNode.swift, Stitch/Graph/Node/Layer/Type/Text/TextFieldLayerNode.swift, Stitch/Graph/Node/Layer/Type/Text/TextLayerNode.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7041
=> Text layer has text input, TextField layer has placeholder input

Stitch/Graph/Node/Port/View/PortValuesPreview/PortPreviewPopoverView.swift, Stitch/Graph/Node/Port/View/PortValuesPreview/PortValuesPreviewView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7045
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7044
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6993
=> Always show field labels; better align loop index label; improve arrow on iPad

Stitch/Graph/Node/Group/GroupNodeDestructionActions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6873
https://github.com/user-attachments/assets/96d396b9-fbca-463c-a672-3e168692ef1e
=> Select children after group node uncreated

Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Stitch/Graph/LayerInspector/LayerInspectorPortView.swift, Stitch/Graph/Sidebar/Util/JumpToCanvasItem.swift
https://github.com/user-attachments/assets/351b287f-7b13-46a7-a17d-ae28affc0728
=> Jump to a canvas item even if it's on another traversal level

Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift, Stitch/Graph/Node/View/CanvasItemPositionHandler.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7024
=> Use UIGestureRecognizer to listen for Option key during canvas item drag

Stitch/Graph/Node/Patch/Type/Value/SplitterPatchNode.swift, TestFlight/WhatToTest.en-US.txt
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7034
Recent media refactoring caused regressions here. Needed media observers for value node along with eval changes.
=> Fixed media processing in value nodes

Stitch/App/Util/Constants.swift, Stitch/Graph/Toolbar/View/TopBarButtonView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7056
Also improves the size of the icons in the ‘…’ menu.
=> Rearrange and improve icons on iPad graph view

Stitch.xcodeproj/project.pbxproj, Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift, Stitch/Graph/Node/Port/Util/NodeRowObserverUtil.swift, Stitch/Graph/Node/Port/Util/PortValue/CoercerUtils.swift, Stitch/Graph/Node/Port/Util/PulseActions.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/InputNodeRowObserver.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift, Stitch/Graph/ViewModel/GraphState.swift, Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7060#issuecomment-2761896680
=> Only eval node if inputs changed

Stitch/App/View/ViewUtil/ViewUtils.swift, Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift
Giving https://github.com/StitchDesign/Stitch/pull/967 a shot for a bit longer before making more changes.
=> Revert Catalyst top bar buttons

Stitch/Graph/Node/Port/Model/Field/FieldValue.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7071
=> Show media name in port preview

Stitch/Graph/LayerInspector/GenericFlyoutView.swift, Stitch/Graph/LayerInspector/LayerInspectorActions.swift, Stitch/Graph/Node/Util/NodeCreatedAction.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupCreated.swift
https://github.com/user-attachments/assets/7c81ae83-c889-4349-bbb9-0887bfb893e5
=> Canvas item insertion is now aware of layer inspector

Stitch/Graph/Node/Port/Util/PortValue/CoercerUtils.swift, Stitch/Graph/Node/Port/Util/TypeChange/NodeTypeChangedHelpers.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/InputNodeRowObserver.swift
Resolves my regression: https://github.com/StitchDesign/Stitch--Old/issues/7079
=> Fix input coercion when node type changes

Stitch/Graph/Node/Patch/Type/Shape/LayerInfoNode.swift, Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/LayerSizeReader.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7081
https://github.com/user-attachments/assets/15e4d315-1d68-44ed-8c18-7feab84afeb5
https://github.com/user-attachments/assets/c414c37e-ea89-4d6b-8329-d14386559116
=> Use read position in LayerInfo instead of just position input

Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7085
We were relying on `self.llmSteps` when adjusting AI-created nodes' positions, but `self.llmSteps` were not being updated with the latest converted-actions. We were also unnecessarily converting the steps again, thus making the function exception-throwing for no reason.
Better solution here is just to use as pure a function as possible: passing in data makes the larger flow explicit, which can sometimes by hidden when we set data on a class in some function and then expect xyz in another one down the road.
=> Fix AI-added nodes' positions

Stitch/Graph/LayerInspector/ColorFlyoutView.swift, Stitch/Graph/LayerInspector/GenericFlyoutView.swift, Stitch/Graph/LayerInspector/LayerInspector3DTransformInputView.swift, Stitch/Graph/LayerInspector/LayerInspectorGridInputView.swift, Stitch/Graph/LayerInspector/LayerInspectorPortView.swift, Stitch/Graph/Node/Port/Util/Field/TabKeyPressActions.swift, Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift, Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerView.swift, Stitch/Graph/Node/Port/View/Field/NodeFieldsView.swift, Stitch/Graph/Node/Port/View/Field/OutputValueView.swift, Stitch/Graph/Node/Port/ViewModel/FieldGroupTypeData.swift, Stitch/Graph/Node/Port/ViewModel/FieldViewModel.swift, Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/InputNodeRowViewModel.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModel.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/OutputNodeRowViewModel.swift
Reverts StitchDesign/Stitch#1010
Need a better commit message than "Compiling"
=> Revert "Non-generic FieldViewModel"

Stitch/Graph/LayerInspector/ColorFlyoutView.swift, Stitch/Graph/LayerInspector/GenericFlyoutView.swift, Stitch/Graph/LayerInspector/LayerInspector3DTransformInputView.swift, Stitch/Graph/LayerInspector/LayerInspectorGridInputView.swift, Stitch/Graph/LayerInspector/LayerInspectorPortView.swift, Stitch/Graph/Node/Port/Util/Field/TabKeyPressActions.swift, Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift, Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerView.swift, Stitch/Graph/Node/Port/View/Field/NodeFieldsView.swift, Stitch/Graph/Node/Port/View/Field/OutputValueView.swift, Stitch/Graph/Node/Port/ViewModel/FieldGroupTypeData.swift, Stitch/Graph/Node/Port/ViewModel/FieldViewModel.swift, Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/InputNodeRowViewModel.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModel.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/OutputNodeRowViewModel.swift, Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModelNodeCalculatable.swift
See PR message : https://github.com/StitchDesign/Stitch/pull/1010
=> Non-generic FieldViewModel

Stitch/Graph/Node/Title/View/NodeTitleTextField.swift, Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift, Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift, Stitch/Graph/ViewModel/GraphState.swift
=> Place 'Go Up Traversal Level' button leftmost in Catalyst project view; only shown debug node Ids when EditLLMActions modal is open

Stitch/Graph/Node/Eval/MediaEvalOpObservable.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverSchemaObserverIdentifiable.swift
Closes https://github.com/StitchDesign/Stitch--Old/issues/7046
Fix by removal here, mostly finding logic to not be necessary.
=> Fixed flashing media on prototype restart

Stitch/App/Logging/LogUtils.swift, Stitch/Graph/Node/View/StitchUIScrollView.swift, Stitch/Graph/Node/ViewModel/NodePageData.swift, Stitch/Graph/Sidebar/Util/JumpToCanvasItem.swift, Stitch/Graph/ViewModel/GraphState.swift, Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7116
=> When creating a new traversal level (group node), use graph's absolute center

Stitch/Graph/Node/Title/View/NodeTitleTextField.swift
https://github.com/user-attachments/assets/50446908-4b49-4e6c-8282-e89093599431
=> Double tap to edit canvas item title

Stitch/Graph/Node/Group/GroupNodeCreationActions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7100
https://github.com/user-attachments/assets/f7da98a4-4670-436f-b397-eebbce732878
=> Take inspector into account when Inserting new group node

Stitch/Graph/Node/Port/View/Field/InputView/AnchorPopoverView.swift, Stitch/Graph/Node/Port/View/Field/OutputValueView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7119
Likely broke due to recent perf work that refactored fields some.
Large diff change but only changes were adding logic for anchoring and layers.
=> Fixed regression where anchoring and layer output fields disappeared

Stitch/Graph/Node/Util/NodeTypeUtils.swift, Stitch/Graph/Node/View/NodeTag/NodeTagMenuButtonsView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7104
=> Display 'Text' instead of 'String' in node type menu

Stitch/Graph/View/ContentView.swift
https://github.com/user-attachments/assets/f70ab7ef-aeaf-40cc-8306-b449c7a8e9d9
=> Remove header from Catalyst project title edit view

Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModel.swift, Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
=> Make GroupNode row view model initialization a little clearer

Stitch/App/StitchApp.swift
https://docs.sentry.io/platforms/apple/configuration/metric-kit/
=> enable metric kit in sentry

Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift
Fixes issue where importing media into a loop builder with existing media removed other used media.
=> Fixed loop builder import removal issue

Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModel.swift
Follow up to https://github.com/StitchDesign/Stitch/pull/1062
=> Fix compiler error after sync vs async GraphState PR revert

Stitch/Graph/Node/Patch/Type/TransitionNode.swift
Enables support for things like `auto`, using similar logic to Origami.
=> Added Transition node support for layer dimension

Stitch/Graph/Node/Eval/PatchEvaluateExtensions.swift, Stitch/Graph/Node/Patch/Type/OptionPickerNode.swift, StitchTests/evalTests.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7141
=> OptionPicker: when first input is not a loop, the output may or may not be a loop

Stitch/Graph/PrototypePreview/Frame/View/PreviewWindowElementUIKitGestures.swift
Follow up to https://github.com/StitchDesign/Stitch/pull/1073
https://github.com/user-attachments/assets/9a40a663-2dc0-4ebb-a25d-9dba8e2d797a
=> Factor out layer's size from position reported to Press interaction

Stitch.xcodeproj/project.pbxproj, Stitch/Graph/PrototypePreview/Layer/Model/LayerData.swift, Stitch/Graph/PrototypePreview/Layer/Model/LayerType.swift, Stitch/Graph/PrototypePreview/Layer/Util/LayerNodesSorting.swift, Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
Just a reorg, no code changes besides changing `typealias` names.
=> Separate file for LayerType

Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepActionToStateChange.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepTypeAction.swift
https://github.com/user-attachments/assets/c38d556f-a37c-4446-ad61-51fc9f317076
=> Position AI-generated nodes by their actual width

Stitch/Graph/PrototypePreview/Frame/View/FloatingWindowView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7142
https://github.com/user-attachments/assets/49945f7a-d501-4fab-855f-e96d593f77c8
=> Hide handle when window not shown

Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemSwipeInnerView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7148
https://github.com/user-attachments/assets/8371249d-8d0d-4fbe-8e04-e60d9f909d91
=> Gray text for hidden sidebar layers even if selected in sidebar

Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PinningUtils.swift, Stitch/Graph/PrototypePreview/Layer/ViewModel/LayerViewModel.swift
=> Move PinToId extension etc. to PinningUtils

Stitch/Graph/Node/Patch/Util/PatchUtils.swift
Just impacts debug builds with a conditional fatal error there.
=> Fixed bug where media type was unknown for speaker node input

Stitch.xcodeproj/project.pbxproj, Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Stitch/Graph/Edge/Util/PortDragActions.swift, Stitch/Graph/GraphStep/GraphStepIncrementer.swift, Stitch/Graph/Node/Component/StitchComponentViewModel.swift, Stitch/Graph/Node/Patch/Type/Loop/LoopBuilder.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift, Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/InputNodeRowObserver.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModel.swift, Stitch/Graph/Node/Title/View/MathExpressionSubmenuButtonView.swift, Stitch/Graph/Sidebar/Util/Gesture/LegacySidebarActions.swift, Stitch/Graph/Sidebar/Util/Gesture/SidebarListItemActions.swift, Stitch/Graph/Util/GraphEvaluationUtil.swift, Stitch/Graph/ViewModel/GraphCalculatable.swift, Stitch/Graph/ViewModel/GraphState.swift
StitchEngine's responsibility is graph eval; Stitch's responsibility is updating the cached-UI-data after a graph evaluation.
=> Make Stitch responsible for responding to UI changes from StitchEngine graph calc

Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/LayerInspector/Model/LayerInspectorSection.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7151
https://github.com/user-attachments/assets/aa0d570f-6c07-43f1-a464-f8147d1a88c9
=> Remember collapsed inspector sections across graph session

Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift, Stitch/Graph/ViewModel/GraphCalculatable.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7150
https://github.com/user-attachments/assets/463987c9-cfa0-4933-a1ba-999b05affb6a
=> Layer multiselect ignores inputs that are wholly or partly blocked

Stitch/Graph/Edge/Util/PortActions.swift, Stitch/Graph/Node/Group/GroupNodeCreationActions.swift, Stitch/Graph/Node/Group/GroupNodeDestructionActions.swift, Stitch/Graph/Node/Port/Util/NodeRowObserverColorUtil.swift, Stitch/Graph/Node/Port/Util/NodeRowObserverUtil.swift, Stitch/Graph/Node/Port/View/PortView.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/InputNodeRowObserver.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverCachedViewDataExtensions.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/OutputNodeRowObserver.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/GraphItemType.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/InputNodeRowViewModel.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModel.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModelId.swift, Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/OutputNodeRowViewModel.swift, Stitch/Graph/Node/Util/NodeDeletedAction.swift, Stitch/Graph/Node/Util/NodeViewModelUtils.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupUncreated.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarListItemSelectionActions.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarSelectedItemsDeleted.swift, Stitch/Graph/StitchAI/DatasetRecording/LLMActionHelpers.swift, Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepTypeAction.swift, Stitch/Graph/Util/NodeSelection/CopyAndPasteNodesActions.swift, Stitch/Graph/ViewModel/GraphReaders.swift, Stitch/Graph/ViewModel/GraphState.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7070
Also passes around values as parameters.
https://github.com/user-attachments/assets/a65bad64-c064-4400-8bee-b1e6ee111c9b
=> Only highlight upstream port if canvas item directly connected

Stitch/Graph/PrototypePreview/Frame/View/FloatingWindowView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7053
https://github.com/user-attachments/assets/489da978-1e9b-41cf-8e7b-d7132269b68f
=> If preview window is landscape, check width not height when determining if gesture would make preview window too small

Stitch/Graph/Edge/Util/PortDragActions.swift, Stitch/Graph/ViewModel/GraphUI.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7126
https://github.com/user-attachments/assets/8995da4e-0539-441d-ad2b-bb9781f63b30
=> Deselect canvas items etc. when output drag starts

Stitch/Graph/Node/Port/ViewModel/FieldViewModel.swift
=> viewCache not needed on FieldViewModel

Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenu.swift
=> White color for InsertNodeMenu's button

Stitch/App/Resources/Assets.xcassets/Colors/SideBarFooter.colorset/Contents.json, Stitch/App/View/StitchRootView.swift, Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingView.swift, Stitch/Graph/Sidebar/View/SidebarFooterView.swift, Stitch/Graph/Sidebar/View/iPadProjectSidebarView.swift
=> Unify sidebar and inspector background colors

Stitch/Graph/Node/Patch/Util/PatchUtils.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaConstants.swift, Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift, Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerValueEntry.swift, Stitch/Graph/Node/Util/NodeKindUtils.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7154
https://github.com/user-attachments/assets/af398dd7-e968-484b-8511-7e4dbf6cf237
=> MediaType depends on both patch and portId

Stitch/Graph/Node/Eval/MediaEvalOpObservable.swift, Stitch/Graph/Node/Patch/Type/CoreMLClassifyNode.swift, Stitch/Graph/Node/Patch/Type/CoreMLDetectionNode.swift, Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModelNodeCalculatable.swift
Most media wasn't updating inputs, likely some recent regression. More work to do for looping support.
=> Fixed most regressions for media input updating

Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModelNodeCalculatable.swift, StitchTests/evalTests.swift
Plus adds unit tests to hopefully catch issues in the future.
=> Fixed media loop handling for all patches

Stitch/Graph/Node/Patch/Util/PatchUtils.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7174
=> Fixed grayscale preview regression

Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonMisc.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7170
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7165
Note: Rotations for pinning are ALWAYS ignored by layout.
Rotations in SwiftUI undesirably change the non-.local size of a layer, thus messing up a layer's `readSize`.
See https://harshil.net/blog/swiftui-rotationeffect-is-kinda-funky
To avoid this, we can have the rotation "ignored by layout". However, rotations ignored by layout move the layer but not e.g. its hit areas. 
Since z-rotations are commonly used with circular-style interactions, we respect (i.e. do NOT ignore) layout for z-rotations.
QA'd on Monthly Stays, Humane, Obscured Squares, Haptic Feedback etc.
=> Layout ignores x and y rotations

Stitch/Graph/Node/Layer/ViewModel/LayerInputFieldBlocking.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7177
We now show again (i.e. no longer improperly block) the alignment, spacing, grid-column etc. inputs on LayerGroups.
https://github.com/user-attachments/assets/6589f3fb-9601-46ce-9a6d-55b7fca6f1dc
=> Some inputs are blocked by layer's own orientation, not its parent's

Stitch.xcodeproj/project.pbxproj, Stitch/Graph/Node/View/CanvasItemInputChangeHandleView.swift, Stitch/Graph/Node/View/NodeView.swift
https://github.com/user-attachments/assets/77a59486-1297-4ef0-ba3e-3374415fa16e
=> Drag bottom of patch node to add or remove inputs

Stitch/Graph/Node/Patch/Type/Animation/RepeatingAnimationNode.swift, Stitch/Graph/Node/Port/Model/PortValue/Type/Animation/ClassicAnimation/Eval/ClassicAnimationNumber.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7183
=> When classic animation duration = 0, jump immediately to the goal

Stitch/Graph/LayerInspector/ColorFlyoutView.swift, Stitch/Graph/LayerInspector/GenericFlyoutView.swift, Stitch/Graph/LayerInspector/LayerInspector3DTransformInputView.swift, Stitch/Graph/LayerInspector/LayerInspectorGridInputView.swift, Stitch/Graph/LayerInspector/LayerInspectorPortView.swift, Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/Node/Model/RowData/LayerInputType.swift, Stitch/Graph/Node/Port/ViewModel/FieldViewModel.swift, Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift, Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputUnpackedPortObserver.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7182
https://github.com/user-attachments/assets/b35f15a5-c40c-4929-b89c-f44df8c6387e
=> Retrieve the appropriate row view model and row observer in the inspector, do not assume packed

Stitch/Graph/LayerInspector/LayerInspectorPortView.swift, Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift, Stitch/Graph/Node/View/NodeView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7186
https://github.com/user-attachments/assets/66b16187-6ef4-431b-8dc0-418eab89bfb0
=> "Are all fields blocked?" logic that works regardless of pack vs unpack

Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift, Stitch/Graph/Node/Port/View/Field/InputView/DropDownChoiceView.swift, Stitch/Graph/Node/Port/View/Field/InputView/StitchFontDropdown.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7161
https://github.com/user-attachments/assets/aa4d7be5-ec47-4d8b-9f88-2bd288873f86
=> Provide 2x normal input width for dropdowns

Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenu.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7190
=> White progress loader for Submit Prompt in node menu

Stitch.xcodeproj/project.pbxproj, Stitch/Graph/Node/View/CanvasItemInputChangeHandleView.swift, Stitch/Graph/Node/View/CanvasItemPositionHandler.swift, Stitch/Graph/Node/View/NodeTag/CanvasItemMenuButtonsView.swift, Stitch/Graph/Node/View/NodeView.swift
https://github.com/user-attachments/assets/215228af-02da-4843-93cc-2ee522b32d48
=> Less wide input-change-handle; add back add/remove input buttons in canvas item menu

Stitch/Graph/LayerInspector/GenericFlyoutView.swift, Stitch/Graph/LayerInspector/OpenFlyoutView.swift, Stitch/Graph/Node/Util/NodeCreatedAction.swift, Stitch/Graph/Sidebar/Util/JumpToCanvasItem.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7189
https://github.com/user-attachments/assets/2f7bde55-ee26-4f52-afd8-d6798076de31
=> Better flyout padding; better canvas jump location

Stitch/App/Shortcut/ProjectsHomeCommands.swift, Stitch/App/Shortcut/StitchCommands.swift, Stitch/Graph/Node/Group/GroupNodeCreationActions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7194
=> Require 2 or more selected canvas items before creating group node

Stitch/Graph/Node/Patch/Util/PatchUIExtensions.swift, Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift, Stitch/Graph/Node/View/NodeViewType.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7202
=> Hide outputs' fields on Pack patches

Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7203
https://github.com/user-attachments/assets/e5a61506-78e1-4414-90d2-cca87997a362
=> Only wipe current sidebar selections if at least one layer duplicated/pasted

Stitch/Graph/Node/Patch/Util/PatchUIExtensions.swift, Stitch/Graph/Node/View/NodeViewType.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7204
=> Hide inputs' fields on unpack patches

Stitch/Graph/Node/Port/View/Field/InputView/CanvasCommonEditingView.swift, Stitch/Graph/Node/Port/View/Field/InputView/TapToEditTextView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7209
TODO: perf of checks on each canvas field re: "Am I the redux-focused field?"
=> Fix tabbing with extended canvas fields

Stitch/Graph/Node/Port/View/Field/InputFieldValueView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7210
=> .trailing alig read-only views in inspector

Stitch/App/Util/TypeExtension/CollectionExtensionUtils.swift, Stitch/Graph/GraphStep/GraphStepIncrementer.swift, Stitch/Graph/Node/Group/GroupNodeCreationActions.swift, Stitch/Graph/Node/Patch/Util/WirelessReceiver.swift, Stitch/Graph/Node/Patch/ViewModel/PatchNodeViewModel.swift, Stitch/Graph/Node/Port/Util/TypeChange/NodeTypeChangedActions.swift, Stitch/Graph/Node/View/NodeTag/CanvasItemMenuButtonsView.swift, Stitch/Graph/PrototypePreview/Layer/Util/LayerDraggedActions.swift, Stitch/Graph/PrototypePreview/Layer/Util/LayerHoveredActions.swift, Stitch/Graph/ViewModel/GraphState.swift
https://github.com/user-attachments/assets/ff74f689-a2be-498f-86e3-b293993a3e1f
=> Change multiple selected patch nodes' types at once

Stitch/App/Util/Constants.swift, Stitch/Graph/Node/Group/GroupNodeCreationActions.swift, Stitch/Graph/Node/Patch/Type/Value/SplitterTypeActions.swift, Stitch/Graph/Node/View/NodeTag/CanvasItemMenuButtonsView.swift, Stitch/Graph/ViewModel/GraphState.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7214
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7213
Resolves https://github.com/StitchDesign/Stitch--Old/issues/2869
https://github.com/user-attachments/assets/558697a4-41b1-4a93-8cef-67a65c1fc0a7
https://github.com/user-attachments/assets/9e44583d-9ea3-4b14-8186-e520c4c8d9c8
=> Change multiple splitter types at once; better splitter staggering; remove outgoing edges when splitter made output type

Stitch/Graph/Node/Group/GroupNodeCreationActions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7215
https://github.com/user-attachments/assets/0f409692-9a22-4e5d-8aef-70d60c9c7b9e
https://github.com/user-attachments/assets/f1ebd28a-ef50-467f-9de0-634056b74522
=> Group Node creation: improve positioning of input and output splitters when e.g. many edges are going to same node

README.md
We'll need smaller GIF files so the webpage isn't so slow to load / choppy.
=> Fewer prototypes in gallery

Stitch/App/Serialization/Util/File/StitchComponentUtil.swift, Stitch/App/Serialization/Util/File/StitchDocumentUtil.swift, Stitch/App/Util/TypeExtension/MiscUtils.swift, Stitch/Graph/Node/Group/GroupNodeCreationActions.swift, Stitch/Graph/Node/Model/GraphCopyable.swift, Stitch/Graph/Node/Model/NodeEntity.swift, Stitch/Graph/Node/Model/StitchClipboardContent.swift, Stitch/Graph/Node/Model/StitchComponentable.swift, Stitch/Graph/Node/Patch/Type/Value/SplitterTypeActions.swift, Stitch/Graph/Node/Title/Util/NodeTitleActions.swift, Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift, Stitch/Graph/Node/Util/NodeDeletedAction.swift, Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModel.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarSelectedItemsDuplicated.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepTypeAction.swift, Stitch/Graph/Util/DocumentEncoder.swift, Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift, Stitch/Graph/ViewModel/GraphState.swift, Stitch/Graph/ViewModel/VisibleNodesViewModel.swift, StitchTests/nodeUIGroupingTests.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7171
=> Fix paste position of nodes inside a group; consolidate and clean up copy-paste / duplication logic

Stitch/Graph/Edge/Util/PortActions.swift, Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarSelectedItemsDuplicated.swift, Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift, Stitch/Graph/ViewModel/GraphState.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7217
https://github.com/user-attachments/assets/166814f7-292b-4d31-b29f-0365488245c0
=> Remove non-wireless, non-group-splitter cross-traversal edges when pasting nodes

.gitignore, Stitch.xcodeproj/project.pbxproj, Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Stitch/App/StitchApp.swift, Stitch/GoogleService-Info.plist
Barebones analytics config
Covers:
- 	app_open
- 	screen views
- 	session start / user engagement
=> Firebase Analytics

Stitch/Graph/PrototypePreview/Frame/View/FloatingWindowView.swift, Stitch/Graph/PrototypePreview/Frame/ViewModel/PreviewWindowSizing.swift, Stitch/Graph/View/Util/ProjectWindowSizeReader.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7051
https://github.com/user-attachments/assets/a52151ee-75dc-4064-8ddc-ff2f4c9b446a
=> Resize preview window when Mac Catalyst window resizes

Stitch/Graph/Sidebar/ViewModel/SidebarItemGestureViewModel.swift, Stitch/Graph/ViewModel/GraphState.swift
Reverts StitchDesign/Stitch#1199
=> Revert "Update `layerDropdownChoiceCache` in `GraphState.updateGraphData` where we update other caches"

Stitch/Graph/Edge/Util/PortActions.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepActionToStateChange.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7223
=> `updateGraphData` after every application of an LLM action

Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift
=> Do not automatically enter LLM augmentation mode when OpenAI request completes

Stitch/Home/View/ProjectItem/ProjectsListItemView.swift, Stitch/Home/View/SampleProjectsView.swift
=> Some love for Sample Projects modal

Stitch/App/Serialization/SampleProjects.swift, Stitch/Home/View/SampleProjectsView.swift
Fixes:
1. Crash caused by opening project without internet connection.
2. Multiple documents loading if multiple are selected (an issue for the Earth demo which doesn't load a loading indicator for some reason).
=> Fixed various sample projects issues

Stitch/App/View/AppSettingsView.swift, Stitch/App/ViewModel/StitchStore.swift, Stitch/Graph/StitchAI/DatasetRecording/LLMActionRecording.swift, Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift, Stitch/Graph/StitchAI/GraphPrompting/UI/EditBeforeSubmitModalView.swift, Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift, Stitch/Graph/View/ProjectToolbar.swift
=> Derive new actions when augmentation started; always show LLM record/augment button

Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift, Stitch/Graph/Toolbar/View/TopBarButtonView.swift, Stitch/Graph/Toolbar/View/TopBarSharingButtonsView.swift, Stitch/Home/View/ProjectsHomeViewWrapper.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7243
Changes
* New home screen option with tint change to fix menu button coloring issue on Catalyst
* New option for sharing an attached document
=> Improved "Contact Us" UX

Stitch/Graph/Menu/InsertNodeMenu/Model/StitchAITips.swift, Stitch/Graph/StitchAI/DatasetRecording/LLMActionRecording.swift, Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift, Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift, Stitch/Graph/Toolbar/View/TopBarButtonView.swift, Stitch/Graph/Util/GraphActions.swift, Stitch/Graph/View/ProjectToolbar.swift, Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
Trigger `StitchAITrainingTip`'s display using `Tip.Rule` macro. Not quite sure how rules vs `.invalidate(reason:)` are supposed to work (or not work?) together. `@Parameter static var` is basically global, namespace'd state.
=> Proper location StitchAITrainingTip; fix iPad compilation

Stitch/App/FeatureFlags.swift, Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuSearchBar.swift, Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift, Stitch/Graph/Toolbar/View/TopBarButtonView.swift
Temporarily hiding until some fixes are in.
=> Hide LLM recording feature

Stitch/App/FeatureFlags.swift, Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuSearchBar.swift, Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift, Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift, Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift, Stitch/Graph/Toolbar/View/TopBarButtonView.swift
Most issues caused by recent Node ID remapping.
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7250
=> Fixed LLM recording issues

Stitch/Graph/LayerInspector/LayerPortAddedToCanvas.swift, Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift, Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift
https://github.com/user-attachments/assets/3207fee6-eb83-40d9-a65d-bfbce5ae4bd1
=> Dragging edge into the inspector: can swap out fields for whole input

Stitch/App/View/ViewUtil/StitchHostingController.swift, Stitch/Graph/Node/Layer/Type/GroupLayerNode.swift, Stitch/Graph/Node/Util/NodeDeletedAction.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupCreated.swift, Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupUncreated.swift, Stitch/Graph/Sidebar/ViewModel/ProjectSidebarObservable.swift, Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/Step.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepType.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepTypeAction.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StitchStructuredOutputs.swift, Stitch/Graph/StitchAI/GraphPrompting/UI/EditBeforeSubmitModalView.swift, Stitch/Graph/ViewModel/GraphState.swift, Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
=> Adding Sidebar Group Actions to AI Example Creation + Structured Outputs Schema

Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/Node/Patch/Type/Data/NetworkRequestNode.swift, Stitch/Graph/Node/Port/Util/TypeChange/NodeTypeChangedActions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7272
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7274
=> Network Request patch improvements: default outputs now respect overall node type + type changes

Stitch/App/Documentation/StitchDocsPopoverView.swift, Stitch/Graph/LayerInspector/LayerInspectorView.swift, Stitch/Graph/Node/View/NodesView.swift, Stitch/Graph/Sidebar/View/iPadProjectSidebarView.swift
Better doc hyperlink, sizing etc.
=> Fixed iPad polish with new empty state UI

Stitch.xcodeproj/project.pbxproj, Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Stitch/Graph/Node/Patch/Util/PatchNodeTypeExtensions.swift, Stitch/Graph/Node/Port/Util/Field/FieldViewModelTypeUtils.swift, Stitch/Graph/Node/Port/Util/PortValue/CoercerUtilHelpers/NumberCoercers.swift, Stitch/Graph/Node/Port/Util/PortValue/CoercerUtils.swift, Stitch/Graph/Node/Port/Util/PortValue/JSONCoercionUtils.swift, Stitch/Graph/Node/Port/Util/PortValue/Parsers.swift, Stitch/Graph/Node/Port/Util/PortValue/PortValueDefaults.swift, Stitch/Graph/Node/Port/Util/PortValue/PortValueDisplay.swift, Stitch/Graph/Node/Port/Util/PortValue/PortValueUtils.swift, Stitch/Graph/Node/Util/NodeTypeUtils.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/LLMValueParsingUtils.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StitchAITypeCasting.swift
Removing type and portvalue support for a non-supported feature in the app.
=> Removed Int type

Stitch/App/StitchApp.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/StitchAITrainingData.swift
For new reasoning grader + RTF fine tuning training sets
=> Validation Updates

Stitch/App/FeatureFlags.swift, Stitch/Graph/StitchAI/GraphPrompting/DataModel/Step.swift
=> Fix decoding of `Step` for a `StepActionLayerGroupCreated`

Stitch.xcodeproj/project.pbxproj, Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Stitch/Graph/LayerInspector/FlyoutUtils.swift, Stitch/Graph/LayerInspector/Model/LayerInspectorSection.swift, Stitch/Graph/Node/Layer/Type/Text/TextFieldLayerNode.swift, Stitch/Graph/Node/Layer/Util/LayerEvalExtensions.swift, Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift, Stitch/Graph/Node/Model/RowData/LayerInputType.swift, Stitch/Graph/Node/Port/Model/Field/FocusHelpers.swift, Stitch/Graph/PrototypePreview/Layer/View/Type/TextField/PreviewTextFieldLayer.swift, Stitch/Graph/PrototypePreview/Layer/View/Type/TextField/PreviewTextFieldLayerUtils.swift, Stitch/Graph/PrototypePreview/Layer/ViewModel/LayerViewModel.swift
https://github.com/user-attachments/assets/ebf86954-74ea-4616-a7a2-f7147abc339f
=> Introduce more TextField layer inputs

Guides/README.md, Stitch/App/Documentation/StitchDocsRouter.swift, Stitch/App/View/AppSettingsView.swift, Stitch/App/View/Component/ToastView.swift, Stitch/App/View/StitchRootView.swift, Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenu.swift, Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuSearchBar.swift, Stitch/Graph/StitchAI/GraphPrompting/Model/StitchAIRatingToast.swift, Stitch/Graph/View/GraphBaseView.swift
New alert describes value prop to user and clear instructions for how to opt out.
https://github.com/user-attachments/assets/89d7a697-39db-47be-a067-d633faf1a268
=> Introduced telemetry alert for first AI request

Stitch/App/View/StitchRootView.swift, Stitch/Graph/LayerInspector/OpenFlyoutView.swift, Stitch/Graph/Menu/InsertNodeMenu/Model/InsertNodeMenuState.swift, Stitch/Graph/Menu/InsertNodeMenu/Util/InsertNodeMenuActions.swift, Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenu.swift, Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuSearchBar.swift, Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuWithModalBackground.swift, Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift, Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequestHelpers.swift, Stitch/Graph/StitchAI/GraphPrompting/API/StitchAIManager.swift, Stitch/Graph/StitchAI/GraphPrompting/Model/StitchAIRequestable.swift, Stitch/Graph/View/ProjectToolbar.swift, Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
This PR fixes an issue where any graph interaction during an AI request would cancel the request.
=> Support for graph interactions during AI loading

Stitch.xcodeproj/project.pbxproj, Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved, Stitch/App/View/Component/StitchSheetInput.swift, Stitch/Graph/Menu/ProjectSettingsView.swift, Stitch/Graph/PrototypePreview/Frame/Util/PreviewWindowDeviceUtils.swift
Changes:
1. App settings are now exposed in project settings
2. Newer iPhones now supported as selectable options
3. Polish fixes on width/height inputs
=> Project settings improvements

Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenu.swift, Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuSearchBar.swift
Adds some background with opacity, still ugly but better than no background when text overflows.
=> Minor cancel button polish

Stitch.xcodeproj/project.pbxproj, Stitch/Graph/Toolbar/View/CatalystNavbarToolTipView.swift, Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift, Stitch/Graph/Toolbar/View/TopBarSharingButtonsView.swift, Stitch/Home/View/ProjectsHomeViewWrapper.swift
https://github.com/user-attachments/assets/f265bb60-0f33-49f0-87fc-3f4c1f926955
=> Catalyst Tool Tips
