StitchDesign/Stitch

- Stitch/Home/View/ProjectItem/ShareView.swift
Projects without media were failing on the `try ... getImportedFilesURL` line.
We now allow copying of ImportedFiles directory to fail when duplicating a project, since that directory is absent if media has never been added to the project.
> Copy thumbnail of duplicated project, even if project has no imported media

- Stitch/Graph/Node/View/NodesOnlyView.swift
Fixes regression introduced by https://github.com/StitchDesign/Stitch/pull/20/files
> Allow graph background tap even when no items on canvas

- Stitch.xcodeproj/project.pbxproj
- Stitch/Graph/LayerInspector/LayerInspectorActions.swift
- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/LayerInspector/LayerInspectorState.swift
- Stitch/Graph/LayerInspector/LayerInspectorView.swift
- Stitch/Graph/Node/Layer/Type/GroupLayerNode.swift
- Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonModifierWithoutFrame.swift
- Stitch/Graph/PrototypePreview/Layer/View/GeneratePreview.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewShapeLayer.swift
- Stitch/Graph/Sidebar/Util/Gesture/SidebarListItemActions.swift
- Stitch/Graph/ViewModel/GraphUI.swift
Demo of padding. Spacing (px vs evenly vs between) can be shown properly when schema's PortValue is updated.
https://github.com/StitchDesign/Stitch/assets/18562836/7bd36218-b039-45d6-8d23-50b4ca73df54
> LayerGroup padding and spacing; deselect property when its row added to canvas

- Stitch/Graph/Node/Port/Model/PortValue/Type/Shapes/ShapeUtils.swift
Slightly more idiomatic way to handle the view-branching.
> Use ViewBuilder when applying stroke

- Stitch/Graph/Node/Port/View/Field/NodeFieldsView.swift
- Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
- Stitch/Graph/Node/Port/ViewModel/FieldGroupTypeViewModel.swift
Some of this UI will be revised when packed vs unpacked multifields work is in, but it's a decent start.
> Vertically stack fields in LayerInspector

- Stitch/Graph/Node/Layer/Type/TextLayerNode.swift
- Stitch/Graph/Node/Model/RowData/LayerInputType.swift
Ensuring that both the Text Input and Text Layer nodes have appropriately sized default text values
> Updating default text sizes

- Stitch/App/ViewModel/StitchUndoManager.swift
- Stitch/App/ViewModel/StoreDelegate.swift
- Stitch/Graph/Menu/NumberAdjustmentBar/AdjustmentBarPopoverView.swift
- Stitch/Home/Util/ProjectDestructiveActions.swift
Resolves #6304
Two different crashes:
1. Using `StitchStore` as an `Environment` object in the adjustment bar view seems to create issues despite correct assignment of `StitchStore` as an environment object. Seems like a SwiftUI bug.
2. A separate issue where casting callbacks which assume `MainActor` thread safety.
> Fixed crashes caused by adjustment bar

- Stitch/Graph/Edge/View/EditMode/EdgeEditModeViewModifier.swift
- Stitch/Graph/LayerInspector/PaddingFlyoutView.swift
- Stitch/Graph/Menu/NumberAdjustmentBar/AdjustmentBarPopoverView.swift
- Stitch/Graph/Menu/NumberAdjustmentBar/WideAdjustmentBarView.swift
- Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
- Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift
- Stitch/Graph/Node/Port/Model/Field/FieldCoordinate.swift
- Stitch/Graph/Node/Port/Util/Field/TabKeyPressActions.swift
- Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift
- Stitch/Graph/Node/Port/View/Field/InputView/EditJSONEntry.swift
- Stitch/Graph/Node/Port/View/Field/InputView/FieldValueNumberView.swift
- Stitch/Graph/Node/Port/View/Field/ValueButton/NumberValueButtonView.swift
- Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
- Stitch/Graph/Node/Port/ViewModel/FieldGroupTypeViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverCachedViewDataExtensions.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowViewModel.swift
- Stitch/Graph/Node/View/NodesView.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel.swift
- Stitch/Graph/ViewModel/GraphState.swift
Issues where a mismatch between the row view model ID and the row observer's. I removed the inconsistency by directly retrieving the row observer's ID directly from the row view model's delegate, and repurposing the view model's ID to be a non-optional port index.
> Fixed output port hover; row view model ID refactor

- Stitch/Graph/Sidebar/View/SidebarItem/SidebarListItemView.swift
Fixes a regression by hiding layer-inspector-specific logic behind a feature flag. 
https://github.com/user-attachments/assets/69380788-57c1-447d-ae3e-a542ba926699
> Tap sidebar layer to jump to its node on the graph

- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
- Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeDelegate.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel.swift
Main issue here is graph delegate not getting assigned in time.
Other changes include simplifications around row view model updates to involve the backend observer less if there's just a visibility change.
> Fixed broken interactions when nodes aren't visible

- Stitch/Graph/Node/Layer/Type/ShapeLayerNode.swift
Hide the inputs that represent features not available when the layer inspector FeatureFlag is turned off.
> Hide aspect ratio and min/max size inputs if layer inspector disabled

- Stitch/Graph/Node/Patch/Type/Value/SplitterTypeActions.swift
Fixes issue when splitter changes don't update in group node unless persistence action happens.
> Fixes out-of-date group port UI

- StitchTests/jsonTests.swift
We now properly use "width" and "height" keys and allow string values like 'auto'; the test was simply out of date.
> Fix LayerSize JSON decoding unit test

- Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
- Stitch/Graph/Node/Port/Model/Field/FieldCoordinate.swift
- Stitch/Graph/Node/Port/Util/Field/TabKeyPressActions.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel.swift
- Stitch/Graph/ViewModel/GraphState.swift
Issue was `NodeRowViewModelId` needed a more specific identifier. There were multiple equal IDs with the prior system which screwed up view builders.
> Fix for multiple input edges in layer inspector node

- Stitch/Graph/Node/ViewModel/NodeViewModel.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupCreated.swift
Search for keyPath, not portId, when updating newly-created LayerGroup's size input
> Do not crash when creating LayerGroup

- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonSizeModifier.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewLayerSizeModifier.swift
For a preview window that is 800x800.
So 50% width = 400 pts etc.
But we can constraint that via min and max width etc.
> Better handling of min and max with parent percentage with LayerGroups

- Stitch/Graph/Node/Port/View/Field/InputView/AnchorPopoverView.swift
Apply .scaleEffect *after* .popover
> Anchor popover arrow now appears next to icon, not at far away from it

- Stitch/Graph/Edge/Model/EdgeEditingState.swift
- Stitch/Graph/Edge/Util/EdgeEditingActions.swift
- Stitch/Graph/Node/View/NodesView.swift
https://github.com/user-attachments/assets/9e9ffd82-b8b0-42fb-a84a-57771451c398
> Show edge-edit-mode input labels according to CanvasItemId, not NodeId

- Stitch/Graph/Node/Port/Util/TypeChange/NodeTypeChangedActions.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
Fixes an issue where group node view models wouldn't update unless the user open+closes project.
> Fixed splitter type changes for group node ports

- Stitch/Graph/Edge/Util/PortDragActions.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowViewModel.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
Focuses on nodes which can have inputs/outputs added or removed, i.e. groups and various patch nodes. Various missing sync issues created crashes or faulty edge UI logic.
> Fixed various port sync issues

- Stitch/App/Serialization/DocumentLoading/StitchFileManager.swift
- Stitch/App/Serialization/Util/File/StitchDocumentURLUtils.swift
- Stitch/App/Serialization/Util/File/StitchDocumentUtil.swift
- Stitch/Home/Util/ProjectDestructiveActions.swift
- TestFlight/WhatToTest.en-US.txt
The issue was caused by attempting to unzip a project from the recently deleted temp folder. Projects here aren't zipped.
Other changes:
* Tweaked logic to look at file extensions to determine if a file needs to be unzipped
* Matched the file extension in recently deleted files
> Fixed project deletion undo

- Stitch/Graph/Node/Patch/Type/Media/SpeakerNode.swift
- Stitch/Graph/Node/Port/Util/PulseActions.swift
Helpers expected output row observer when none was created for the speaker node, which doesn't contain any outputs.
> Fixed crash caused by speaker node

- Stitch.xcodeproj/project.pbxproj
- Stitch/Graph/Node/ViewModel/NodeViewModel.swift
- stitch.xcworkspace/xcshareddata/swiftpm/Package.resolved
Fixes issue where a downstream counter node would pulse on too many occasions when connected from a press interaction "down" output.
Changes are mostly in StitchEngine but have been isolated to only impact the press interaction node. Nodes can leverage this in the future with updates in the `requiresOutputValuesChange` computed getter.
> Fixed counter issue with press interaction node

- Stitch/Graph/Node/Layer/Type/3DModelLayerNode/PreviewModel3DLayer.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/AR/StitchEntity.swift
- TestFlight/WhatToTest.en-US.txt
Model entities in a 3D model layer use a different tech stack than the reality node, and therefore need to be updated differently. The fix required converting StitchEntity into an Observable, allowing it to publish changes to the view representable. When these updates happen we can trigger matrix transform updates in the update view method.
> Fixed transform updates for 3D Model layer node

- Stitch/App/Resources/Assets.xcassets/Colors/LayerInspectorRowCapsuleColor.colorset/Contents.json
- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/LayerInspector/LayerInspectorView.swift
- Stitch/Graph/Node/Port/View/Field/OutputValueView.swift
- Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
- Stitch/Graph/Util/Font/FontConstants.swift
- stitch.xcworkspace/xcshareddata/swiftpm/Package.resolved
Brings inspector row UI closer to Figma spec and uses a "sticky header" for the specific layer we're inspecting.
Note:
- no blue tinting yet
- some aspects of dark mode are still being refined
https://github.com/user-attachments/assets/0ea5ce00-f619-47b4-8b98-85b8c004d14c
https://github.com/user-attachments/assets/4b569567-75fb-4425-adfd-1ee8cddb8cb1
> Bring inspector row closer to Figma spec; inspected layer now has sticky header

- Stitch/Graph/LayerInspector/FlyoutUtils.swift
- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/LayerInspector/PaddingFlyoutView.swift
- Stitch/Graph/LayerInspector/ShadowFlyoutView.swift
- Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
Need more love here but solves several UI issues. 
Fixes:
- issue where rapidly opening or closing a flyout could cause improper placement of the flyout
- updates flyouts' UI to be closer to Figma spec (white capsule etc.)
- remove double-listing of "Shadow" title in the Shadow flyout
> Improve inspector flyouts (Figma spec)

- Stitch/Graph/LayerInspector/LayerInspectorState.swift
- Stitch/Graph/Node/Port/Util/Field/TabKeyPressActions.swift
- Stitch/Graph/ViewModel/GraphUI.swift
The fix was converting `PropertySidebarState` to an Observable class.
The issue is caused by too many data struct mutations of `PropertySidebarState` by the `LayerPropertyRowOriginReader` action, which is dispatched on all scroll events. Despite just one property being mutated, `PropertySidebarState` is a struct and will trigger a render cycle for any views which subscribe to its state.
> Improved scroll perf on inspector sidebar

- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel.swift
Impacts here are at least a 25% improvement for the Humane demo.
We used inefficient getters which unnecessarily looped through all layer node ports before finding relevant view models. New logic reduces complexity to constant time.
> Fixed perf issues caused by row view model getters

- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
Adding an HStack or even just a ZStack was causing the list row's .background color to expand too far. Removing the HStack for now until we finalize the unpack/pack UI for the layer inspector row.
> Property sidebar: fix row background color

- Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift
- Stitch/Graph/Node/Port/View/Field/InputView/LayerNamesDropDownChoiceView.swift
- Stitch/Graph/Node/Port/View/Field/OutputValueView.swift
- Stitch/Graph/Sidebar/Util/SidebarListItemGroupActions.swift
Part of a possible strategy for e.g. "not allowing a group to be pinned to one of its descendants"; we can explore how this feels; would need to be handled at input coercer level as well; plus various perf considerations.
> Pinning: do not list a layer group's descendants in the layer group's pinTo dropdown

- Stitch/Graph/Node/Layer/Type/SwitchLayerNode.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommon.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewImage.swift
Use preview coordinate space reader with PreviewImage and ToggleSwitch
> Pinning now works with Image and ToggleSwitch layers

- Stitch/Graph/Node/Port/Util/Field/TabKeyPressActions.swift
Note: there are still intermittent issues where we will instead focus the project title text-field instead.
> Only tab through fields on canvas item, not inspector

- Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift
- Stitch/Graph/PrototypePreview/Layer/Util/LayerNodesSorting.swift
Also, a note about sorting + pinning.
> Properly update sizing scenario fields

- Stitch/Graph/Node/Model/RowData/LayerInputType.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonModifierWithoutFrame.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonPositionModifier.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift
Two parts:
1. we now update preview when pinTo changes; fixes bugs where pinTo changes would not take effect until project was reopened (due to not triggering a preview-cache update)
2. do not use .position modifier with GhostView rendering of a layer; fixes bugs where using a .position modifier causes the parent stack (HStack, VStack or ZStack) to expand (underlying SwiftUI issue remains but we now avoid it more gracefully)
> Change preview layers when pinTo changes; avoid some pinning scenarios where a LayerGroup unexpectedly expanded

- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonModifierWithoutFrame.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewSidebarHighlightModifier.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewShapeLayer.swift
> Do not highlight the GhostView rendering of a pinned layer

- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonSizeModifier.swift
Demo projects:
[Group with hug.stitch.zip](https://github.com/user-attachments/files/16682983/Group.with.hug.stitch.zip)
[Group with fill.stitch.zip](https://github.com/user-attachments/files/16682984/Group.with.fill.stitch.zip)
Group has its own anchoring of top left, but is same size as parent so that anchoring does nothing
> Group's Fill size uses 100% of parent

- Stitch/Graph/Node/Port/Util/Field/TabKeyPressActions.swift
Regression from recent change that added special logic for only tabbing through the fields of a layer input on the canvas.
We now only pass layerInputOnCanvas if field is for a canvas item.
> Allow tabbing between rows in layer inspector

- Stitch/Graph/Node/Port/Model/PortValue/Type/Shapes/ShapeUtils.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonModifierWithoutFrame.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift
> ApplyStroke modifier ignores a pinned layer's GhostView

- Stitch/Graph/LayerInspector/LayerInspectorView.swift
Note: inspector background on iPad seems too dark?
> Reduce section spacing; never use caps in section headers

- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/AR/SIMDExtensions.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/AR/StitchEntity.swift
https://github.com/user-attachments/assets/f0302819-6798-4968-a2dd-8a351f95b077
https://github.com/user-attachments/assets/939abf05-b353-4fe0-b5fb-83ccb23e9836
Notes:
So, in our current implementation on `main`, the entity held by the StitchEntity class was the loaded model entity, which might have a non-identity transform (https://en.wikipedia.org/wiki/Identity_matrix). So, subsequently, setting a transform on the StitchEntity could overwrite the model’s root transform, which might have a rotation to convert from Z-up to Y-up convention, or, a scale to convert from a format that uses centimeters instead of meters.
By injecting a container entity between the (optional) anchor and the model entity, any transform applied by the user is isolated from affecting the model’s root transform, and …
> Using container entities to wrap 3D Models

- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonPositionModifier.swift
- Stitch/Graph/PrototypePreview/Layer/ViewModel/LayerViewModel.swift
Example: VStack, unclipped, where each child was hardcoded to use modifier to have offset of w=50, h=100
Todo:
> Introduce .offset modifier when a child's position has been disabled due to being in an HStack, VStack or Grid

- Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/LayerPaddingModifier.swift
Had swapped bottom vs trailing padding.
> Properly apply StitchPadding with SwiftUI .padding modifier

- Stitch/Graph/Node/Layer/Type/GroupLayerNode.swift
- Stitch/Graph/Node/Layer/Type/HitAreaLayerNode.swift
- Stitch/Graph/Node/Layer/Type/ProgressIndicatorLayerNode.swift
- Stitch/Graph/Node/Layer/Type/RadialGradientNode.swift
- Stitch/Graph/Node/Layer/Type/RealityView/RealityNode.swift
- Stitch/Graph/Node/Layer/Type/SFSymbolLayerNode.swift
- Stitch/Graph/Node/Layer/Type/SwitchLayerNode.swift
- Stitch/Graph/Node/Layer/Type/TextFieldLayerNode.swift
- Stitch/Graph/Node/Layer/Type/TextLayerNode.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Shapes/ShapeUtils.swift
- Stitch/Graph/Node/Port/View/Field/InputView/LayerNamesDropDownChoiceView.swift
- Stitch/Graph/Node/Port/View/Field/Media/VideoDisplayView.swift
- Stitch/Graph/PrototypePreview/Frame/View/PreviewContent.swift
- Stitch/Graph/PrototypePreview/Layer/Model/LayerData.swift
- Stitch/Graph/PrototypePreview/Layer/Util/LayerNodesSorting.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/LayerSizeReader.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PinningUtils.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommon.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonMisc.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonModifierWithoutFrame.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonPositionModifier.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonSizeModifier.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewWindowCoordinateSpaceReader.swift
- Stitch/Graph/PrototypePreview/Layer/View/GeneratePreview.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewImage.swift
- Stitch/Graph/PrototypePreview/Layer/ViewModel/LayerViewModel.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/GraphUI.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
Big changes:
1. Pinning data is now saved in a nested data structure so we can better determine a linked list of pins. This allows us to better determine all the views to render at a specific hierarchy so that nesting is supported.
2. Revamped ghosting logic to better support orientation groups. We now render a duplicate prototype view that is totally invisible. Doing this allows us to more easily handle offset changes necessary to render a pinned view in the correct location.
3. To better support orientation groups, pinned views are rendered outside the `VStack`, `HStack` etc. This assumes shrinkage in an orientation group and can be modified in the future given priority.
> Pinning support for nested pins and orientation groups

- Stitch/Graph/Node/Patch/Type/Interaction/DragInteractionPatchNode.swift
- TestFlight/WhatToTest.en-US.txt
This fixes an issue where the Drag Interaction patch would reset its position output value after each drag. This misses parity with Origami which updates position locally in the patch node, without reacting to actual position values from the layer.
> Fixed drag interaction output reset on each drag

- Stitch/Graph/Node/Util/NodeDeletedAction.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewSidebarHighlightModifier.swift
Fixes two crashes:
1. Reads of `highlightedSidebarLayers` can cause a crash, tracked in #264 
2. Connections to deleted layer nodes would cause the same unsafe memory access crash when editing an input
> Fixed crashes caused by disconnected layer nodes

- Stitch/Graph/Node/Layer/Type/3DModelLayerNode/PreviewModel3DLayer.swift
Looks like I missed this case in original PR a while back.
> Use Color.clear instead of 3D Model View when generating project thumbnail

- Stitch/Graph/Node/Util/NodeDeletedAction.swift
Issue was caused by pack mode changes not getting triggered due to over-reliance on the view handling this logic.
> Fixed issue where layer input values incorrectly changed on delete

- Stitch/Graph/Node/Eval/MediaEvalOpObservable.swift
- Stitch/Graph/Node/Layer/Type/RealityView/PreviewRealityLayer.swift
- TestFlight/WhatToTest.en-US.txt
Cause by pinning implementation which created a duplicate RealityView, causing AR to no longer work.
> Fixed broken Reality layer node

- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift
Note: we currently do _not_ dismiss the row-selection-status when user scrolls etc.; only when user toggles inspector panel or selects another row
> Only allow inspector-row-selection on iOS

- Stitch/Graph/LayerInspector/LayerInspectorView.swift
> Only show inspector section chevron on hover

- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/Sidebar/View/iPadProjectSidebarView.swift
Fixing small regression from sidebar UI improvements.
> Disable row-selection on inspector in Catalyst

- Stitch/App/Shortcut/ProjectsHomeCommands.swift
- Stitch/Graph/LayerInspector/FlyoutUtils.swift
- Stitch/Graph/LayerInspector/LayerInspectorActions.swift
- Stitch/Graph/LayerInspector/LayerInspectorView.swift
- Stitch/Graph/LayerInspector/LayerMultiselect.swift
- Stitch/Graph/Node/Util/NodeDeletedAction.swift
- Stitch/Graph/Node/View/NodeTag/TagMenuHelperViews.swift
- Stitch/Graph/Sidebar/Model/Gesture/SidebarSelectionState.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupUncreated.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarSelectedItemsDeleted.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarSelectedItemsDuplicated.swift
- Stitch/Graph/Sidebar/Util/SidebarListItemGroupActions.swift
- Stitch/Graph/Sidebar/View/SidebarFooterView.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SidebarListItemChevronView.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SidebarListItemSelectionCircleView.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SidebarListItemView.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SidebarListLabelView.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemSwipeInnerView.swift
- Stitch/Graph/Sidebar/View/SidebarListView.swift
- Stitch/Graph/Sidebar/View/iPadProjectSidebarView.swift
- Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
- Stitch/Graph/ViewModel/GraphDelegate.swift
- Stitch/Graph/ViewModel/GraphUI.swift
- StitchTests/nodeUIGroupingTests.swift
https://github.com/user-attachments/assets/d132110c-2b80-4a2c-84a5-3fa26280eb74
https://github.com/user-attachments/assets/ed2bc071-76ea-46d3-a3e4-5bbbaf548f73
https://github.com/user-attachments/assets/dfa06af1-f54a-43ba-8337-92690197cb85
https://github.com/user-attachments/assets/726a55e9-ab05-4554-8bad-e8d4d1c8e6c4
> Focused vs 'actively selected' layers in sidebar

- Stitch/Graph/Sidebar/Model/Gesture/SidebarSelectionState.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemGestureRecognizerView.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemSwipeView.swift
- Stitch/Graph/Sidebar/View/SidebarListView.swift
Note: Catalyst-only. ContextMenu's iOS LongPress gesture would clash with iPad's "long press + drag to move layer around in the sidebar."
Implementation details: we had to switch to UIKit's context menu to use delegate methods that tell us when context menu is opening.
> Select a right-clicked layer (if not already selected) when opening context menu

- Stitch.xcodeproj/project.pbxproj
- Stitch/Graph/Sidebar/Model/Gesture/SidebarSelectionState.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarListItemSelectionHelpers.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SidebarListItemView.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SidebarListLabelView.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemGestureRecognizerView.swift
- Stitch/Graph/Sidebar/View/iPadProjectSidebarView.swift
Note: some remaining work:
- selection logic needs finalization; is not quite as simple as "range between just-selected and last-selected" nor "range between just-selected and closest-already-selected"
- shift needs to be made more reliable; our common key listening logic does not work well with shift (responder chain gets interrupted?); an observer on GameController is not recreated when project re-opened and a listener on UITapGesture seems fickle with right-click to open context menu
- https://github.com/StitchDesign/Stitch--Old/issues/6451
> Select multiple sidebar layers via Shift

- Stitch/App/StitchApp.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemGestureRecognizerView.swift
Using a GameController observer EnvironmentObject seems more accurate for listening to the Shift key than UIHostingController key commands (we need to improve our responder chain issues?) and a GestureRecognizer's `shouldReceive: UIEvent` (does not work well with right-click).
Note: when GameController observer lived in the individual sidebar list item's view, the observer would not be re-initialized when we re-opened a project.
> Use GameController EnvironmentObject to listen for Shift key

- Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarListItemSelectionHelpers.swift
i.e. shift-click does not change the "starting point" for selecting a range of layers. 
https://github.com/user-attachments/assets/2b379b82-5427-406c-af95-3951bc54aa45
> Improved shift select logic

- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/LayerSizeReader.swift
Prevents crashes like we saw when creating a layer group with a single child whose `scale = 0`
https://github.com/user-attachments/assets/22c7584e-7320-4550-961c-80e34b13a7da
> Handle NaN in LayerSizeReader

- Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupCreated.swift
`auto` handles loops etc. more easily.
Notes: 
- any reason to not use .auto x .auto for a nearly created group? ... perhaps for .background, which can become too big in a group whose children use .position modifiers?
- how important is the LayerGroupFit.adjustment/offset etc. ?
https://github.com/user-attachments/assets/248a778a-aa3a-432d-b189-7565c18f7763
> Use `auto x auto` size for newly created layer groups

- Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift
- Stitch/Graph/ViewModel/GraphDelegate.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
> When parent's group-orientation is updated, block or unblock position and offset fields on children

- Stitch/Graph/LayerInspector/GenericFlyoutView.swift
- Stitch/Graph/LayerInspector/LayerInspectorView.swift
- Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift
- Stitch/Graph/Node/Port/Util/Field/TabKeyPressActions.swift
- Stitch/Graph/Node/Port/Util/InputEdit/InputCommittedActions.swift
- Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift
- Stitch/Graph/Node/Port/View/Field/NodeFieldsView.swift
- Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
- Stitch/Graph/Node/Port/ViewModel/FieldViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/ViewModel/NodeDelegate.swift
- Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
Previously we stored `isBlockedOut: Bool` on `FieldViewModel`, but this was inaccurate because:
1. only a layer input/field can be blocked, and 
2. whether a field is blocked or not is independent of packed vs unpacked, inspector vs canvas etc.
`LayerInputObserver` is now responsible for which fields are blocked (`blockedFields`).
This accurate data modeling makes impossible a bug where a field view model would be properly set as blocked but then lose that information when created down the road: https://github.com/StitchDesign/Stitch--Old/issues/6449
> Layer nodes now start with proper fields blocked or unblocked

- Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarListItemSelectionHelpers.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemGestureRecognizerView.swift
- properly handle some cases where the contiguous range may have shrunk or expanded
- if just-clicked item == last-clicked-item, then deselect everything in the contiguous range but the clicked item
- prefer listening to Command Key via UIKit tap gesture; more accurate
https://github.com/user-attachments/assets/f77b17f9-d285-48dc-a726-59b9db9ec687
> Improve shrinking or expanding of shift-select range in layer sidebar

- Stitch/Graph/Sidebar/Model/Gesture/SidebarSelectionState.swift
- Stitch/Graph/Sidebar/Util/Gesture/LegacySidebarActions.swift
- Stitch/Graph/Sidebar/Util/Gesture/SidebarListUIActions.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift
- Stitch/Graph/Sidebar/Util/SidebarListItemGroupActions.swift
- Stitch/Graph/Sidebar/Util/SidebarListItemToggleHelpers.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemGestureRecognizerView.swift
Note: this will look better once we insert duplicated layer items at their proper place again, instead of just adding them to the top of the list.
https://github.com/user-attachments/assets/92a4eae6-d62c-4071-9765-a8645d4d83df
https://github.com/user-attachments/assets/9f2951d3-89f5-45cd-9a55-0dcc5196fe9b
> Option+Drag for sidebar layers

- Stitch/Graph/Sidebar/Util/ListModification/SidebarListItemSelectionHelpers.swift
We now properly flatten the nested ordered-sidebar-layers list.
https://github.com/user-attachments/assets/bd1c5bf3-501e-4939-a195-85b877851a75
> Shift-select nested sidebar layers

- Stitch/App/Shortcut/ProjectsHomeCommands.swift
- Stitch/App/Shortcut/ShortcutsUtils.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupCreated.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupUncreated.swift
- Stitch/Graph/Sidebar/Util/SidebarVisibilityUtils.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemSwipeInnerView.swift
Note: both shortcuts disabled when no layers actively selected and each shortcut respectively disabled when its specific conditions are not met (e.g. to ungroup, we must have a group selected).
Also fixes two other bugs:
1. do not reset edit-mode selections unless in edit mode when group created
2. retrieve proper children when group uncreated
https://github.com/user-attachments/assets/d43e9fd0-52b0-4c98-b994-d894e1c2f1d2
> Group (CMD+G) and Ungroup (CMD+Delete) shortcuts

- Stitch.xcodeproj/project.pbxproj
- Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
v1.0.3 has fixes issue for the `get` method on nested lists used by some sidebar layer helpers.
> Update to StitchViewKit v1.0.3

- Stitch/App/Model/LoadingStatus.swift
- Stitch/App/Serialization/DocumentLoading/DocumentLoader.swift
- Stitch/App/Serialization/DocumentLoading/ProjectLoader.swift
- Stitch/App/Serialization/FileDropHandling.swift
- Stitch/App/Serialization/Util/File/StitchCustomURL.swift
- Stitch/App/Shortcut/ProjectsHomeCommands.swift
- Stitch/App/View/StitchRootModifier.swift
- Stitch/Graph/Util/ProjectThumbnailActions.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
- Stitch/Home/Util/ProjectCreatedActions.swift
- Stitch/Home/View/ProjectItem/ProjectsListItemLoadedView.swift
- Stitch/Home/View/ProjectItem/ProjectsListItemView.swift
- Stitch/Home/View/ProjectsHomeView.swift
- Stitch/Home/View/ProjectsHomeViewWrapper.swift
Changes:
* Thumbnails don't re-load if no changes were processed, and thus don't re-sort project thumbnails on quick open/close
* Improved concurrency to ensure thumbnails are reloaded
> Improved project thumbnail loading

- Stitch/Graph/Node/Port/View/Field/InputView/LayerNamesDropDownChoiceView.swift
I validated that we get persistence events on dropdown selections with this change.
> Fixed issue where layer dropdown persists on render

- Stitch/Graph/Edge/ViewModel/EdgeDrawingObserver.swift
- Stitch/Graph/Node/Port/View/PortView.swift
Caused by updating publishers on a `reset` function. We just needed equality checks to reduce render cycles there.
Reduces ~63% of render cycles in the Humane demo.
> Improved perf for node dragging on large graphs

- Stitch/Graph/Node/Layer/Type/3DModelLayerNode/PreviewModel3DLayer.swift
- Stitch/Graph/View/GraphBaseView.swift
Added `@MainActor` to a couple spots that were preventing compilation on the dev debug and debug build schemes.
> Fix `development` branch @MainActor compiler errors

- Stitch/App/Serialization/DocumentEncodableUtil.swift
- Stitch/App/Serialization/DocumentLoading/StitchFileManager.swift
- Stitch/App/Serialization/Model/StitchDocumentEncodable.swift
- Stitch/App/Serialization/StitchFileManagerProject.swift
- Stitch/Graph/Node/Component/StitchMasterComponent.swift
- Stitch/Graph/Node/Model/GraphCopyable.swift
- Stitch/Graph/Node/Model/NodeEntity.swift
- Stitch/Graph/Node/Model/StitchClipboardContent.swift
- Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModelType.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarSelectedItemsDuplicated.swift
- Stitch/Graph/Util/GraphActions.swift
- Stitch/Graph/Util/NodeSelection/CopyAndPasteNodesActions.swift
- Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/SchemaObserver.swift
- StitchTests/nodeUIGroupingTests.swift
Various copy + paste actions hadn't been properly supported with recent changes to support components. Copy + paste shortcuts now work properly along with shift + click duplication.
> Fixed copy/paste regressions + components support

- Stitch/Graph/CommentBox/Util/CommentBoxGestureActions.swift
- Stitch/Graph/Gesture/Util/GestureUtils.swift
- Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift
- Stitch/Graph/Node/Util/Movement/NodePositionUtils.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemGestureRecognizerView.swift
- Stitch/Graph/View/Gesture/GraphGestureView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6461#issuecomment-2397495071
Generally we should either pass down the `command is pressed` Bool from the UIKit gesture recognizer or improve our key listening logic on Catalyst.
> Listen for CMD via UIGestureRecognizerDelegate for CMD+panning zoom

- Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift
Defocus ReduxFocusedField when project title TextField is defocused.
Noticed with bug where edge-edit mode shortcut was being ignored.
> Properly defocus project title in state

- Stitch/Graph/View/Gesture/GraphGestureView.swift
I've noticed a couple times now that graph double tap seems to stop working, and it seems to be that only the UIKit single tap gesture is being recognized. 
Since we're not actually using the `tapInView` method, I've commented out the assignment for now.
> Do not assign tap gesture in GraphGestureDelegate

- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemSwipeInnerView.swift
> Use gray for hidden or secondarily-selected layers in sidebar

- Stitch/Graph/Node/Patch/Type/Animation/SmoothValueNode.swift
> Use 0.4 as Smooth Value node's Hysteresis input's default value

- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewLayerSizeModifier.swift
If we have static width and height and do not use parent-percent for width or height, use SwiftUI's .frame API that allows for specific `alignment:`.
> Fix Text layer `alignment` and `vertical alignment` when using a static size

- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewLayerSizeModifier.swift
Add `alignment:` to more `.frame` uses in `LayerSizeModifier`
> Better handling of text alignment when one dimension is non-static

- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonSizeModifier.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewLayerSizeModifier.swift
Red text uses Fill x Fill, and has the whole preview window as its parent.
Green text uses Fill x Fill, with Group as parent.
Purple text uses Auto x Auto, with Group as parent.
> SwiftUI views with inherent sizes (like Text) use `Fill` as 100% of parent length

- Stitch/App/Serialization/DocumentLoading/DocumentEncodable.swift
- Stitch/App/System/StitchSystemViewModel.swift
- Stitch/App/ViewModel/StitchStore.swift
- Stitch/App/ViewModel/StitchUndoManager.swift
- Stitch/App/ViewModel/StoreDelegate.swift
- Stitch/Graph/Node/Component/StitchMasterComponent.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
- Stitch/Home/Util/ProjectCreatedActions.swift
This moves project encoding logic once invoked just for the top-level document to be abstract, working for other encoders and any file type.
> Improved undo for components

- Stitch/Graph/LayerInspector/LayerInspectorView.swift
- Stitch/Graph/Node/Layer/Type/AngularGradientNode.swift
- Stitch/Graph/Node/Layer/Type/ColorFillLayerNode.swift
- Stitch/Graph/Node/Layer/Type/LinearGradientNode.swift
- Stitch/Graph/Node/Layer/Type/ProgressIndicatorLayerNode.swift
- Stitch/Graph/Node/Layer/Type/RadialGradientNode.swift
- Stitch/Graph/Node/Layer/Type/SwitchLayerNode.swift
- Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift
> Do not show aspect ratio, sizing scenario etc. for layers that do not support sizes (gradients, toggle, etc.)

- Stitch/App/Util/Action/HandleStitchAction.swift
- Stitch/App/View/ViewUtil/StitchHostingController.swift
- Stitch/App/ViewModel/StitchStore.swift
- Stitch/Graph/Edge/Util/EdgeEditingActions.swift
- Stitch/Graph/ViewModel/GraphUI.swift
Use `@MainActor` for EdgeEditMode
An attempt to address `exclusive_access` crashes when adding or removing edges via edge-edit-mode.
> Avoid access crashes when using edge-edit-mode

- Stitch/Graph/Node/Patch/Type/Delay/DelayNode.swift
Delay node output: use default false value of input's kind when graph opened or reset
https://github.com/user-attachments/assets/9e545e3c-64d2-413b-891d-8fc776ec2b18
https://github.com/user-attachments/assets/2001ea50-5c95-43be-ab22-f15a6f81fe14
> Use proper output value type on Delay node on project open and reset

- Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverSchemaObserverIdentifiable.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowViewModel.swift
- Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift
Also: the below means we're taking perf hits for updating "off-screen" inspector inputs
> Inspector rows with off-screen connected canvas items now start with correct value

- Stitch/App/FeatureFlags.swift
- Stitch/App/Serialization/DocumentLoading/DocumentEncodable.swift
- Stitch/App/ViewModel/StitchUndoManager.swift
- Stitch/Graph/Node/Component/StitchMasterComponent.swift
- Stitch/Graph/Util/GraphActions.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
- Stitch/Home/Util/ProjectCreatedActions.swift
- Stitch/Home/View/ProjectItem/ProjectsListItemView.swift
Component encodings don't directly encode the document, therefore the project thumbnails weren't re-ordering. The fix is to call document encoding even on component encoding.
> Fixed project thumbnail ordering on component edits

- Stitch/Graph/Node/Eval/AsyncSingletonMediaEval.swift
- Stitch/Graph/Node/Eval/EphemeralObserver/NodeEphemeralObservable.swift
- Stitch/Graph/Node/Eval/MediaEvalOpObservable.swift
- Stitch/Graph/Node/Patch/Type/Delay/DelayNode.swift
- Stitch/Graph/Node/Patch/Type/DelayOneNode.swift
- Stitch/Graph/Node/Patch/Type/Interaction/DragInteractionPatchNode.swift
- Stitch/Graph/Node/Patch/Type/Interaction/PressInteractionPatchNode.swift
- Stitch/Graph/Node/Patch/Type/Interaction/Scroll/ScrollData.swift
- Stitch/Graph/Node/Patch/Type/Loop/LoopInsert.swift
- Stitch/Graph/Node/Patch/Type/Media/ARAnchorNode.swift
- Stitch/Graph/Node/Patch/Type/Media/SoundImportNode.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel.swift
The issue was caused from re-initializing ephemeral observers. This didn't play nicely with media which we want to keep around. The fix was creating a new protocol function that requires functionality to be defined on prototype restart for each ephemeral observer type.
For the most part we just re-initialize values, except for media observers now.
> Fixed media issues on prototype restart

- Stitch/Graph/Node/View/NodesView.swift
Regression was caused by recent perf fix which reduced render counts of edge views. The fix was including candidate inputs so that we can still achieve most of that perf fix.
> Fixed edge animation

- Stitch/Graph/Gesture/Util/GraphUICursorSelectionActions.swift
- Stitch/Graph/Model/KeyPressState.swift
- Stitch/Graph/Util/NodeSelection/NodeSelectionUtil.swift
- Stitch/Graph/View/Gesture/GraphBackgroundGestureView.swift
- Stitch/Graph/ViewModel/GraphUI.swift
Shift+NodeCursorBox does not reset selection state of canvas items that were selected previous to the gesture.
https://github.com/user-attachments/assets/a51460f1-b100-465d-9b51-48023f5efcac
> Shift + canvas item cursor selection box now allows multiple additions of canvas items

- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewSidebarHighlightModifier.swift
Continuing to avoid sidebar layer hover on release builds until we get to root of bad access crash.
> Do not use sidebar layer hover on release build scheme

- Stitch/Graph/LayerInspector/LayerInspectorState.swift
- Stitch/Graph/Node/Layer/Type/GroupLayerNode.swift
- Stitch/Graph/Node/Layer/Type/ShapeLayerNode.swift
- Stitch/Graph/PrototypePreview/Layer/View/GeneratePreview.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift
Note: 
- `.layerPadding` is what is actually used now.
- we'll need a proper migration before we can completely remove the `.padding` input (i.e. `LayerInputPort.padding` case)
> Remove Layer Group `.padding` input in app, but keep in schema for now

- Stitch/Graph/View/Gesture/GraphGestureView.swift
We now actually listen to key presses at a higher level, in `ContentView` itself
> Do not listen for key presses in GraphGesture delegate

- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemSwipeInnerView.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemSwipeView.swift
- Stitch/Graph/Sidebar/ViewModel/SidebarItemGestureViewModel.swift
Design decision to prefer right-click on Catalyst platform over native List-style swipe actions.
Resolves an issue where some UIKit gestures are unresponsive post-Sequoia.
> Disable sidebar item swipe menu on Catalyst; improve sidebar item's hover hit area

- Stitch/Graph/Node/Patch/Type/Interaction/PressInteractionPatchNode.swift
- Stitch/Graph/Node/ViewModel/InteractionLayer.swift
- Stitch/Graph/PrototypePreview/Frame/View/PreviewWindowElementUIKitGestures.swift
TODO: this fix also allows Allow simultaneous Single and Double Taps on the Press Interaction node, which may not be quite what we want in a variety of use cases.
https://github.com/user-attachments/assets/65b0ee92-94a7-4991-9f8b-2a4b3d71971d
https://github.com/user-attachments/assets/80b35ee6-0ad5-4ebb-8147-648ee9efe4a8
> Proper speed for single tap 

- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/Node/Layer/Type/3DModelLayerNode/PreviewModel3DLayer.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Layer/LayerDimensionUtils.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Layer/LayerSizeUtils.swift
> Use `fill` with 3D Model layer; improve 'jump to layer input on canvas' hit area in Catalyst

- Stitch/Graph/Node/Port/Model/PortValue/Type/Layer/LayerDimensionUtils.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Layer/LayerSizeUtils.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonModifierWithoutFrame.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewShapeLayer.swift
> Prefer non-scaled size to determine anchoring position

- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonSizeModifier.swift
We now provide min height and min width on layer groups with hug to avoid NaN in LayerSizeReader.
Note there are still issues around the proper reading of the size of the now-empty layer group using hug, including when a project is first opened.
https://github.com/user-attachments/assets/985525fd-b1a6-452c-b62b-56b8669087ca
> Improve LayerInfo size-reading accuracy when moving a child out of a layer group makes that layer group empty

- Stitch/Graph/Node/Layer/Type/GroupLayerNode.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Layer/LayerDimensionUtils.swift
- Stitch/Graph/PrototypePreview/Layer/View/GeneratePreview.swift
interactions on empty GroupLayers still work: 
https://github.com/user-attachments/assets/f21da2a3-5c50-470b-b051-7c8dfe92a35f
> Do not use hit-area clear rect on empty layer groups that use hug or auto

- Stitch.xcodeproj/project.pbxproj
- Stitch/Graph/LayerInspector/ColorFlyoutView.swift
- Stitch/Graph/LayerInspector/GenericFlyoutView.swift
- Stitch/Graph/LayerInspector/LayerInspectorState.swift
- Stitch/Graph/LayerInspector/OpenFlyoutView.swift
- Stitch/Graph/LayerInspector/ShadowFlyoutView.swift
- Stitch/Graph/Menu/ProjectSettingsView.swift
- Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift
- Stitch/Graph/Node/Port/View/Field/ValueButton/ColorOrbValueButtonView.swift
- Stitch/Graph/Node/Port/View/Field/ValueButton/StitchColorPicker/StitchColorPickerView.swift
- Stitch/Graph/Node/Port/View/Field/ValueButton/StitchColorPicker/StitchCustomColorPickerView.swift
Resolves issue where our color picker's SwiftUI .popover in the SwiftUI Inspector would be cut off, despite `.frame`, `.fixedSize` etc.
We now use a flyout for color picker on iPad instead.
> Use flyout for color picker on iPad to avoid popover cutoff

- Stitch/App/Serialization/Util/File/StitchDocumentUtil.swift
- Stitch/Graph/Node/Port/ViewModel/FieldGroupTypeViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowViewModel.swift
Fix required being more selective on when our array of field observers gets refreshed—if nothing really changed then we don't create new objects. This creation caused source media to disappear.
The hope here is later helpers will call recalc and properly update fields anyways, esp if they changed.
> Fixed issue where media may disappear on undo

- Stitch/Graph/Node/Port/View/Field/ValueButton/StitchColorPicker/StitchColorPickerView.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonSizeModifier.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewLayerSizeModifier.swift
We use e.g. `.frame(maxWidth: .parentPercent(100))` and `.frame(width: nil)` when a child's width = fill, so that parent's padding can squeeze the child smaller. 
Also: LayerInfo patch accurately detects the shrinkage:
> Parent padding shrinks available space for child to fill

- Stitch/Graph/ViewModel/GraphState.swift
The main fix here is calling `update()` in `updateGraphData()`.
> Fixed regression where port colors wouldn't update

- Stitch/App/ViewModel/StitchUndoManager.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
Caused by a recent change adding Task objects upon undo history incrementing. This breaks undo/redo.
> Fixed undo regression

- Stitch/Graph/LayerInspector/LayerInspectorView.swift
Unfortunately we need to remove a bottom padding attempt here, as using a clear rectangle almost works but creates a visible line on iPad.
> Fixed bottom padding regression for layer inspector

- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
Careless change on my end when attempting to fix ports. This change is much more scoped and won't introduce weird side effects.
> Fixed node moving regression issue

- Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift
- Stitch/Graph/Util/GraphUIActions.swift
We now 'animate' sidebar, inspector toggling.
https://github.com/user-attachments/assets/d73fffa6-4c16-41c0-af59-8e607e5b565c
> Improve preview window position changes when sidebar and inspector opened

- Stitch/Graph/ViewModel/GraphState.swift
Was causing intermittent crashes when e.g. opening a project with media layers. Returning the empty GraphStepManager seems fine.
Why does this race condition arise?
> Do not use `fatalError` if DocumentDelegate not yet assigned in GraphStepManager

- Stitch/Graph/LayerInspector/OpenFlyoutView.swift
- Stitch/Graph/Util/GraphUIActions.swift
- Stitch/Graph/View/GraphBaseView.swift
- Stitch/Graph/ViewModel/GraphUI.swift
i.e. the top bar moves the graph down some, so we need to my flyout a little bit up.
> Adjust flyout for graph's own y position

- Stitch/Graph/Sidebar/Util/Gesture/LegacySidebarActions.swift
The same operation takes place later in the function.
> Removed redundant sidebar drag translation change

- Stitch/Graph/LayerInspector/LayerMultiselect.swift
`sidebarSelectionState.all` is a computed property that gets updated when secondarily selected items update. Here we only need primary selections.
> Improved sidebar drag perf

- Stitch/Graph/LayerInspector/FlyoutUtils.swift
- Stitch/Graph/LayerInspector/GenericFlyoutView.swift
- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/LayerInspector/LayerMultiselect.swift
- Stitch/Graph/Node/Port/View/Field/NodeFieldsView.swift
- Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
Gives more space in the inspector.
> Use 2x2 grid for layer padding and margin inputs in inspector

- Stitch/App/Shortcut/ProjectsHomeCommands.swift
- Stitch/Graph/Node/Util/NodeDeletedAction.swift
- Stitch/Graph/Util/NodeSelection/NodeSelectionUtil.swift
Look at `GraphUI.isSidebarFocused` instead of just whether we have primary selections. 
Regressed because `hasActiveSelections` changed from data that distinguished between 'sidebar focused or not.' 
Quick fix.
> Regression Fixed: `Delete` shortcut on layer-input-on-graph no longer deletes layer too

- Stitch/Graph/Node/Title/View/CanvasItemTitleView.swift
- Stitch/Graph/Node/Util/NodeViewModelUtils.swift
- Stitch/Graph/Node/View/NodeTag/NodeTagMenuButtonsView.swift
- Stitch/Graph/Node/View/NodeTag/NodeWirelessBroadcastSubmenuView.swift
Note: we no longer show "choose broadcaster" in the node tag menu. 
Easier UX and avoids several issues with SwiftUI native Picker selection state (can't be set by passed in value).
https://github.com/user-attachments/assets/832395c3-f5f7-470a-8189-e6360a6fe956
> Open 'wireless broadcaster choice' menu by clicking node title

- Stitch/Graph/Node/View/NodesView.swift
Filter out wireless receiver inputs from 'connected inputs for edges'
Hat tip Elliot for the debugging help here. 
Issue was us drawing an edge "from 0,0 to 0,0" for the wireless broadcaster -> wireless receiver. 
All wireless edges should instead be hidden.
> Completely hide wireless edges

- Stitch/Graph/Node/Layer/Type/Media/RealityView/PreviewRealityLayer.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/AR/RealityView.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/CameraFeed/Util/CameraUtil.swift
This PR supports a camera-less version of the reality layer node, allowing users to add 3D objects to a blank background.
> Reality node support for Mac

- Stitch/Graph/Node/Patch/Type/Shape/LayerInfoNode.swift
- Stitch/Graph/Node/Port/Util/PortValue/Coercers.swift
- Stitch/Graph/PrototypePreview/Layer/ViewModel/LayerViewModel.swift
Specifically: we now evaluate LayerInfo and ConvertPosition patch nodes when layer view model's `readFrame` updated
https://github.com/user-attachments/assets/5d7538dd-3707-44a6-922c-1ddd2f7b9f08
> LayerInfo starts with proper outputs upon graph open

- Stitch/Home/View/ProjectItem/ProjectsListItemView.swift
> Use lighter background in project thumbnail for projects with dark preview window backgrounds

- Stitch/App/View/StitchRootView.swift
- Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift
- Stitch/Graph/View/ProjectToolbar.swift
- Stitch/Graph/ViewModel/GraphUI.swift
Several bugs (double character entry, state render cycles ignored, etc.) with TextField in NavigationStack's Toolbar on Catalyst with the "Optimize for Mac" build. 
Using a modal as a workaround.
https://github.com/user-attachments/assets/b1f22b2c-32b5-451a-ac36-36fe98978d5c
https://github.com/user-attachments/assets/9ac02339-dc3b-422b-a8c1-7b2e378e3d21
> Catalyst: Edit project title via modal

- Stitch/Graph/Node/Port/Model/Field/FieldValue.swift
- Stitch/Graph/Node/Port/Model/Field/LayerDimensionField.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Layer/StitchSpacingUtils.swift
- Stitch/Graph/Node/Port/Util/PortValue/PortValueDisplay.swift
- Stitch/Graph/Node/Port/ViewModel/NumberFormatterObserver.swift
Using a `NumberFormatter` at the view had costly perf given how frequently some fields update.
> Disabled number formatter for perf

- Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
- Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift
- Stitch/Graph/Node/Port/Util/NodeRowObserverUtil.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverSchemaObserverIdentifiable.swift
- Stitch/Graph/ViewModel/GraphState.swift
Perf improvement attributed to not leveraging an already existing cached property in `connectedCanvasItems`.
> Fixes for port colors perf + compiler issue

- Stitch/Graph/Node/Model/GraphCopyable.swift
- Stitch/Graph/Sidebar/Util/LayerGrouping/SidebarLayerData.swift
- Stitch/Graph/ViewModel/GraphDelegate.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
`GraphDelegate.orderedSidebarLayers` used to have to be a complicated getter for getting nested sidebar data. Because the sidebar now uses nested view model data we don't need to use the old logic for many locations.
> Improved perf by replacing encoded sidebar getter

- Stitch/Graph/Node/View/NodeTag/NodeTagMenuButtonsView.swift
Previously said "Group" now says "Component".
> Fixed node tag button label for visiting component

- Stitch/App/ViewModel/StitchUndoManager.swift
- Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuWrapper.swift
- Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift
- Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingViewWrapper.swift
- Stitch/Graph/Node/Port/View/Field/InputView/FieldValueNumberView.swift
- Stitch/Graph/Node/Port/View/Field/ValueButton/NumberValueButtonView.swift
- Stitch/Graph/Node/View/NodeViewType.swift
- Stitch/Graph/Node/View/NodesOnlyView.swift
- Stitch/Graph/ViewModel/GraphUI.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6628
A recent PR removed the adjustment bar ID hack, which at the time was doing nothing but used to fix a bug where undo changes should close adjustment bar popovers. This was to resolve an issue where the popover becomes out of sync with the field.
The fix here reverts a recent commit and adds logic to undo to close the adjustment bar.
> Fixed adjustment bar undo regression

- Stitch/Graph/LayerInspector/LayerInspectorView.swift
Use computed var in view for `layerInspectorData`
> Fix occasional mismatch between sidebar selection state and inspector's focused layer

- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Pulse/PulseReversionUtils.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
- Stitch/Graph/ViewModel/GraphState.swift
Logic moved to a new helper for row outputs observers which now processes each change for pulses.
> Fixed pulse reversion effects regression

- Stitch/Graph/Sidebar/Model/Gesture/SidebarSelectionState.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift
- Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
Fixes a regression from the way we changed sidebar-focus. 
1. Cmd+A now looks at sidebar-focus
2. sidebar-focus set true when layer tapped, not when primary-selections reset
> Only focus sidebar when sidebar layer tapped or dragged

- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift
Otherwise layer group background (additional one applied for .shadow) does not rotate.
> Apply .rotation after .shadow on LayerGroup

- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonMisc.swift
Use value 0-1 in axis tuple for `.rotation3DEffect`
> Respect positive vs negative rotation angles

- Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift
- Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupCreated.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupUncreated.swift
- Stitch/Graph/Sidebar/ViewModel/SidebarItemGestureViewModel.swift
Fixes regression. 
We now derive a layer node view model's layer group parent from sidebar items.
TODO: remove `layerGroupId` from schema ?
https://github.com/user-attachments/assets/4864f93b-fed6-4b29-b392-ff36ecf457a5
> Rely on sidebar data for a layer's parent

- Stitch/Graph/Node/Patch/Type/Shape/LayerInfoNode.swift
Fixes a regression from the removal of a guard statement when updating LayerInfo eval to work with loops.
> Skip LayerInfo patch eval if assigned layer's preview models not yet created

- Stitch/Graph/Node/View/CanvasItemPositionHandler.swift
Fixes regression; but need a better solution here to keep the perf improvement by not having the `if/else` statement.
> Do not apply .position modifier to NodeView during node insertion animation

- Stitch/App/View/Component/StitchTextEditingField.swift
- Stitch/Graph/Node/Title/View/CanvasItemTitleView.swift
- Stitch/Graph/Node/Title/View/NodeTitleTextField.swift
- Stitch/Graph/Node/View/CanvasItemSelectedViewModifier.swift
We use a canvas item's pre-edit width during title edits. Note that we still have some change in width and there is still occasional stutters on very large graphs, but overall this feels smoother.
> Reduce jitters when during node title edits

- Stitch/Graph/Node/Util/NodeCreatedAction.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupCreated.swift
Note: no changes to duplication / copy-paste.
https://github.com/user-attachments/assets/bc757280-a385-4437-a245-a56103e61683
https://github.com/user-attachments/assets/8d783caf-ed62-46b1-bc57-29a4ea4018a1
> Focus newly created layer nodes (including groups) in inspector

- Stitch/App/View/Component/StitchButton.swift
- Stitch/App/View/Component/StitchSheet.swift
- Stitch/App/View/ViewUtil/StitchHostingController.swift
- Stitch/App/View/ViewUtil/UIKitWrapper.swift
- Stitch/Graph/Edge/Model/EdgeEditingState.swift
- Stitch/Graph/Edge/Util/EdgeEditingActions.swift
- Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuSearchBar.swift
- Stitch/Graph/Node/Patch/Type/Interaction/Keyboard/KeyPressActions.swift
- Stitch/Graph/PrototypePreview/Frame/View/FullScreenGestureRecognizerView.swift
- Stitch/Graph/PrototypePreview/Frame/View/PreviewContent.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemGestureRecognizerView.swift
- Stitch/Graph/View/ContentView.swift
Vastly extends usefulness of edge-edit-mode. Was also a feature requested by Jay.
https://github.com/user-attachments/assets/bc35f23d-1e1f-4a4b-89b2-5101808c6dae
> TAB between eligible nodes during edit mode

- Stitch/Graph/Node/Port/Model/PortValue/Type/JSON/JSONUtils.swift
- Stitch/Graph/Node/Port/Util/PortValue/PortValueDisplay.swift
- Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift
- Stitch/Graph/StitchAI/GraphPrompting/API/StitchAIConstants.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StateChangeToStepAction.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepActionToStateChange.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StitchAIDataModel.swift
We now encode and decode values as `JSONFriendlyFormat`, so we theoretically support all PortValue types but we need to extend the node_types listed in the OpenAI schema. 
(Also fixes bug with creating connections from OpenAI-generated data.)
In practice the non-fine-tuned model can get the following prompts right about 50% of them:
- Create a value node, change its node type to Size, then change its input to be width = 300 and height = 200
- Create a value node, change its node type to Position, then change its input to be x = 300 and y = 200
^^ when we get e.g. "width = 300, height = 300" on a node as the final result, it's because the model created two separate `SetInput` steps, each which has `.number(300)`; i.e. the model is creating incorrect information; our action-parsing logic …
> Support wider variety of PortValue types in StitchAI Step actions

- Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift
- Stitch/Graph/PrototypePreview/Frame/View/PreviewWindowElementUIKitGestures.swift
- Stitch/Graph/PrototypePreview/Layer/Model/LayerData.swift
- Stitch/Graph/PrototypePreview/Layer/Util/LayerNodesSorting.swift
- Stitch/Graph/PrototypePreview/Layer/View/GeneratePreview.swift
- Stitch/Graph/PrototypePreview/Layer/ViewModel/LayerViewModel.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
We now extend masker and masked view loops to be as the length of the longest loop. 
https://github.com/user-attachments/assets/97cb7459-7f55-4150-abb9-c0b6d7e734d5
https://github.com/user-attachments/assets/2d8dcb57-0c76-4c64-b0ba-f12d6b6d8c68
> Better support masking when the masked and masking views have different loop length

- Stitch/Graph/Menu/InsertNodeMenu/Util/InsertNodeMenuActions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6700
Issue was caused by not resetting focus field state when submitting the form for a new node.
> Fixed regression where edge creation on output hover would fail

- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6704
Issue was due to no port locations having been created.
> Fixed regression where edge would fail on newly added input

- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6690
Issue was incorrect title height logic specifically for the math expression node.
> Fixed math expression node edge locations

- Stitch/Graph/Node/Title/View/CanvasItemTitleView.swift
- Stitch/Graph/Node/Title/View/MathExpressionSubmenuButtonView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6686.
Main issue was due to not applying a height modifier to the wireless receiver menu to match the default height in the title view.
> Fixed wireless receiver outgoing edge regression

- Stitch/App/View/StitchRootView.swift
- Stitch/Graph/Gesture/Util/GraphUITappedActions.swift
- Stitch/Graph/Menu/InsertNodeMenu/Util/InsertNodeMenuActions.swift
- Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenu.swift
- Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuWrapper.swift
- Stitch/Graph/View/ContentView.swift
- Stitch/Graph/View/GraphBaseView.swift
- Stitch/Graph/View/Util/ProjectWindowSizeReader.swift
- Stitch/Graph/ViewModel/GraphUI.swift
Also: add drop shadow to menu. Menu is dismissed when we scroll or tap outside. 
Notes:
- We have already disabled the node insertion animation for now; can re-introduce it later.
- We still correctly shrink the menu height on smaller devices like iPad Mini
https://github.com/user-attachments/assets/63f7acde-5989-4a33-ab30-ad4a477b051f
> Place node menu above sidebar

- Stitch/Graph/LayerInspector/GenericFlyoutView.swift
- Stitch/Graph/LayerInspector/LayerInspectorActions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6720.
Issue was due to not resetting the new cache used for layer inputs.
> FIxed unpacked canvas node insertion regression

- Stitch/Graph/Node/Group/GroupNodeDestructionActions.swift
- Stitch/Graph/Node/Util/NodeDeletedAction.swift
- Stitch/Graph/ViewModel/GraphState.swift
Notes: 
1. deleting a GroupNode is deleting a canvas item
2. the children of a GroupNode are canvas items as well (e.g. layer inputs, never a full layer node itself)
https://github.com/user-attachments/assets/63abda1e-d64b-4c15-a93c-02717865634f
> Do not delete a layer node when deleting a GroupNode containing one of the layer's inputs

- Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
- Stitch/Graph/Node/Port/View/PortView.swift
- Stitch/Graph/Node/View/NodeViewType.swift
The PortValues-preview for looped values in an input and output now opens consistently and with the correct values.
One of the perf-related checks was not required since the popover's view is only re-rendered when the popover is actively open. 
https://github.com/user-attachments/assets/84914dbd-6923-4b62-923a-001ab0a90a7e
> Improve responsiveness of looped-values preview

- Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
- Stitch/Graph/Node/Patch/ViewModel/PatchNodeViewModel.swift
- Stitch/Graph/Node/Port/Util/TypeChange/NodeTypeChangedActions.swift
- Stitch/Graph/Node/View/NodeTag/NodeTagMenuButtonsView.swift
- Stitch/Graph/Node/View/NodeView.swift
- Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift
- Stitch/Graph/ViewModel/GraphState.swift
Specifically, unresponsive whenever the node contained an upstream connection. New values caused the node's views to render due to logic for determining active loop counts. We're good so long as that logic is kept outside the menu view, because those extra renders cause the menu to freak out.
Additional logic was made to properly support undo scenarios of node type changing.
> Fixed bug where node type menu on iPad was unresponsive

- Stitch.xcodeproj/project.pbxproj
- Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Stitch/App/Util/TypeExtension/MiscUtils.swift
- Stitch/App/Util/URL/URLSessionExtensionUtils.swift
- Stitch/Graph/Node/Patch/Type/Data/NetworkRequestNode.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/JSON/JSONReplViews.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/NetworkRequest/NetworkRequest.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/NetworkRequest/NetworkRequestHandleResponse.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/NetworkRequest/NetworkRequestUITestView.swift
Prioritized for Swift 6 migration work, which had some concurrency issues with BrightFutures.
Validated with JSON + image requests that things are good here.
> Replaced BrightFutures with async/await

- Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift
- Stitch/Graph/StitchAI/GraphPrompting/API/StitchAIConstants.swift
* Ensures actual implementation of structured outputs (`strict = true`)
* Set `additionalProperties = false` for all objects
* Modifies schema to eliminate all JSON keywords not supported by the OpenAI JSON validator
> Structured outputs conformance

- Stitch/Graph/Edge/Util/EdgeEditingActions.swift
- Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift
https://github.com/user-attachments/assets/999830eb-41e7-479c-86c8-bde451ad3389
> Edge edit mode: Compare distance between hovered output and node's inputs, not node's center

- Stitch/Graph/Node/Port/Model/Field/FieldValue.swift
- Stitch/Graph/Node/Port/View/PortValuesPreviewView.swift
We now: 
1. support more types (like anchoring), 
2. use fixed width (to avoid jitters when e.g. a Time node connected)
3. change active index upon hover
Also cleaned up the UI some.
https://github.com/user-attachments/assets/4def0480-fb2a-4bea-8103-4f0b14ab6a42
> UX improvements for previewing a port's looped values

- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewImage.swift
Resolves regression while still solving hit areas from this earlier PR: https://github.com/StitchDesign/Stitch/pull/593/files
> Fix fitStyle = fill with images

- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewImage.swift
https://github.com/user-attachments/assets/72f09a20-16a9-4121-8c48-cfc11bb538f0
https://github.com/user-attachments/assets/e50b70d2-e1cd-495e-b43c-94bd9fd882d7
> Properly anchor images that use `auto` dimension (i.e. image resource's length) 

- Stitch/Graph/Menu/InsertNodeMenu/Model/InsertNodeMenuState.swift
- Stitch/Graph/ViewModel/GraphUI.swift
(Resolves regression from updating node menu to no longer be moved by opening or closing the left sidebar.)
`doubleTapLocation` was really only for InsertNodeMenuState, where it is now stored and properly reset when node menu state reset.
https://github.com/user-attachments/assets/7d9be48b-a204-4931-a92d-951b5b6e8c13
> Add nodes to center of canvas when node menu has been dismissed

- Stitch/Graph/Gesture/View/GraphMovementViewModifier.swift
- Stitch/Graph/Node/Patch/Type/Shape/LayerInfoNode.swift
- Stitch/Graph/Node/Port/Util/NodeRowObserverUtil.swift
- Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift
- Stitch/Graph/Node/Port/View/Field/NodeFieldsView.swift
- Stitch/Graph/Node/Port/View/Field/OutputValueView.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
- Stitch/Graph/Node/View/NodeLayout.swift
- Stitch/Graph/Node/View/NodeView.swift
- Stitch/Graph/Node/View/NodeViewType.swift
- Stitch/Graph/Node/View/NodesOnlyView.swift
- Stitch/Graph/Util/NodeSelection/NodeSelectionUtil.swift
- Stitch/Graph/View/InfiniteCanvas.swift
The problem addressed in this PR is lost FPS for scenarios involving static large graphs.
Two main changes here:
1. Brought back functionality which prevent field updates from off-screen fields
2. Removed an unnecessary dispatch used for recalculating layers
> Perf improvements from decreased field updates

- Stitch/Graph/LayerInspector/GenericFlyoutView.swift
- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
- Stitch/Graph/Node/Util/NodeDeletedAction.swift
The unpacked field's value was being overwritten by an unexpected call to `layerInputObserver.wasPackModeToggled()` in `LayerInspectorInputPortView`. 
We now only rely on redux actions like `deleteCanvasItem` and `LayerInputFieldAddedToCanvas`, instead of the view, to synchronize packed vs unpacked fields.
Ideally, if not too bad for perf, we could update both the packed and unpacked fields.
https://github.com/user-attachments/assets/22684333-435f-4c28-aab0-1d7ace6bf0ed
> A layer's fields on canvas no longer lose their value when the layer is selected again in sidebar

- Stitch/App/Serialization/DocumentLoading/DocumentEncodable.swift
- Stitch/App/Serialization/DocumentLoading/DocumentLoader.swift
- Stitch/App/Serialization/DocumentLoading/ProjectLoader.swift
- Stitch/App/View/StitchNavStack.swift
- Stitch/App/ViewModel/StitchStore.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
- Stitch/Home/View/ProjectItem/ProjectsListItemLoadedView.swift
- Stitch/Home/View/ProjectItem/ProjectsListItemView.swift
Caused by #635.
Encoder was using the wrong ID when undo was fired. To be safe I'm reverting the change where we replaced StitchDocumentViewModel with ProjectLoader in the navPath in case there were other ripple effects from this.
This revert keeps the perf improvements made on the home screen.
> Fixed regression where undo would cause crash

- Stitch/Home/View/ProjectItem/ProjectsListItemView.swift
Strangely, on a 2020 MacBook Air M1 with 8 GB RAM, `.high` priority does not properly load projects on homescreen but `.low` and `.background` do. 
So, using `.low` until we can debug further.
> Use .low priority instead of .high to properly load project on homescreen

- Stitch/Graph/LayerInspector/LayerInspectorView.swift
- Stitch/Graph/Node/Model/RowData/LayerInputType.swift
- Stitch/Graph/PrototypePreview/Frame/View/NativeScrollGestureView.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewAbsoluteShapeLayerModifier.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonModifierWithoutFrame.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift
> iPad, upon project first open: better re-rendering when a Group Layer's Scroll Enabled input is set true

- Stitch.xcodeproj/project.pbxproj
- Stitch/Graph/View/DebugModePopover.swift
- Stitch/Graph/View/GraphBaseView.swift
- Stitch/Graph/View/StitchProjectOverlayView.swift
The popover UI for the new debug mode would sit on top of the layer inspector if dragged in enough. Fix here left-aligns the popover, constrains the width, and moves it to new hierarchy so that the inspector would overlap instead of the other way around.
> Fixed debug mode popover layout issue

- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
Caused by recent schema changes which used to save node kind in schema.
> Disable fatal error regression on node kind getter

- Stitch/Graph/StitchAI/DatasetRecording/LLMActionRecording.swift
Fixes issue where nodes were considered offscreen once recording mode began.
> Do not change graph offset when LLM Recording Mode starts

- Stitch/Graph/Node/Layer/Type/Media/RealityView/PreviewRealityLayer.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift
Camera settings are used to infer camera direction, and on reality layer node creation we ignore the camera direction input. This PR updates camera settings if there's a mismatch between the layer input and camera settings.
> Fixed camera direction mismatch on reality node creation

- Stitch/App/View/Component/StitchButton.swift
- Stitch/App/View/Component/StitchSheet.swift
- Stitch/App/View/Component/StitchTextEditingField.swift
- Stitch/App/View/ViewUtil/StitchHostingController.swift
- Stitch/App/View/ViewUtil/UIKitWrapper.swift
- Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuSearchBar.swift
- Stitch/Graph/Node/Port/Model/Field/FieldValue.swift
- Stitch/Graph/Node/Port/Model/Field/FocusedUserEditField.swift
- Stitch/Graph/Node/Port/Util/PortValue/Parsers.swift
- Stitch/Graph/PrototypePreview/Frame/View/FullScreenGestureRecognizerView.swift
- Stitch/Graph/PrototypePreview/Frame/View/PreviewContent.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemGestureRecognizerView.swift
- Stitch/Graph/Util/KeyBindingActions.swift
- Stitch/Graph/View/ContentView.swift
- Stitch/Graph/ViewModel/GraphUI.swift
Notes:
1. we still support regular up- and down-arrow functionality in text fields that do not use numbers (first part of video)
2. we support changing a percentage!
3. currently, we do not continue to inc/dec when the arrow key is held down
https://github.com/user-attachments/assets/6da8ea62-0580-457e-a040-0d8cc656cd06
> Use up- and down-arrow keys to increment or decrement a number field

- Stitch/Graph/Node/Model/RowData/LayerInputType.swift
- Stitch/Graph/Node/Port/View/Field/NodeFieldsView.swift
- Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
Just a small UI change. 
TODO: the labels probably need to be on same row as the fields? do we drop the x,y,z labels?
> Header for 3D Transform flyout, left-align labels

- Stitch/Graph/GraphStep/GraphStepIncrementer.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
Also: properly update the unpacked fields in response to user's gesture.
> Do not crash when editing 3D Transform field on canvas

- Stitch.xcodeproj/project.pbxproj
- Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
Has latest changed for SSK V29 migrations.
> Use StitchSchemaKit `main` branch

- Stitch/Graph/Node/Port/Model/Field/FieldValue.swift
- Stitch/Graph/Node/Port/ViewModel/NumberFormatterObserver.swift
Shows sig digits now when previously would just show "0.0".
> Improved number formatting for many significant digits

- Stitch/App/View/StitchNavStack.swift
Not seeing memory usage decrease but debugger confirms StitchDocumentViewModel is no longer retained in some scenarios.
> Removed references to documents when projects close

- Stitch/Graph/Node/Model/RowData/LayerInputType.swift
- Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift
Fixes a small regression and also properly labels the 3D Transform input on canvas (less confusing for user).
> Show 3D Transform label in flyout and on packed canvas input

- Stitch/Home/View/ProjectItem/ProjectsListItemLoadedView.swift
Problem: the thumbnail view had an outdated version of the StitchDocument struct, which was supposed to have been modified and encoded by the text edit view. 
Original implementation seemed to expect a side-effect (persistence) to trigger our directory-listening logic, which would then update our UI.
Rather than rely on a side-effect, we can just make the state change manually, which triggers the view updates.
https://github.com/user-attachments/assets/aacf77e1-e14e-435c-bc67-e6070f11652e
https://github.com/user-attachments/assets/6a06069e-0ad9-498c-b7a9-21aa555301da
> Manually update StitchStore with the loaded StitchDocument's name change

- Stitch/Graph/Node/Layer/Type/Media/3DModelLayerNode/Model3DView.swift
- Stitch/Graph/Node/Layer/Type/Media/3DModelLayerNode/PreviewModel3DLayer.swift
- Stitch/Graph/Node/Layer/Type/Media/RealityView/PreviewRealityLayer.swift
- Stitch/Graph/Node/Model/Definition/NodeDefinition.swift
- Stitch/Graph/Node/Patch/Type/ARRaycastingNode.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/AR/RealityView.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/AR/StitchARView.swift
New ARViews weren't creating new render cycles, which were needed to fix an issue where a 3D model layer could be dragged in/out of a reality view but not re-appear in the scene.
> Fixed 3D entity handling when exiting reality view

- Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuSearchBar.swift
- Stitch/Graph/StitchAI/GraphPrompting/API/SupabaseManager.swift
* remove stitch ai compiler flag for the insert node menu
* ensure that if we are NOT in correction mode, we do NOT show a json modal to the user twice
> ai flow fixes

- Stitch/Graph/Node/Port/Util/TypeChange/NodeTypeChangedHelpers.swift
There are probably a few other places where we are using fatal errors that would cause an undesired crash on a release build. 
We encountered this on a TestFlight for AI work.
TODO: support more node-types in Spring Animation patch?
> SpringAnimationState: Do not crash with fatalError on production

- Stitch/Graph/Node/Util/NodeCreatedAction.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepActionToStateChange.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6820
> Use the nodeId from the Step created by the LLModel

- Stitch/Graph/StitchAI/DatasetRecording/LLMActionRecording.swift
- Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift
- Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepActionToStateChange.swift
- Stitch/Graph/StitchAI/GraphPrompting/StitchAIEvents.swift
- Stitch/Graph/StitchAI/GraphPrompting/UI/StitchAIPromptView.swift
- Stitch/Graph/Util/GraphUIActions.swift
- Stitch/Graph/View/ContentView.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
This PR:
1. LLM Edit Modal would open when regular recording modal closed (messed up Supabase uploads)
2. Cleans up code (mostly removes older implementation)
> Do not open LLM Edit Modal when regular recording session ends

- Stitch/Graph/Node/View/NodeView.swift
- Stitch/Graph/StitchAI/DatasetRecording/LLMActionHelpers.swift
- Stitch/Graph/StitchAI/DatasetRecording/LLMActionRecording.swift
- Stitch/Graph/StitchAI/DatasetRecording/LLMModalViews.swift
- Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift
- Stitch/Graph/StitchAI/GraphPrompting/UI/EditBeforeSubmitModalView.swift
https://github.com/user-attachments/assets/765938f0-1275-44e2-96ca-ceac6650761c
> Record user's actions when "Edit Before Submit" modal is open; visually indicate AI-created nodes etc.

- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemSwipeView.swift
- Stitch/Graph/Sidebar/ViewModel/SidebarItemGestureViewModel.swift
- Stitch/Graph/Sidebar/ViewModel/SidebarItemSwipable.swift
Fixes an issue where graph state is retained by .onHover, specifically with the sidebar.
Strange behavior as we're implementing best practices. Appears the view isn't garbaged collected as a consequence of .onHover.
> Fixed issue where graph media could be retained by onHover

- Stitch/Graph/Node/Patch/Type/Text/SplitTextNode.swift
> SplitText patch only uses last value in each input's loop

- Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StateChangeToStepAction.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepActionToStateChange.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepTypeAction.swift
- Stitch/Graph/StitchAI/GraphPrompting/UI/EditBeforeSubmitModalView.swift
improve canvas item positioning logic = treat nodes without incoming connections as having depth level of 0
> LLM: show reason why actions were invalid or could not be applied; improve canvas item positioning logic

- Stitch/Graph/Node/Eval/MediaEvalOpObservable.swift
- Stitch/Graph/Node/Eval/PatchEvaluateExtensions.swift
- Stitch/Graph/Node/Model/Definition/NodeDefinition.swift
- Stitch/Graph/Node/Model/Definition/PatchNodeDefinitionKinds.swift
- Stitch/Graph/Node/Patch/Type/Loop/LoopSelectNode.swift
- Stitch/Graph/Node/Patch/Util/PatchDefaultNodeExtensions.swift
- Stitch/Graph/Node/Port/Util/PortValue/PortValueUtils.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel.swift
- StitchTests/evalTests.swift
This PR continues recent media refactoring by adding support for the loop select node.
In addition, we improved eval support for nodes by no longer requiring usage of the eval switch statement for node kinds.
> Fixed media regression on loop selector

- Stitch/Graph/Edge/Util/PortActions.swift
- Stitch/Graph/Node/Eval/MediaEvalOpObservable.swift
- Stitch/Graph/Node/Patch/Type/CoreMLClassifyNode.swift
- Stitch/Graph/Node/Patch/Type/CoreMLDetectionNode.swift
- Stitch/Graph/Node/Patch/Type/Delay/DelayNode.swift
- Stitch/Graph/Node/Patch/Type/Loop/LoopBuilder.swift
- Stitch/Graph/Node/Patch/Type/Loop/LoopSelectNode.swift
- Stitch/Graph/Node/Patch/Type/Media/SoundImportNode.swift
- Stitch/Graph/Node/Patch/Type/Media/SpeakerNode.swift
- Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift
- Stitch/Graph/Node/Port/View/Field/OutputValueView.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowViewModel.swift
- Stitch/Graph/Node/Util/NodeMediaUtils.swift
- Stitch/Graph/PrototypePreview/Layer/View/GeneratePreview.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6856.
Solves an issue that directly targets nodes like splitters which have the ability to point to some media.
Given recent changes, media isn't directly passed from node to node via port values. This PR fixes media referencing for nodes that don't mutate objects. The solution uses a fallback method for searching for media, rather than requiring updates to each node eval, thus providing a maintainable approach.
> Fixed regression where media objects sometimes aren't retained

- Stitch/App/View/StitchRootView.swift
- Stitch/Graph/Gesture/View/GraphMovementViewModifier.swift
- Stitch/Graph/Menu/InsertNodeMenu/Model/InsertNodeMenuState.swift
- Stitch/Graph/Menu/InsertNodeMenu/Util/InsertNodeMenuActions.swift
- Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenu.swift
- Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuSearchResults.swift
- Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuWrapper.swift
- Stitch/Graph/Node/View/StitchUIScrollView.swift
- Stitch/Graph/View/ContentView.swift
- Stitch/Graph/View/Util/ProjectWindowSizeReader.swift
This PR removes animation logic for the insert node menu, which had been cancelling UI gestures while the insert node menu closes.
> Improved graph responsiveness from insert node menu closing

- Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
> Display a splitter's output fields if splitterType = output and we are viewing the group from the outside

- Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/LLMValueParsingUtils.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StateChangeToStepAction.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/Step.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepTypeAction.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StitchAICodableTypes.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StitchAITypeCasting.swift
Pseudo revert, we use a protocol called `StitchAIStringConvertable` instead of `StringOrNumber`, which uses the logic from the latter but allows for flexibility with more types than just numbers. Possibly useful if this strategy proves necessary.
> Revert parsing logic to better handle string types

- Stitch.xcodeproj/project.pbxproj
- Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Stitch/Graph/Node/Port/Util/NodeRowObserverUtil.swift
- Stitch/Graph/Node/Port/Util/PortValue/CoercerUtils.swift
- Stitch/Graph/Node/Port/Util/TypeChange/NodeTypeChangedHelpers.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
We were not actually removing the interaction assignment for a given layer, leading to cases where a layer group's old interactions interfered with children's hit areas below.
TODO: write a thorough test for layer-assignments to interaction patches
> Properly de-assign an interaction from a layer

- Stitch/Graph/Node/Patch/Type/Animation/ClassicAnimation.swift
- Stitch/Graph/Node/Patch/Type/Animation/spring+and+pop+animations/PopAnimationNode.swift
- Stitch/Graph/Node/Patch/Type/Animation/spring+and+pop+animations/SpringAnimationNode.swift
- Stitch/Graph/Node/Patch/Type/Animation/spring+and+pop+animations/SpringAnimationNumberOp.swift
- Stitch/Graph/Node/Patch/Type/Animation/spring+and+pop+animations/SpringAnimationPositionOp.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Animation/ClassicAnimation/Eval/ClassicAnimationColor.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Animation/ClassicAnimation/Eval/ClassicAnimationNumber.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Animation/ClassicAnimation/Eval/ClassicAnimationOpAnchoring.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Animation/ClassicAnimation/Eval/ClassicAnimationOpSize.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Animation/ClassicAnimation/Eval/ClassicAnimationPoint3D.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Animation/ClassicAnimation/Eval/ClassicAnimationPoint4D.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Animation/ClassicAnimation/Eval/ClassicAnimationPosition.swift
We had inconsistent behavior across Graph Open vs Graph Reset, since the first provided non-empty default outputs and the second set the outputs empty. 
We now treat both Graph Open and Reset as "graph time is zero."
https://github.com/user-attachments/assets/4fd05a4e-0a40-4899-923b-a05a857101e7
> Start at animation goal when graph opened

- Stitch/Graph/Node/Port/Util/InputEdit/InputCommittedActions.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepActionToStateChange.swift
We were passing in a separate `nodeId` parameter which was actually different from the `nodeId`; this bug may have come  when we started querying the state for the `node` directly rather than relying on the `input.nodeDelegate`.
> Retrieve `nodeId` from the passed-in `input`, not a separately passed-in `nodeId`

- Stitch/Graph/Node/Port/Util/InputEdit/InputCommittedActions.swift
- Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift
Log to Sentry if the field was not visible in frame when edited.
> Any edited field must be 'visible in frame'

- Stitch/Graph/Node/Port/Util/InputEdit/InputCommittedActions.swift
Follow up to https://github.com/StitchDesign/Stitch/pull/827
Need to find a better solution here; at least still like this as a UX improvement: no more inputs mysteriously rejecting edits.
> Do not crash or log to Sentry if input edited not yet considered on screen

- Stitch/Graph/Node/Patch/Type/DelayOneNode.swift
- Stitch/Graph/Node/Patch/Type/Math/AbsoluteValueNode.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6932
Not sure why `node.calculate` was not actually running the node on the next cycle. Possibly because input did not change? Anyway, we already have a return-value parameter for run-again cases like this.
> Use willRunAgain return value

- Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
- Stitch/Graph/View/ProjectNavigationView.swift
- Stitch/Graph/ViewModel/GraphState.swift
Improvements while exploring node duplication perf issues. Helpers in `ProjectNavigationView` created heavy perf loss.
> Reduced render cycles in ProjectNavigationView

- Stitch/Graph/Gesture/Util/GraphUIZoomedActions.swift
- Stitch/Graph/Gesture/View/GraphMovementViewModifier.swift
- Stitch/Graph/View/Gesture/GraphBackgroundGestureView.swift
- Stitch/Graph/View/GraphBaseView.swift
- Stitch/Graph/ViewModel/GraphUI.swift
Noticed that we were sometimes updating zoomData.current but not calling `updateVisibleNodes`; `GraphScrollDataUpdated` does not update `zoomData.current`; we no longer need SwiftUI MagnificationGesture and UIKit PinchGesture for the graph, since we use UIScrollView.
> Remove SwiftUI MagnificationGesture and UIKit PinchGesture on graph

- Stitch/Graph/PrototypePreview/Frame/View/FullScreenPreviewViewWrapper.swift
- Stitch/Graph/Sidebar/ViewModel/SidebarItemSwipable.swift
https://github.com/user-attachments/assets/b9ebe34f-04ca-43a5-9011-3b48d85a55b1
> Show 'exit prototype' message instead of 'exit fullscreen' on iPhone

- Stitch/Graph/Util/GraphActions.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6937
The issue is caused by persistence from node creation using a different flow than the new UI updating logic was leveraging. Logic has been moved to places which are consistently called on encoding.
> Fixed regression where new nodes couldn't establish edges

- Stitch/Graph/Node/View/NodeViewType.swift
- Stitch/Graph/Node/View/NodesOnlyView.swift
Fixes perf by moving expensive logic out of `var body`
> Reduced render cycles to NodesOnlyView

- StitchTests/openAIRequestTests.swift
Test was failing. We can revisit `PortValue.anchorEntity` later.
> For now, do not test encoding and decoding AnchorEntity PortValue type

- Stitch/Graph/Node/Eval/EvalKindNodeEvaluationHelpers.swift
- Stitch/Graph/Node/Eval/PatchEvaluateExtensions.swift
- Stitch/Graph/Node/Eval/PatchNodeType.swift
- Stitch/Graph/Node/Eval/UserVisibleTypeSet.swift
- Stitch/Graph/Node/Patch/Type/Math/AddNode.swift
- Stitch/Graph/Node/Patch/Type/Math/LengthNode.swift
- Stitch/Graph/Node/Patch/Type/Math/SubtractNode.swift
- Stitch/Graph/Node/Patch/Util/PatchNodeTypeExtensions.swift
**Test Projects**
[Color Arithmetic.stitch.zip](https://github.com/user-attachments/files/18946939/Color.Arithmetic.stitch.zip)
[ColorsTestProject.zip](https://github.com/user-attachments/files/18951405/ColorsTestProject.zip)
_Note_: length seems a bit different in OrigamI? ChatGPT could not make sense of what formula it was using when provided examples of calculating color length from Origami; I decided to go with calculating normalized vector length in RGB space
**Add Node:**
**Subtract Node**
**All Nodes**
> Color Arithmetic: Add, Subtract, Length

- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StitchAITypeCasting.swift
- StitchTests/openAIRequestTests.swift
Seems to be okay in actual app? Only test is messed up?
Switching to fatalError instead of XCTFail, which seems to not actually print the caught error.
> Skip interactionId in `testStitchAICodables`

- Stitch/Graph/Sidebar/Util/SidebarIcons.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6947
> Different icon for ColorFill vs Oval

- Stitch/Graph/Node/Group/GroupNodeCreationActions.swift
- Stitch/Graph/Node/Util/Movement/NodePositionUtils.swift
- Stitch/Graph/Node/Util/NodeDeletedAction.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/TextField/PreviewTextFieldLayerUtils.swift
- Stitch/Graph/Sidebar/Util/JumpToCanvasItem.swift
- Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift
- Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
- Stitch/Graph/Util/NodeSelection/NodeSelectionUtil.swift
- Stitch/Graph/ViewModel/GraphUI.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6951
We were accessing GraphState via NodeDelegate; a separate issue arose where a canvas item's NodeDelegate would be nil and so we would fail to access GraphDelegate. 
In reality, every method that called canvas item's select or deselect had a GraphState available in its context. 
Passing down GraphState directly both makes the function more transparent (= inputs communicate more info about what is required) and means these functions won't fail in the future even if we somehow mess up NodeDelegate again.
> Pass GraphState to CanvasItem select and deselect methods

- Stitch/Graph/Node/Eval/LoopedEval.swift
- Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift
- Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerView.swift
- Stitch/Graph/Node/Port/View/Field/OutputValueView.swift
- Stitch/Graph/Node/Port/ViewModel/FieldViewModel.swift
- Stitch/Graph/Node/View/NodeLayout.swift
Removing more expensive logic in `var body`, now moved to event handlers and called much less frequently.
> Reduced render counts for media views

- Stitch.xcodeproj/project.pbxproj
- Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Stitch/Graph/Edge/Util/PortActions.swift
- Stitch/Graph/GraphStep/GraphStepIncrementer.swift
- Stitch/Graph/Node/Patch/Type/Value/SplitterTypeActions.swift
- Stitch/Graph/Node/Patch/Type/WirelessBroadcasterNode.swift
- Stitch/Graph/Node/Patch/Util/WirelessReceiver.swift
- Stitch/Graph/Node/Port/Util/InputEdit/InputCommittedActions.swift
- Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift
- Stitch/Graph/Node/Port/Util/TypeChange/NodeTypeChangedActions.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverCachedViewDataExtensions.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
- Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift
- Stitch/Graph/Node/Util/Movement/NodePositionUtils.swift
- Stitch/Graph/Node/Util/NodeViewModelUtils.swift
- Stitch/Graph/Node/View/NodeView.swift
- Stitch/Graph/Node/View/StitchUIScrollView.swift
- Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel.swift
- Stitch/Graph/Util/GraphUIActions.swift
- Stitch/Graph/ViewModel/GraphUI.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
- StitchTests/evalTests.swift
Noticed we were relying on NodeDelegate for GraphState in the CanvasItem's select and deselect methods. We still need to fix the bug that caused NodeDelegate to be missing, but with this change we no longer expose other parts of the app to that failure (more maintainable).
This change only removes `GraphDelegate` from `CanvasItemViewModel`. `NodeDelegate` still has `GraphDelegate` etc.
It ended up being small because in every context where we were accessing NodeDelegate.graphDelegate, we had `graph` in the parent caller.
We get:
1. **consistency**: one way to access GraphState (via GraphState method / action handler); we no longer do weird things where a function is called in context where GraphState exists yet we access the optional GraphDelegate
2. **greater function transparency**: …
> Prefer passing down `GraphState` directly

- Stitch/Graph/Node/Patch/Type/Loop/LoopInsert.swift
Previously:
Now:
https://github.com/user-attachments/assets/24ba267c-da40-455d-b3e9-7da9c7e681e5
> Use inputs if outputs are empty for LoopInsert node

- Stitch/Graph/CommentBox/Util/CommentBoxActions.swift
- Stitch/Graph/CommentBox/Util/CommentBoxGestureActions.swift
- Stitch/Graph/Gesture/Util/GraphUIScrollActions.swift
- Stitch/Graph/Gesture/Util/GraphUITappedActions.swift
- Stitch/Graph/Gesture/Util/GraphUIZoomedActions.swift
- Stitch/Graph/Gesture/View/GraphMovementViewModifier.swift
- Stitch/Graph/Gesture/ViewModel/GraphMovementObserver.swift
- Stitch/Graph/GraphStep/GraphStepIncrementer.swift
- Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuWrapper.swift
- Stitch/Graph/Node/Patch/Type/DeviceInfoNode.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift
- Stitch/Graph/Node/Port/View/PortView.swift
- Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift
- Stitch/Graph/Node/Util/Movement/NodePositionUtils.swift
- Stitch/Graph/Node/Util/NodeCreatedAction.swift
- Stitch/Graph/Node/View/NodesOnlyView.swift
- Stitch/Graph/Node/View/NodesView.swift
- Stitch/Graph/Node/View/StitchUIScrollHelpers.swift
- Stitch/Graph/Node/View/StitchUIScrollView.swift
- Stitch/Graph/Node/ViewModel/NodePageData.swift
- Stitch/Graph/Sidebar/Util/JumpToCanvasItem.swift
- Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/GraphUI.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
In the future, might be nice to: 
1. completely remove GraphMovementObserver and just rely on NodePageData's offset and zoom
2. have a way to subscribe directly to UIScrollView's zoomScale and contentOffset, without intermediate state (attempted this but `UIScrollView` is not Sendable? Also weird imo to store the view in state...)
Note: large number of files changed because I removed `class GraphZoom` since zoom gesture now longer needs `current` vs ` final`. 
https://github.com/user-attachments/assets/61e0007b-c04e-4a55-b6bb-d486679f308e
> Use offset and zoom per traversal level; use graph-center if entering level for first time

- Stitch/Graph/CommentBox/Util/CommentBoxActions.swift
- Stitch/Graph/Edge/Util/EdgeEditingActions.swift
- Stitch/Graph/Node/Group/GroupNodeCreationActions.swift
- Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift
- Stitch/Graph/Node/View/NodesView.swift
- Stitch/Graph/Node/View/StitchUIScrollView.swift
- Stitch/Graph/Sidebar/Util/JumpToCanvasItem.swift
- Stitch/Graph/Util/GraphStateCardinalPoints.swift
- Stitch/Graph/Util/GraphUIActions.swift
- Stitch/Graph/Util/NodeSelection/NodeSelectionUtil.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/GraphUI.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
Renamed other methods to explicitly distinguish between nodes / canvas items at traversal level vs visible in frame.
> `getVisibleXYZ` now only refers to `isVisibleInFrame`

- Stitch.xcodeproj/project.pbxproj
- Stitch/Graph/Node/Port/View/Field/OutputValueView.swift
- Stitch/Graph/Node/View/NodesOnlyView.swift
- Stitch/Graph/Node/View/NodesView.swift
- Stitch/Graph/StitchAI/DatasetRecording/LLMActionHelpers.swift
- Stitch/Graph/StitchAI/DatasetRecording/LLMActionRecording.swift
- Stitch/Graph/StitchAI/DatasetRecording/LLMAssignPromptToScratchLLMExampleModalView.swift
- Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepActionToStateChange.swift
- Stitch/Graph/View/ContentView.swift
- Stitch/Graph/View/ProjectNavigationView.swift
- Stitch/Graph/ViewModel/GraphState.swift
Eventually would be nice to clean up this code a bit more.
> When creating example from scratch, show LLM Edit Modal before submitting; Supabase submissions have proper correction vs from-scratch

- Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift
Fixes connections and non-moving nodes. Issue was caused by action reapplying logic actually deleting nodes, which is an issue for the new system which caches objects locally. Those cached objects needed to be completely reset, which is why this fix works.
> Fixed regression for Stitch AI edit mode

- Stitch/Graph/ViewModel/GraphState.swift
Our algorithm got around this because we also hash based on `manualEdits`, which looks at nil vs non-nil.
Really, `manualEdits` is just counting non-connected inputs. `manualEdits` and `upstreamConnections` always add up to the total number of inputs on the graph, so we only need one, not both?
> Do not count `nil` `upstreamOutputCoordinates` as valid upstreamConnections in `calculateGraphUpdaterId`

- Stitch/App/View/Component/StitchTextEditingField.swift
- Stitch/Graph/Edge/Util/PortActions.swift
- Stitch/Graph/Menu/InsertNodeMenu/Util/InsertNodeMenuActions.swift
- Stitch/Graph/Node/Patch/Util/PatchDefaultNodeExtensions.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/CameraFeed/Util/CameraUtil.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift
- Stitch/Graph/Node/Port/Util/InputEdit/InputCommittedActions.swift
- Stitch/Graph/Node/Port/Util/InputEdit/PickerActions.swift
- Stitch/Graph/Node/Port/Util/TypeChange/NodeTypeChangedActions.swift
- Stitch/Graph/Node/Port/View/Field/InputView/AnchorEntitiesDropdownView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/EditJSONEntry.swift
- Stitch/Graph/Node/Util/NodeKindUtils.swift
- Stitch/Graph/Node/View/NodeView.swift
- Stitch/Graph/StitchAI/DatasetRecording/LLMActionHelpers.swift
- Stitch/Graph/StitchAI/DatasetRecording/LLMActionRecording.swift
- Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift
- Stitch/Graph/StitchAI/GraphPrompting/API/OpenAIRequest.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StateChangeToStepAction.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/Step.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepActionToStateChange.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepTypeAction.swift
- Stitch/Graph/StitchAI/GraphPrompting/UI/EditBeforeSubmitModalView.swift
- Stitch/Graph/View/GraphBaseView.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
This PR introduces automation for the list of actions generated by the user or the AI prompt for Stitch AI requests. Automating actions provides the following benefits:
1. Improves UX by removing the need for manual reordering
2. Improves reliability of training data by preventing superfluous action creation or any possibility of incorrect data
3. Improves consistency of training results by providing a consistent pattern of actions
Other benefits:
* Nodes no longer jump around after validation
* Nodes consistently show output values after validation
* New "Auto Validation" toggle allows users to enable validation checking, which is now a mostly* optional process for edit mode thanks to automated handling of actions
_* Still needed for deleting actions._
> Improved Stitch AI edit mode UX

- Stitch/Graph/Node/Eval/PatchEvaluateExtensions.swift
- Stitch/Graph/Node/Patch/Type/Math/DivideNode.swift
- Stitch/Graph/Node/Patch/Type/Math/MultiplyNode.swift
- Stitch/Graph/Node/Patch/Util/PatchNodeTypeExtensions.swift
[Color Multiply and Divide.origami.zip](https://github.com/user-attachments/files/19044143/Color.Multiply.and.Divide.origami.zip)
[Color Multiply and Divide.stitch.zip](https://github.com/user-attachments/files/19044144/Color.Multiply.and.Divide.stitch.zip)
> add color support for multiply and divide

- Stitch/Graph/LayerInspector/GenericFlyoutView.swift
- Stitch/Graph/Node/Port/View/Field/NodeFieldsView.swift
- Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6973
Note: we can give this area more love in the future; need some way to abstract over "packed = 1 field group with n field models" vs "unpacked = n groups with 1 field model each"
> LayerInspector: properly handle unpacked Margin and Padding layer inputs

- Stitch.xcodeproj/project.pbxproj
- Stitch/Graph/Node/Group/GroupNodeCreationActions.swift
- Stitch/Graph/Node/Group/GroupNodeDestructionActions.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/Util/NodeMediaUtils.swift
- Stitch/Graph/Node/View/NodeViewType.swift
- Stitch/Graph/Node/ViewModel/NodeDelegate.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModelNodeCalculatable.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6977
We now properly display inputs and outputs on a GroupNode.
`getInputObserverForUI(port, graph)` is now specifically for UI cases where GroupNode is needed; all other cases still use `getInputObserver(port)`.
Also moved implementation of NodeCalculatable to own file.
> In UI, retrieve GroupNode's underlying input- or output-splitters

- Stitch/Graph/Gesture/View/GraphMovementViewModifier.swift
- Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift
- Stitch/Graph/Util/NodeSelection/NodeSelectionUtil.swift
- Stitch/Graph/View/SelectionBox/ExpansionBoxView.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6965
https://github.com/user-attachments/assets/d6d5e714-78b5-4ce9-a0cb-e99da559c72e
> If GroupNode is visible-on-canvas, then so are its underlying input- and output-splitters

- Stitch.xcodeproj/project.pbxproj
- Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Stitch/Graph/GraphStep/GraphStepIncrementer.swift
- Stitch/Graph/LayerInspector/LayerInspectorState.swift
- Stitch/Graph/LayerInspector/LayerInspectorView.swift
- Stitch/Graph/LayerInspector/LayerMultiselect.swift
- Stitch/Graph/Menu/ProjectSettingsView.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Layer/LayerDimensionUtils.swift
- Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift
- Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift
- Stitch/Graph/Node/Port/View/Field/InputView/AnchorPopoverView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/BoolCheckboxView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingViewWrapper.swift
- Stitch/Graph/Node/Port/View/Field/InputView/DropDownChoiceView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/FieldValueNumberView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/LayerGroupAlignmentChoicesView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/LayerGroupOrientationDropDownChoiceView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/LayerNamesDropDownChoiceView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/SpecialPickerFieldValueView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/StitchFontDropdown.swift
- Stitch/Graph/Node/Port/View/Field/OutputValueView.swift
- Stitch/Graph/Node/Port/View/Field/ValueButton/ColorOrbValueButtonView.swift
- Stitch/Graph/Node/Port/View/Field/ValueButton/StitchColorPicker/StitchColorPickerView.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
This PR adds caching logic for reporting which fields display heterogenous values in a sidebar multiselect scenario. Previous logic introduced extra render cycles thanks to methods get `getNodeViewModel` which required view refresh whenever the nodes dictionary changed.
Perf improves in node duplication on humane demo by roughly 10%.
> Reduced render cycles from sidebar multiselect logic

- Stitch/Graph/Gesture/View/GraphMovementViewModifier.swift
- Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerView.swift
- Stitch/Graph/Node/View/StitchUIScrollHelpers.swift
- Stitch/Graph/Node/ViewModel/NodeDelegate.swift
... since we now always open the graph to the center anyway.
> Do not persist when graph scroll ends

- Stitch.xcodeproj/project.pbxproj
- Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Stitch/Graph/Edge/Util/PortActions.swift
- Stitch/Graph/Node/Eval/EphemeralObserver/NodeEphemeralObservable.swift
- Stitch/Graph/Node/Eval/MediaEvalOpObservable.swift
- Stitch/Graph/Node/Eval/PatchEvaluation.swift
- Stitch/Graph/Node/Layer/Type/Media/3DModelLayerNode/Model3DLayerUtil.swift
- Stitch/Graph/Node/Layer/Type/Media/3DModelLayerNode/Nodes/Model3DLayerNode.swift
- Stitch/Graph/Node/Layer/Type/Media/3DModelLayerNode/PreviewModel3DLayer.swift
- Stitch/Graph/Node/Model/RowData/NodeIOCoordiante.swift
- Stitch/Graph/Node/Patch/Type/Data/NetworkRequestNode.swift
- Stitch/Graph/Node/Patch/Type/Delay/DelayNodeUtil.swift
- Stitch/Graph/Node/Patch/Type/Interaction/PressInteractionPatchNode.swift
- Stitch/Graph/Node/Patch/Type/Media/MicrophoneFeedNode.swift
- Stitch/Graph/Node/Patch/Type/Media/SpeakerNode.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift
- Stitch/Graph/Node/Port/Util/PulseActions.swift
- Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerView.swift
- Stitch/Graph/Node/Port/ViewModel/FieldViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
- Stitch/Graph/Node/Util/NodeMediaUtils.swift
- Stitch/Graph/Node/Util/NodeUtils.swift
- Stitch/Graph/Node/View/StitchUIScrollView.swift
- Stitch/Graph/Node/ViewModel/NodeDelegate.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModelNodeCalculatable.swift
- Stitch/Graph/PrototypePreview/Layer/View/GeneratePreview.swift
- Stitch/Graph/PrototypePreview/Layer/ViewModel/LayerViewModel.swift
- Stitch/Graph/ViewModel/GraphState.swift
This PR aims to reduce media field rendering, which for some scenarios is the highest perf cost in the app. Changes here include:
* Media ephemeral objects now hold media for both "input" and "computed" copies, which aims to replace helpers that used functions to traverse upstream for media. These helpers created extra render cycles in the view.
* Node eval results now include an option for a media list, in addition to its existing port values. StitchEngine updates media ephemeral objects in hose flow.
Node duplication render duration in humane demo reduced by 1/3 after these changes.
> Improved perf with StitchEngine media handling

- Stitch/Graph/Node/View/StitchUIScrollHelpers.swift
- Stitch/Graph/Node/View/StitchUIScrollView.swift
Also re-arranged UIScrollViewDelegate method implementations to follow declaration order in documentation, to more easily see which methods we might not be implementing.
> Check borders when `scrollViewDidEndDragging` fires

- Stitch/Graph/Gesture/Util/GraphUIScrollActions.swift
- Stitch/Graph/Gesture/View/GraphMovementViewModifier.swift
- Stitch/Graph/Model/GroupNodeType.swift
- Stitch/Graph/Node/View/NodesOnlyView.swift
- Stitch/Graph/Node/View/NodesView.swift
- Stitch/Graph/Node/View/StitchUIScrollHelpers.swift
- Stitch/Graph/Node/ViewModel/NodePageData.swift
- Stitch/Graph/View/ProjectNavigationView.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
A `didSet` seems to avoid the race condition that apparently arose from `.onChange(groupNodeId)`.
We also no longer persist any root level graph-offset and will log-to-Sentry any very strange graph offset (seen once when exiting a group).
> Use `didSet` instead of `.onChange` to avoid race condition where the nodes in a just-entered group occasionally did not show

- Stitch/Graph/CommentBox/Util/CommentBoxActions.swift
- Stitch/Graph/CommentBox/View/CommentBoxView.swift
- Stitch/Graph/Node/Group/GroupNodeCreationActions.swift
- Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift
- Stitch/Graph/Node/Util/NodeDeletedAction.swift
- Stitch/Graph/Util/NodeSelection/CopyAndPasteNodesActions.swift
- Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
- Stitch/Graph/ViewModel/GraphUI.swift
- Stitch/Home/View/ProjectItem/ProjectsListItemView.swift
- StitchTests/nodeUIGroupingTests.swift
Including canvas layer inputs and outputs. 
Can copy-paste both layers and patches, including media. 
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6470
Note that copy-pasting media into the same project over and over again can be slow?
https://github.com/user-attachments/assets/d5c63a27-a0d0-47c0-9927-1e5ac950790b
> Copy + Paste support for layers

- Stitch/Graph/PrototypePreview/Frame/View/PreviewContent.swift
We added UIKitWrapper to even the EmptyView / hidden preview window because we wanted better / consistent key listening. However, we were still ending up with a hit area being covered. So we disabled hit tested.
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6989
> Disable hit-testing on the hidden preview window's UIKitWrapper

- Stitch/Graph/Node/View/NodeViewType.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6994
Regression from recent UI perf work; an easy mistake to make, just passing down the node assuming it was always the right one. GroupNode is an exception.
> Port label needs to look at group node's underlying splitter node

- Stitch/Graph/Node/View/NodesView.swift
- Stitch/Graph/Node/View/StitchUIScrollHelpers.swift
Perf problems caused by costly onChange handlers causing renders on all graph movement. Logic moved to actions which are consistently called on changes.
Perf regression from #915.
> Fixed perf from recent group node fixes

- Stitch/Graph/Node/Patch/ViewModel/PatchNodeViewModel.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Home/View/ProjectItem/ProjectsListItemView.swift
Text field logic requires the full document data struct, which causes render cycles if _anything_ in the structure changes (which happens on each encoding). Fix here is to use read-only logic when a graph is visible since the home screen text field isn't needed when a graph is open.
> Reduced render cycles from project title text fields

- Stitch.xcodeproj/project.pbxproj
- Stitch/Graph/Edge/Model/ConnectedEdgeData.swift
- Stitch/Graph/Edge/Model/EdgeAnchorData.swift
- Stitch/Graph/Edge/Model/EdgeEditingState.swift
- Stitch/Graph/Edge/Util/EdgeEditingActions.swift
- Stitch/Graph/Edge/Util/EdgeUtils.swift
- Stitch/Graph/Edge/View/EdgeDrawingView.swift
- Stitch/Graph/Edge/View/EditMode/EdgeEditModeLabelsView.swift
- Stitch/Graph/Edge/View/ExistingEdgesView.swift
- Stitch/Graph/Node/Group/GroupNodeCreationActions.swift
- Stitch/Graph/Node/Patch/ViewModel/PatchNodeViewModel.swift
- Stitch/Graph/Node/Port/View/PortValuesPreview/PortPreviewPopoverView.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/InputNodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/OutputNodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModel.swift
- Stitch/Graph/Node/View/NodesView.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
This PR caches needed edge data for populating visual edges, fixing perf issues caused by accessing graph state and weak references from views. 
Perf improvement is around 17% when duplicating nodes on the Humane graph.
> Reduced render cycles caused by edges

- Stitch/Graph/Node/View/StitchUIScrollView.swift
> Crash in debug if border-checking diff is too large

- Stitch/Graph/LayerInspector/GenericFlyoutView.swift
- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/LayerInspector/LayerInspectorView.swift
- Stitch/Graph/Node/Port/View/Field/NodeFieldsView.swift
- Stitch/Graph/Node/Port/View/Field/OutputValueView.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModel.swift
- Stitch/Graph/Node/View/CanvasLayerInputView.swift
Perf hangups from frequent updates to field view model publishers and passing in view builder functions into views.
> Reduced render cycles from fields

- Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift
- Stitch/Graph/Node/View/StitchUIScrollHelpers.swift
- Stitch/Graph/ViewModel/GraphUI.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7019
Node dupe-drag with media still feels a bit buggy?
> Reset node dupe-drag state when alerts reset or graph scrolled or zoomed

- Stitch.xcodeproj/project.pbxproj
- Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Stitch/Graph/Node/Eval/OperationEvaluationHelpers.swift
- Stitch/Graph/Node/Patch/Type/Math/ModNode.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModelNodeCalculatable.swift
Helps catch migration issues earlier
e.g. this PR required that we added a node type to existing Mod nodes: https://github.com/StitchDesign/Stitch/pull/951/files
> In debug mode, crash if eval produces empty outputs

- Stitch/Graph/Node/View/CanvasItemPositionHandler.swift
- Stitch/Graph/Node/View/NodeView.swift
- Stitch/Graph/Node/View/NodesOnlyView.swift
`usesPositionHandler` is no longer needed since changes to node insertion animation
> Remove `usesPositionHandler` since no longer used

- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/Node/Group/GroupNodeCreationActions.swift
- Stitch/Graph/Node/Port/Util/PulseActions.swift
- Stitch/Graph/Node/Port/View/Field/ValueButton/PulseValueButtonView.swift
- Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift
- Stitch/Graph/Node/Util/Movement/NodePositionUtils.swift
- Stitch/Graph/Node/Util/NodeCreatedAction.swift
- Stitch/Graph/Node/Util/NodeDeletedAction.swift
- Stitch/Graph/Node/View/NodeView.swift
- Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/TextField/PreviewTextFieldLayerUtils.swift
- Stitch/Graph/Sidebar/Util/JumpToCanvasItem.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupCreated.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift
- Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
- Stitch/Graph/Util/NodeSelection/NodeSelectionUtil.swift
- Stitch/Graph/ViewModel/GraphUI.swift
- StitchTests/nodeUIGroupingTests.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6781
Also cleans up a couple redundant methods. 
Note: also introduces clearer signature on logic for selecting and deselecting a canvas item. 
Previously this logic was a method on `CanvasItemViewModel` that took a full `GraphState`. However, such a signature misleadingly implied that selection-status was stored on the canvas item itself, like canvas item's z-index. We were also forced to retrieve the full canvas item view model in contexts where we only had, and only needed, the canvas item's id. 
The new signature `(GraphState, CanvasItemId) -> Void` makes clear that we're modifying (part of) GraphState and only need the canvas item id.
> Deselect other canvas items when canvas item's field focused

- Stitch/Graph/Node/View/StitchUIScrollView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7031
Previously we only looked at canvas items within the view port, but this creates situations e.g. where an edge indicates some off-screen node farther to the east that we cannot naturally scroll to since some other on-screen node counts as the border.
(Ideally we would use UIScrollview's natural 'bounce' behavior for border checking, but adjusting contentSize upon zoom was very, very buggy.)
> Check borders against all canvas items on traversal level, not just the visible ones

- Stitch/Graph/Node/Layer/Type/Text/TextFieldLayerNode.swift
- Stitch/Graph/Node/Patch/Type/Value/SplitterPatchNode.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7049
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7050
> Use identity eval for non-pulse and non-media splitters; start TextField layer output with empty string

- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/InputNodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/OutputNodeRowObserver.swift
Communicates:
1. what's that function is actually doing
2. that the function is only not actually generic (it's only for pulsed outputs)
> Rename OutputNodeRowObserver's `didValuesUpdate` to something more specific: `kickOffPulseReversalSideEffects`

- Stitch.xcodeproj/project.pbxproj
- Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Stitch/Graph/PrototypePreview/Frame/View/FullScreenPreviewViewWrapper.swift
Two changes
1. Main fix comes from StitchEngine where removing a mutating function cut down publishing from `NodeViewModel`
2. Smaller change which reduced render cycles in `FullScreenPreviewViewWrapper`
> Improved perf by reducing renders from outputs updating

- Stitch/Graph/Node/Eval/NodeEvaluationHelpers.swift
- Stitch/Graph/Node/Eval/PatchEvaluateExtensions.swift
- Stitch/Graph/Node/Model/Definition/PatchNodeDefinitionKinds.swift
- Stitch/Graph/Node/Patch/Type/Value/SplitterPatchNode.swift
- Stitch/Graph/Node/Patch/Type/WirelessBroadcasterNode.swift
- Stitch/Graph/Node/Patch/Type/WirelessReceiverNode.swift
- Stitch/Graph/Node/Patch/Util/PatchDefaultNodeExtensions.swift
Use node ephemeral state and media-aware identity eval with wireless nodes.
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7065
sample project: [Wireless pulse, media.stitch.zip](https://github.com/user-attachments/files/19540819/Wireless.pulse.media.stitch.zip)
> Media now properly flows across wireless nodes

- Stitch/App/View/Component/StitchButton.swift
- Stitch/App/View/ViewUtil/ViewUtils.swift
- Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift
- Stitch/Graph/Toolbar/View/TopBarButtonView.swift
- Stitch/Home/View/ProjectsHomeViewWrapper.swift
Changes:
1. Catalyst nav bar buttons used a Menu component to fix an issue where nav bar buttons don't have hover effects. That menu button used EmptyViews for its dropdown as to not show a menu. This hackiness, combined with the EmptyView, could be an issue.
2. Removed retain cycles in action closures for nav bar buttons.
> Attempted fix for disappearing Catalyst nav buttons

- Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift
An additional, conservative follow up to https://github.com/StitchDesign/Stitch/pull/967#issue-2944708064
As far as I know, we have not seen disappearing Catalyst nav bar buttons on the homescreen since the above PR, but this PR also reduces a potential variable.
If we see the Catalyst nav bar buttons disappear even after this, we may need to be more aggressive, e.g. remove Menu (at the cost of hover effects?) or introduce SceneDelegate ?
> In Catalyst nav bar buttons, use `.simultaneousGesture` instead of `UIKitOnTapModifier`'s `UIHostingController`

- Stitch/App/ViewModel/StitchStore.swift
- Stitch/Graph/PrototypePreview/Frame/View/FloatingWindowView.swift
- Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift
- Stitch/Graph/Util/GraphUIActions.swift
- Stitch/Graph/View/ContentView.swift
- Stitch/Graph/View/GraphBaseView.swift
- Stitch/Graph/View/ProjectNavigationView.swift
- Stitch/Graph/View/StitchProjectOverlayView.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
Closes https://github.com/StitchDesign/Stitch--Old/issues/6997
Closes https://github.com/StitchDesign/Stitch--Old/issues/6954
The issue was caused by the inspector subscribing to state existing in StitchDocumentViewModel. Clearly under the hood the inspector doesn't tear down completely when a project closes, even if that inspector is defined at a child view.
The fix was moving that boolean state to StitchStore.
> Fixed document retain cycles when closing projects

- Stitch/Graph/Edge/Util/PortActions.swift
- Stitch/Graph/Node/Component/StitchComponentViewModel.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift
- Stitch/Graph/Node/Port/Util/PortValue/CoercerUtils.swift
- Stitch/Graph/Node/Port/Util/PulseActions.swift
- Stitch/Graph/Node/Port/Util/TypeChange/NodeTypeChangedHelpers.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputUnpackedPortObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/InputNodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverPostProcessing.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverSchemaObserverIdentifiable.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/OutputNodeRowObserver.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModel.swift
- Stitch/Graph/ViewModel/GraphState.swift
- StitchTests/evalTests.swift
In the last 3-4 weeks we've solved several bugs that arose from lack of clarity around `didInputsUpdate` vs `setValuesInInput` vs `updateValues` etc.
- e.g. we made `setValuesInInput` update the values in the input already, thus breaking our post-processing logic (e.g. de-assigning a layer from an interaction patch node)
- e.g. we failed to have `updateValues` update the "refresh these UI fields" ports, thus breaking unpacked layers inputs
No one new coming to the codebase is going to understand `didInputsUpdate` vs `setValuesInInput` vs `updateValues` etc.
This PR takes a step toward simplifying our logic: we are always either updating an input or an output, and the differences between the two are clear:
- updating an input: coercing values, potentially updating interaction cache and …
> Specific update methods for inputs vs outputs

- Stitch/Graph/Node/Patch/Util/PatchNodeTypeExtensions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7063
Ideally we would use a submenu for 'rarer types,' but Picker does not support submenus (Menu does but does not support checkboxes).
> Hide rarely-used types in node type change menu

- Stitch/App/Serialization/DocumentLoading/DocumentEncodable.swift
- Stitch/App/Serialization/FileDropHandling.swift
- Stitch/App/Serialization/Util/File/StitchCustomURL.swift
- Stitch/App/Shortcut/ProjectsHomeCommands.swift
- Stitch/App/System/StitchSystemViewModel.swift
- Stitch/App/View/StitchRootModifier.swift
- Stitch/App/ViewModel/StitchStore.swift
- Stitch/Graph/Node/Component/StitchMasterComponent.swift
- Stitch/Graph/Node/Patch/Type/Value/SplitterPatchNode.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/GraphUI.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
- Stitch/Home/Util/ProjectCreatedActions.swift
- Stitch/Home/View/ProjectsHomeViewWrapper.swift
- StitchTests/nodeUIGroupingTests.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6581
This was very hard to debug: in the test we were silently failing (returning nil) on some code that worked on actual device.
The test-created stitch document view model did not, and still does not, have the proper encoder delegate. 
For now, in test contexts, we allow the encoder delegate's rootURL to be nil.
> Fix group node duplication test; better name for createProject fn that was actually doing a side-effect

- Stitch/Graph/Node/Util/NodeKindUtils.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SidebarListLabelView.swift
- Stitch/Graph/Sidebar/ViewModel/SidebarItemGestureViewModel.swift
- Stitch/Graph/Sidebar/ViewModel/SidebarItemSwipable.swift
- Stitch/Graph/ViewModel/GraphState.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7076
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7078
> Update layer dropdown choices after sidebar name edit; do not revert to layer's full name when sidebar item string is empty

- Stitch.xcodeproj/project.pbxproj
- Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Stitch/Graph/Edge/Util/PortActions.swift
- Stitch/Graph/Node/Layer/Type/Media/3DModelLayerNode/Nodes/Model3DLayerNode.swift
- Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift
- Stitch/Graph/Node/Patch/Type/Loop/LoopBuilder.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModelNodeCalculatable.swift
- Stitch/Graph/PrototypePreview/Layer/View/GeneratePreview.swift
- Stitch/Graph/PrototypePreview/Layer/ViewModel/LayerViewModel.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6992.
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7068
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7067
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6992
This PR fixes issues caused by recent media handling changes, which used to correctly obtain media by traversing upstream nodes. That implementation changed in favor of a system that holds media locally at each node, which jeopardized media looping for layer nodes.
The new media handling approach has StitchEngine handling media at hoseflow. To fix the layer media looping, logic has moved from StitchEngine to its client for handling some media events. This was needed to enable `LayerNodeViewModel` to hold upstream media, and then …
> Media looping fixes

- Stitch/Graph/LayerInspector/ColorFlyoutView.swift
- Stitch/Graph/LayerInspector/GenericFlyoutView.swift
- Stitch/Graph/LayerInspector/LayerInspector3DTransformInputView.swift
- Stitch/Graph/LayerInspector/LayerInspectorGridInputView.swift
- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/Node/Port/Util/Field/TabKeyPressActions.swift
- Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift
- Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerView.swift
- Stitch/Graph/Node/Port/View/Field/NodeFieldsView.swift
- Stitch/Graph/Node/Port/View/Field/OutputValueView.swift
- Stitch/Graph/Node/Port/ViewModel/FieldGroupTypeData.swift
- Stitch/Graph/Node/Port/ViewModel/FieldViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/InputNodeRowViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/OutputNodeRowViewModel.swift
Our field view model was generic because of the row view model delegate, which turned out to be redundant: we only needed the port type (for `FieldViewModel.fieldLabelIndex`) which was already available on the field coordinate's rowId.
A safe change, just following the compiler. 
QA'd by opening demo projects and interacting with them.
> Non-generic FieldViewModel

- Stitch/Graph/Node/Port/Model/PortValue/Type/Anchoring/Anchoring.swift
- Stitch/Graph/PrototypePreview/Frame/View/PreviewWindowElementUIKitGestures.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/HoverGestureModifier.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/LayerSizeReader.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PinningUtils.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewAbsoluteShapeLayerModifier.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonModifierWithoutFrame.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonPositionModifier.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewWindowCoordinateSpaceReader.swift
- Stitch/Graph/PrototypePreview/Layer/View/GeneratePreview.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewGroup.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewHitAreaLayer.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/PreviewShapeLayer.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6370
Main change: we place layers in preview window via `.offset` instead of `.position`. This had a couple domino effects, e.g. `.contentShape`'s placement.
> ZStack `hug` now properly hugs children

- Stitch/Graph/Node/Patch/Type/Media/MicrophoneFeedNode.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Models/StitchMediaObject.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Sound/SoundHelpers.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Sound/StitchAudio.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Sound/StitchMicrophone.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/ObjectTypes/Sound/StitchSoundFile.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/6983
Issue here being requesting "play and record" after "play" was already established. Solution is to make all requests "play and record" since it's unclear if changing the permissions type is even possible.
> Fixed crashes from simultaneous mic + sound player nodes

- Stitch/Home/View/ProjectsHomeViewWrapper.swift
Super interesting. I can’t reproduce the 'disappearing homescreen buttons on app first open' locally — regardless of Menu vs Button, big vs small screen resolution, dev debug vs release build.
Only consistent repro is on the TF itself. (Latest TF is from this morning.)
We’ll see what Button in the Catalyst nav bar homescreen does in the next TF that goes out.
> Try Button in Catalyst homescreen nav bar for next TestFlight

- Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift
- Stitch/Graph/Node/View/CanvasItemPositionHandler.swift
- Stitch/Graph/Node/View/NodeView.swift
- Stitch/Graph/Node/View/StitchUIScrollHelpers.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/GraphUI.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7099.
Offending commit causing regression is unknown, however some opportunities here to use more gesture events like `began` that allow us to clean up logic and fix the option + drag issues.
> Fixed option + drag node regression

- Stitch/Graph/CommentBox/Util/CommentBoxGestureActions.swift
- Stitch/Graph/Node/Patch/Type/ARRaycastingNode.swift
- Stitch/Graph/Node/Patch/Type/ConvertPositionNode.swift
- Stitch/Graph/Node/Patch/Type/Interaction/Keyboard/KeyboardNode.swift
- Stitch/Graph/PrototypePreview/Layer/Util/LayerDragEndedActions.swift
- Stitch/Graph/PrototypePreview/Layer/Util/LayerDraggedActions.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PinningUtils.swift
- Stitch/Graph/Sidebar/Util/Gesture/LegacySidebarActions.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemGestureRecognizerView.swift
- Stitch/Graph/ViewModel/GraphDelegate.swift
What does it mean if `documentDelegate` is nil? 
We can't have key press state or preview window size if we don't have a project loaded. 
What does providing `.zero` for a preview window size even mean? 
What scenario does that cover?
> Remove several non-sense GraphState methods that accessed Document in a type-unclear way

- Stitch/App/Model/AppState.swift
- Stitch/App/Model/ProjectAlertState.swift
- Stitch/App/Serialization/Util/File/StitchDocumentUtil.swift
- Stitch/App/Util/Action/HandleStitchAction.swift
- Stitch/App/View/StitchNavStack.swift
- Stitch/App/ViewModel/StitchStore.swift
- Stitch/Graph/CommentBox/Util/CommentBoxDataUtils.swift
- Stitch/Graph/CommentBox/Util/CommentBoxGestureActions.swift
- Stitch/Graph/CommentBox/ViewModel/CommentBoxViewModel.swift
- Stitch/Graph/Node/Component/ComponentNavBarView.swift
- Stitch/Graph/Node/Component/StitchComponentViewModel.swift
- Stitch/Graph/Node/Model/GraphCopyable.swift
- Stitch/Graph/Node/Util/NodeDeletedAction.swift
- Stitch/Graph/PrototypePreview/Frame/View/FloatingWindowView.swift
- Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
- Stitch/Graph/View/ProjectToolbar.swift
- Stitch/Graph/ViewModel/GraphDelegate.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/HomescreenProjectSelectionState.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
- Stitch/Home/Util/ProjectDestructiveActions.swift
- Stitch/Home/View/ProjectItem/ProjectsListItemView.swift
- Stitch/Home/View/ProjectsHomeView.swift
- StitchTests/TestUtils/MockFileManager.swift
- StitchTests/TestUtils/TestStateUtils.swift
In the past when we have switched a method from `extension NodeViewModel` to `extension GraphState` (or vice-versa), we introduced bugs wherever a `self.id` was not updated to be e.g. `graph.id` or `node.id`; 
e.g. we ended up trying to retrieve some part of the node view model using a graph id!
Example from this refactor: we had made comment box methods on `extension StitchDocument` and were referencing `id` i.e. `self.id` when trying to retrieve a comment box. This is total non-sense. 
Type-safe identifiers make these mistakes impossible.
Longer explanation: https://www.rea-group.com/about-us/news-and-insights/blog/the-abject-failure-of-weak-typing/
> Use type-safe IDs for Graph, CommentBox

- Stitch/Graph/Node/Patch/Type/Shape/LayerInfoNode.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemSwipeView.swift
Tagging https://github.com/StitchDesign/Stitch--Old/issues/7111 which sees some improvement.
Fixes:
1. Using `.nodes` instead of `.patchNodes` removes an unnecessary filtering check for nodes. Unnecessary because logic already filters for patches.
2. Reduces render cycles caused by layer highlighting.
> Minor perf improvements for layer scenarios

- Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingViewReadOnly.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SidebarListLabelView.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemSwipeInnerView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7106
https://github.com/user-attachments/assets/1853dca7-0fcd-4d8d-a979-89c314ce11f9
> Visually indicate actively edited sidebar name; defocus redux field in sidebar item selected

- Stitch/App/View/StitchRootView.swift
- Stitch/Graph/LayerInspector/FlyoutUtils.swift
- Stitch/Graph/View/ContentView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7097
TextField still broken on Catalyst: repeated char entry after deleting a char. 
Improvement on our alternative: 
https://github.com/user-attachments/assets/402c136d-92b8-46a1-ab67-073258348a6d
> Better placement of project title edit view on Catalyst

- Stitch/Graph/CommentBox/Util/CommentBoxActions.swift
- Stitch/Graph/CommentBox/Util/CommentBoxGestureActions.swift
- Stitch/Graph/Edge/Util/EdgeEditingActions.swift
- Stitch/Graph/Edge/View/EditMode/EdgeEditModeOutputHoverView.swift
- Stitch/Graph/Gesture/Util/GraphUICursorSelectionActions.swift
- Stitch/Graph/Gesture/Util/GraphUIScrollActions.swift
- Stitch/Graph/Node/Patch/Type/DeviceInfoNode.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift
- Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift
- Stitch/Graph/Node/Util/NodeDeletedAction.swift
- Stitch/Graph/Node/View/CanvasItemPositionHandler.swift
- Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
- Stitch/Graph/ViewModel/GraphDelegate.swift
- Stitch/Graph/ViewModel/GraphUI.swift
This accessor method was convenient but total nonsense: graph movement lives on the document, not graph state, and if we don't have a document then we cannot access graph movement. 
Do not give representation to illegal state.
> Access `GraphMovement` directly `Document`, not indirectly via `GraphState`

- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
- StitchTests/TestUtils/TestUtils.swift
- StitchTests/nodeTypeTests.swift
Fixes test crash.
All tests pass now.
> Do not crash if we're missing store and/or document encoder when encoding project

- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/Node/Port/View/Field/WirelessPortView.swift
- Stitch/Graph/Node/Port/View/LayerInspectorRowButton.swift
- Stitch/Graph/Node/View/NodeTag/NodeTagMenuButtonsView.swift
- Stitch/Graph/Node/View/NodeView.swift
- Stitch/Graph/Sidebar/Util/JumpToCanvasItem.swift
- Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift
- Stitch/Graph/Toolbar/View/TopBarButtonView.swift
- Stitch/Graph/View/ProjectToolbar.swift
Actions are a way to kickoff a state change from a view without having to pass down the entire relevant state to that view.
Defining an action can admittedly be a pain (requires writing a couple more lines of code); but passing down more state than necessary to a view makes the view's dependencies unclear -- e.g. was `WirelessPortView` actually relying on graph state and document for its UI, or was that just for the state change?
Actions let us separate view deps from state changes.
We also opened more opportunities for mistakes -- supposed we had not marked `graph` and `document` as `weak`? Would we have potentially introduced a retain cycle?
> Don't pass down Document and Graph just to kickoff state changes from the UI

- Stitch/App/Model/ProjectAlertState.swift
- Stitch/App/Serialization/StitchFileManagerProject.swift
- Stitch/App/Util/URL/URLExtensionUtils.swift
- Stitch/Graph/Menu/FileImportView.swift
- Stitch/Graph/Node/Layer/Util/LayerUtils.swift
- Stitch/Graph/Node/Patch/Type/Loop/LoopBuilder.swift
- Stitch/Graph/Node/Patch/Util/PatchUtils.swift
- Stitch/Graph/Node/Port/Model/Field/FieldValueMedia.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Import/SupportedMediaFormat.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaConstants.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaKeyUtils.swift
- Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift
- Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerValueEntry.swift
- Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/PickerValueEntry.swift
- Stitch/Graph/Node/Util/NodeKindUtils.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7121
Loop builder and Splitter nodes needed support for handling any media type for import. Some new logic in our code was needed for supporting all media types, vs. a single media type as needed for most nodes.
> Fixed media import support for loop builder

- Stitch/Graph/Node/Patch/Type/Loop/LoopBuilder.swift
- Stitch/Graph/Node/Patch/Type/Media/ImageNode.swift
Completing the job started by #1049
Problem here being we needed logic to create a media object if source media was added directly.
Also fixed here is image import eval unnecessarily changing the `.id` property on media—this ID should remain static for the source media.
> Fixed direct media imports on Loop Builder

- Stitch/Graph/Node/Layer/Type/Media/VideoLayerNode.swift
- Stitch/Graph/Node/Layer/Type/Media/VisualMedia.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7122
Removing sizing scenario inputs for image + video layers as there's no support currently and non-trivial to do at this moment.
> Removed sizing scenario inputs for visual media layers

- Stitch.xcodeproj/project.pbxproj
- Stitch/Graph/Edge/Util/EdgeEditingActions.swift
- Stitch/Graph/Gesture/View/UpdateVisibleNodes.swift
- Stitch/Graph/LayerInspector/LayerInspectorActions.swift
- Stitch/Graph/Node/Group/GroupNodeCreationActions.swift
- Stitch/Graph/Node/Group/GroupNodeDestructionActions.swift
- Stitch/Graph/Node/Patch/Type/Value/SplitterTypeActions.swift
- Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
- Stitch/Graph/Node/Util/NodeCreatedAction.swift
- Stitch/Graph/Node/Util/NodeDeletedAction.swift
- Stitch/Graph/Node/View/StitchUIScrollHelpers.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupUncreated.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarListItemSelectionActions.swift
- Stitch/Graph/Sidebar/ViewModel/SidebarItemGestureViewModel.swift
- Stitch/Graph/Util/GraphUIActions.swift
- Stitch/Graph/Util/NodeSelection/CopyAndPasteNodesActions.swift
- Stitch/Graph/View/InfiniteCanvas.swift
- Stitch/Graph/View/ProjectNavigationView.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/Readers.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
- StitchTests/evalTests.swift
- StitchTests/loopTests.swift
- StitchTests/nodeUIGroupingTests.swift
Was unclear if `updateGraphData` could be called without a document; by using proper function parameters, we can see it can't.
Also renamed `updateVisibleNodes` to be a little more clear what's going: it's really only for a visible graph, and for canvas items.
QA'd on Humane demo. 
All tests pass after some finagling so that the StitchStore lives long enough and the documentEncoderDelegate references don't die. Hat tip Elliot.
> Pass document to `updateGraphData`, update tests

- Stitch/App/Serialization/DocumentEncodableUtil.swift
- Stitch/App/Serialization/DocumentLoading/DocumentLoader.swift
- Stitch/App/Serialization/StitchFileManagerProject.swift
- Stitch/Graph/Node/Component/StitchComponentViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModelType.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
- Stitch/Home/Util/ProjectCreatedActions.swift
- StitchTests/evalTests.swift
- StitchTests/loopTests.swift
- StitchTests/nodeTypeTests.swift
Given where/how `DocumentLoader.getDecodedFiles` is called, seems fine to do it on the MainActor.
The only remaining `async` is because of a cross actor update (MainActor vs DocumentLoader actor) in the createNewProject function. That logic is isolated now; we can compose these functions, which let me use less asynchronous logic in the tests.
QA'd on Humane and creating new project.
All tests pass.
> Use synchronous initializers for GraphState and StitchDocumentViewModel

- Stitch/Graph/Node/Component/StitchComponentViewModel.swift
- Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
- Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift
- Stitch/Graph/Node/Patch/ViewModel/PatchNodeViewModel.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaActions.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/InputNodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverPostProcessing.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverSchemaObserverIdentifiable.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/OutputNodeRowObserver.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModelType.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/Node/StitchAINodeUtils.swift
- Stitch/Graph/ViewModel/GraphState.swift
In most contexts we had the node immediately available; in others, we actually just needed e.g. the `GraphState`.
> Reduce usage of `NodeRowObserver.nodeDelegate`

- Stitch/Graph/LayerInspector/GenericFlyoutView.swift
- Stitch/Graph/LayerInspector/LayerInspectorActions.swift
- Stitch/Graph/Node/Component/StitchComponentViewModel.swift
- Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
- Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift
- Stitch/Graph/Node/Model/SchemaNodesUtil.swift
- Stitch/Graph/Node/Patch/ViewModel/PatchNodeViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModel.swift
- Stitch/Graph/Node/Util/NodeDeletedAction.swift
- Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModelType.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
We were passing two parameters to `syncRowViewModels` that weren't even being used. Now the signature and code is much cleaner. 
Also fixes runtime crash from `39bdf7de7599d7b7a2e6fd2dac089ee661174509`
> Cleaner signature for `syncRowViewModels`; fix runtime crash

- Stitch/App/Serialization/DocumentEncodableUtil.swift
- Stitch/App/Serialization/DocumentLoading/DocumentLoader.swift
- Stitch/App/Serialization/StitchFileManagerProject.swift
- Stitch/Graph/Node/Component/StitchComponentViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModelType.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
- Stitch/Home/Util/ProjectCreatedActions.swift
- StitchTests/evalTests.swift
- StitchTests/loopTests.swift
- StitchTests/nodeTypeTests.swift
Reverts StitchDesign/Stitch#1058
https://github.com/StitchDesign/Stitch/pull/1058/files
This commit clearly broke project import e.g. of the Humane demo. Not sure why -- it appeared from the compiler that we were only async in part of the function because we crossed actors (Main vs DocumentLoader). 
Low priority, but would love to understand why and how this broke things without compiler properly warning us. Maybe have to go through the original PR's changes line-by-line.
Would love to have a sync-option for creating a new document (e.g. for tests, for in the Xcode previews). Project import can still be asynchronous since we're reading from the file system.
> Revert "Use synchronous initializers for GraphState and StitchDocumentViewModel"

- Stitch.xcodeproj/project.pbxproj
- Stitch/App/Serialization/DocumentLoading/DocumentLoader.swift
- Stitch/App/Serialization/DocumentLoading/SynchronousDocumentViewModelInitializer.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
- Stitch/Home/Util/ProjectCreatedActions.swift
- Stitch/Home/View/ProjectItem/ProjectsListItemLoadedView.swift
- Stitch/Home/View/ProjectItem/ProjectsListItemView.swift
- StitchTests/evalTests.swift
- StitchTests/loopTests.swift
- StitchTests/nodeTypeTests.swift
- StitchTests/nodeUIGroupingTests.swift
Attempt to introduce a sync init for document (at least for tests); ignores DocumentLoader actor. 
All tests pass.
Related to https://github.com/StitchDesign/Stitch--Old/issues/7134
> Introduce sync init for document

- Stitch/Graph/Node/Component/StitchComponentViewModel.swift
- Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
- Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift
- Stitch/Graph/Node/Model/SchemaNodesUtil.swift
- Stitch/Graph/Node/Patch/ViewModel/PatchNodeViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/InputNodeRowViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/OutputNodeRowViewModel.swift
- Stitch/Graph/Node/Title/View/MathExpressionSubmenuButtonView.swift
- Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModelType.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
A row view model is a ui-data cache for an underlying row observer. The row VM's activeValue reflects the row observer's, so long as the row VM is "visible" (= on screen).
Initializing with `activeValue: PortValue = number(0)` was just nonsense, e.g. row observer with color type could never have number type row VM.
> Require PortValue when creating row view model from row observer; don't initialize with nonsense default

- Stitch/App/Util/TypeExtension/StringUtils.swift
- Stitch/Graph/Node/Patch/Type/Text/TextTrimNode.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7129
> Fix TrimText crash and inaccuracy; leverage native Swift prefix method

- Stitch/Graph/PrototypePreview/Frame/View/PreviewWindowElementUIKitGestures.swift
- Stitch/Graph/PrototypePreview/Layer/Util/LayerDragEndedActions.swift
- Stitch/Graph/PrototypePreview/Layer/View/CommonModifier/PreviewCommonModifierWithoutFrame.swift
Press interaction node could get stuck as press down if some change causes the interactive view to get recreated. In my scenario, a group orientation change when triggered by gesture changes creates this race condition.
The fix is using an `onDisappear` view modifier to trigger drag ended helpers.
> Fixes drag gesture reset if group orientation changes

- Stitch/Graph/PrototypePreview/Layer/Model/PreviewGridData.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/CanvasSketchView.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/TextField/PreviewTextFieldLayerUtils.swift
- Stitch/Graph/Sidebar/Util/Gesture/SidebarListItemActions.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupCreated.swift
- Stitch/Graph/Sidebar/Util/SidebarIcons.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemGestureRecognizerView.swift
- Stitch/Graph/ViewModel/GraphState.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7135
We're also smarter about where and how we require a LayerNode not just a Node.
> Show hide or unhide option according to visibility status of selected sidebar layers

- Stitch.xcodeproj/project.pbxproj
- Stitch/Graph/Edge/Model/EdgeEditingState.swift
- Stitch/Graph/Edge/Model/PortEdgeUI.swift
- Stitch/Graph/Edge/Model/PortIdAddress.swift
- Stitch/Graph/Edge/Util/EdgeEditingActions.swift
- Stitch/Graph/Edge/Util/PortActions.swift
- Stitch/Graph/Edge/Util/PortDragActions.swift
- Stitch/Graph/Edge/View/EditMode/EdgeEditModeOutputHoverView.swift
- Stitch/Graph/Edge/View/PossibleEdgesView.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/InputNodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverCachedViewDataExtensions.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/OutputNodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/InputNodeRowViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/OutputNodeRowViewModel.swift
- Stitch/Graph/ViewModel/GraphState.swift
QA'd on Humane, Obscured-Squares demos.
> Remove unused `var connectedNodes` from input and output observers; renamed `PortViewData` to `PortIdAddress`

- Stitch/Graph/Node/Port/View/Field/InputView/DropDownChoiceView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7128
https://github.com/user-attachments/assets/d3f0fd47-2b37-4500-b4e7-2665f40212ea
> Explicitly set width on DropDownChoiceView's label, guaranteeing  enough space for longer options if even we started with shorter option

- Stitch/Graph/Edge/Util/EdgeUtils.swift
- Stitch/Graph/Edge/Util/PortActions.swift
- Stitch/Graph/Edge/Util/PortDragActions.swift
- Stitch/Graph/Node/Patch/Type/Value/SplitterTypeActions.swift
- Stitch/Graph/Node/Patch/Util/WirelessReceiver.swift
- Stitch/Graph/Node/Port/Util/PortValue/UnpackedValueCoercer.swift
- Stitch/Graph/Node/Port/View/PortView.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/OutputNodeRowViewModel.swift
- Stitch/Graph/ViewModel/GraphReaders.swift
Also made it a little clearer what data input and output port drags rely on. Really, we're just using the protocol methods on row view model so we can have the specific input vs output port drag while keeping the UI input vs output agnostic.
> Remove some unused `isVisible` parameter for removing connections; portIsDragging is now local view state

- Stitch/Graph/Node/Port/Model/PortValue/Type/Media/Utils/MediaConstants.swift
- Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerValueEntry.swift
- Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/ReadOnlyEntry.swift
> Explicit min and max width for non-inspector media picker labels

- Stitch/Graph/Node/Port/View/Field/InputView/DropDownChoiceView.swift
- Stitch/Graph/Node/Port/View/Field/ValueButton/StitchColorPicker/StitchColorPickerView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7157
https://github.com/user-attachments/assets/368fe219-0891-45a6-9260-d15714a33307
> Right-align dropdown labels in inspector; use nil-image background to better show translucent colors in color picker

- Stitch.xcodeproj/project.pbxproj
- Stitch/Graph/LayerInspector/GenericFlyoutView.swift
- Stitch/Graph/LayerInspector/LayerInspectorActions.swift
- Stitch/Graph/Node/Component/StitchComponentViewModel.swift
- Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
- Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift
- Stitch/Graph/Node/Patch/ViewModel/PatchNodeViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/InputNodeRowViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/InputPortUIData.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/OutputNodeRowViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/OutputPortUIData.swift
- Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModelType.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
Introduce standalone type for row view model port data.
Seems like row view model has two main uses:
1. cached field ui values (relevant for both canvas and inspector)
2. port ui data (canvas only)
In some contexts I'm noticing that I probably only need the port ui data (and maybe some fact about the row observer), not the whole row view model.
> Standalone type for a row view model's port data

- Stitch.xcodeproj/project.pbxproj
- Stitch/Graph/Edge/Model/ConnectedEdgeData.swift
- Stitch/Graph/Edge/Model/EdgeAnchorData.swift
- Stitch/Graph/Edge/Util/PortDragActions.swift
- Stitch/Graph/Edge/View/EdgeDrawingView.swift
- Stitch/Graph/Edge/View/ExistingEdgesView.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/InputNodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/OutputNodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/GraphItemType.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/InputNodeRowViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/InputPortUIViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/OutputNodeRowViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/OutputPortUIViewModel.swift
- Stitch/Graph/ViewModel/GraphState.swift
Most of our edge-view logic only needs facts about the port UI, not the cached field UI etc. So, where possible, we pass just that port UI data, not the full row view model.
Follow up to https://github.com/StitchDesign/Stitch/pull/1112, showing how to use more specific data.
QA'd on Humane demo and small project with a group node in which I tested creating, updating and deleting edges.
> Prefer port UI view model (rather than node row view model) when that's all we need

- Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerValueEntry.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7168
> Single width for media picker label, since None vs media caused noticeable node width change

- Stitch/Graph/Node/Eval/LoopedEval.swift
- Stitch/Graph/Node/Patch/Type/Value/SplitterPatchNode.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModelNodeCalculatable.swift
Logic was missing for extending/removing ephemeral observers specifically for looped inputs. Fixes issues surrounding loop builder media or any other occasion where media can be created into a loop.
> Fixed media input looping regressions

- Stitch.xcodeproj/project.pbxproj
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverSchemaObserverIdentifiable.swift
- StitchTests/GraphTests.swift
Added test since we missed this during QA and the regression has been around ~2 weeks.
https://github.com/user-attachments/assets/d1682802-bbd3-4796-9196-2cc5e57f8b83
> Wipe outputs when graph reset; add test

- Stitch/Graph/LayerInspector/LayerInspectorView.swift
last input row is no longer so close to the bottom, gives us a little more room to breathe
> Padding on bottom of inspector

- Stitch/Graph/Node/Model/RowData/LayerInputType.swift
Apparently we did not need `ReferenceWritableKeyPath`  for layerNodeKeyPath ?
No compiler complaints.
QA'd on Humane demo, Circular Text demo.
> Use `KeyPath` instead of `ReferenceWritableKeyPath`  for layerNodeKeyPath

- Stitch/Graph/LayerInspector/GenericFlyoutView.swift
- Stitch/Graph/LayerInspector/LayerInspectorActions.swift
- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
- Stitch/Graph/Node/Model/RowData/LayerInputType.swift
- Stitch/Graph/Node/Port/View/LayerInspectorRowButton.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepTypeAction.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7187
Also cleans up some code:
- make explicit that AddLayerInput assumes packed mode
- when adding a field to the canvas, do not create a CanvasNodeEntity but rather create the CanvasItemViewModel directly
https://github.com/user-attachments/assets/b10a265f-fd2d-4eb2-90b2-882547e53b49
> Do not add whole input to canvas if one field already on canvas

- Stitch/Graph/GraphStep/GraphStepIncrementer.swift
- Stitch/Graph/LayerInspector/GenericFlyoutView.swift
- Stitch/Graph/LayerInspector/LayerInspectorActions.swift
- Stitch/Graph/LayerInspector/LayerInspectorGridInputView.swift
- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/LayerInspector/OpenFlyoutView.swift
- Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
- Stitch/Graph/Node/Port/Model/Field/FieldValueMedia.swift
- Stitch/Graph/Node/Port/Util/Field/FieldValueUtils.swift
- Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift
- Stitch/Graph/Node/Port/View/PortValuesPreview/PortValuesPreviewView.swift
- Stitch/Graph/Node/Port/ViewModel/FieldGroup.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModel.swift
- Stitch/Graph/Node/View/CanvasLayerInputView.swift
- Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModel.swift
more cleanup and simplifications
QA'd on Humane demo.
> Reduce usage of _packed; keep NodeId on LayerInputObserver

- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
- Stitch/Graph/PrototypePreview/Layer/ViewModel/LayerViewModel.swift
Remaining direct accesses of _packedData are for updates (delegates, schema-syncing).
> LayerInputObserver: prefer `packedRowObserver` API to accessing `_packedData` directly

- Stitch.xcodeproj/project.pbxproj
- Stitch/Graph/LayerInspector/ColorFlyoutView.swift
- Stitch/Graph/LayerInspector/FlyoutHeader.swift
- Stitch/Graph/LayerInspector/GenericFlyoutView.swift
- Stitch/Graph/LayerInspector/LayerInspector3DTransformInputView.swift
- Stitch/Graph/LayerInspector/LayerInspectorGridInputView.swift
- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/LayerInspector/LayerInspectorView.swift
- Stitch/Graph/LayerInspector/ShadowFlyoutView.swift
- Stitch/Graph/Node/Port/View/Field/InputValueEntry.swift
- Stitch/Graph/Node/Port/View/Field/InputView/MediaPickerView.swift
- Stitch/Graph/Node/Port/View/Field/OutputValueView.swift
- Stitch/Graph/Node/Port/View/LayerInspectorRowButton.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
- Stitch/Graph/Node/View/NodeView.swift
- Stitch/Graph/Node/View/NodeViewType.swift
GenericFlyoutView no longer relies on _packedData, just field observers etc.
QA video, especially for the tricky case of inspector row and fly-out for packed 3D transform input: 
https://github.com/user-attachments/assets/8d0fa669-bf01-4db1-b54e-d675e00642a1
> `GenericFlyoutView` no longer relies on `_packedData`

- Stitch/Graph/Menu/NumberAdjustmentBar/AdjustmentBarPopoverView.swift
- Stitch/Graph/Menu/NumberAdjustmentBar/WideAdjustmentBarView.swift
- Stitch/Graph/Node/Port/Util/Field/FieldValueUtils.swift
- Stitch/Graph/Node/Port/Util/InputEdit/InputCommittedActions.swift
- Stitch/Graph/Node/Port/Util/InputEdit/InputEditedActions.swift
- Stitch/Graph/Node/Port/View/Field/InputView/CommonEditingView.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7137
This PR does two things:
1. Making the bug impossible by applying a true condition: user manual input edit/commit now always update the fields UI, whether value changed or not
2. Catches the bug next time it occurs: dev debug crash if user edit's value and input's existing value were 'same' but have differing fields UI (canvas only, since there's some trickiness with )
> Always update fields UI on user edit; catch next time fields-UI discrepancy happens in debug

- Stitch/Graph/Node/View/NodesOnlyView.swift
- Stitch/Graph/Util/GraphUIActions.swift
Improves: https://github.com/StitchDesign/Stitch--Old/issues/7179
https://github.com/user-attachments/assets/c22d0a64-834a-405d-ba90-e3c2971ff680
> When active index changes, only update port views of on-screen nodes at current traversal level

- Stitch/Graph/Node/Patch/Type/Loop/LoopBuilder.swift
- Stitch/Graph/Node/Patch/Type/Loop/LoopInsert.swift
- Stitch/Graph/Node/Patch/Type/Loop/LoopRemoveNode.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModelNodeCalculatable.swift
Adds media support for both along with broader fixes for Loop Remove node. We now have mostly shared code between both nodes' evals.
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7176
> Fixes for Loop Insert/Remove nodes

- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepTypeAction.swift
we were hitting setting layer input logic when we were on a node that is a layer input, which lead to errors like this:
> only parse a layer input if we are on a layer node

- Stitch/Graph/Edge/Util/EdgeUtils.swift
- Stitch/Graph/Edge/Util/PortDragActions.swift
- Stitch/Graph/Edge/View/DrawnEdge.swift
- Stitch/Graph/Edge/View/EdgeDrawingView.swift
- Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
- Stitch/Graph/Node/Port/View/PortView.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/PortUIViewModel/OutputPortUIViewModel.swift
- Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift
- Stitch/Graph/ViewModel/GraphState.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7197
Resolves https://github.com/StitchDesign/Stitch--Old/issues/5974
This PR resolves all our existing port/edge (non-edge-edit mode) animation issues. No more slivers/cuticles lagging behind during an output drag, etc.
Note: in `calculatePortColor`, how did the compiler allow a `NodeIOCoordinate == NodeRowViewModelId` check? Are we implementing a weird `Identifiable` or `Equatable` somewhere on one or both of those  ?
https://github.com/user-attachments/assets/cad64fab-8a9e-4a9c-a02b-8692d6d79e7c
> Fix all non-edge-edit-mode edge animation issues

- Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift
Addresses two problems:
1.  issues with generating LLM training data (edges and positions inaccurate, can't create new edge etc.; super jumpy)
2. sizes were also not very correct and relying on a 0.2 sec delay was silly
For (1), we still have 'flashes' when e.g. add or remove an edge while creating LLM training data.
For (2), we can probably get away with a manual static printing of `patch -> node type -> size (but especially width)` (@narner's idea, sounds good imo)
> Reverting side effect positioning of LLM-generated nodes

- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7200
> Proper z-indexing on HStack of a layer-input-on-canvas's fields

- Stitch/Graph/Node/Eval/LoopedEval.swift
- Stitch/Graph/Node/Patch/Type/Pulse/CounterNode.swift
- Stitch/Graph/Node/Patch/Type/Pulse/RepeatingPulsePatchNode.swift
- Stitch/Graph/Node/Patch/Type/Pulse/SwitchNode.swift
Issue was caused by reliance on actual outputs, which weren't getting reset on prototype restart. Instead, computed node state gets reset. We now read from computed node state.
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7208.
> Fixed Repeating Pulse node after prototype restart

- Stitch/Graph/Node/Patch/Type/Animation/spring+and+pop+animations/SpringHelpers.swift
- Stitch/Graph/Node/Port/Model/PortValue/Type/Animation/ClassicAnimation/ClassicAnimationCurve.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7160
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7095
Given some of our classic animation assumptions (e.g. frame rate, completion difference epsilon), some curves' animations can continue indefinitely at durations < 0.1. 
As a workaround, we'll treat duration < 0.1 animations are completing when we've run the expected duration rather than reached some epsilon.
> Complete classic animation with duration < 0.1 when duration completes

- Stitch/App/Shortcut/ProjectsHomeCommands.swift
https://github.com/user-attachments/assets/df557005-c1aa-4576-af74-ac6cb0ec9349
> When inside a project, CMD+N creates new project instead opening node menu

- Stitch/Graph/Node/Eval/AnimationEvaluationHelpers.swift
- Stitch/Graph/Node/Eval/AsyncMediaImpureEvalResult.swift
- Stitch/Graph/Node/Eval/EphemeralObserver/NodeEphemeralObservable.swift
- Stitch/Graph/Node/Eval/LoopedEval.swift
- Stitch/Graph/Node/Eval/MediaEvalOpObservable.swift
- Stitch/Graph/Node/Patch/Type/Media/SoundImportNode.swift
- Stitch/Graph/Node/Patch/Type/Pulse/CounterNode.swift
- Stitch/Graph/Node/Patch/Type/Pulse/PulseOnChangeNode.swift
- Stitch/Graph/Node/Patch/Type/Pulse/SwitchNode.swift
- Stitch/Graph/Node/Port/Util/PortValue/PortValuesUtils.swift
- Stitch/Graph/Node/Util/NodeMediaUtils.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7220
Issue here being the eval needs to rely on ephemeral state rather than outputs, which don't get directly reset on prototype restart.
Some extra work is done here to start support generic usage of node's which rely on previous values so that we can reuse implementation for other nodes.
> Fixed prototype restart for sound import node

- Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/CanvasCommonEditingView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/InputFieldBackgroundView.swift
- Stitch/Graph/Node/Port/View/Field/InputView/ReadOnlyEntry.swift
- Stitch/Graph/Node/Port/View/Field/InputView/TapToEditTextView.swift
- Stitch/Graph/Node/Port/View/Field/OutputFieldValueView.swift
- Stitch/Graph/Node/View/CanvasItemSelectedViewModifier.swift
- Stitch/Graph/Node/View/NodeView.swift
- Stitch/Graph/Node/View/NodeViewType.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7198
Still needs some love for:
1. when last field extends past end of node and goes against similar-color background
2. differentiating output field hover to see more value vs hovering output for edge edit mode
> Support extended view on outputs

- Stitch.xcodeproj/project.pbxproj
- Stitch/Graph/Edge/Util/EdgeEditingActions.swift
- Stitch/Graph/LayerInspector/GenericFlyoutView.swift
- Stitch/Graph/LayerInspector/LayerInspectorActions.swift
- Stitch/Graph/Node/Component/StitchComponentViewModel.swift
- Stitch/Graph/Node/Layer/Model/LayerNodeData.swift
- Stitch/Graph/Node/Layer/ViewModel/LayerNodeViewModel.swift
- Stitch/Graph/Node/Patch/ViewModel/PatchNodeViewModel.swift
- Stitch/Graph/Node/Port/ViewModel/FieldGroup.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserver.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowObserver/NodeRowObserverExtensions.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/NodeRowViewModel.swift
- Stitch/Graph/Node/ViewModel/CanvasItemViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModel/NodeViewModel.swift
- Stitch/Graph/Node/ViewModel/NodeViewModelType.swift
- Stitch/Graph/Sidebar/ViewModel/ProjectSidebarObservable.swift
- Stitch/Graph/ViewModel/GraphState.swift
- Stitch/Graph/ViewModel/VisibleNodesViewModel.swift
QA'd on Humane demo. Also QA'd adding and removing inputs. Looks like we can rely on `updateGraphData` there.
> Clarify more of `GraphState`'s `initializeDelegate` method

- Stitch/App/Util/TypeExtension/CollectionExtensionUtils.swift
- Stitch/Graph/Node/Model/GraphCopyable.swift
- Stitch/Graph/Node/Model/StitchClipboardContent.swift
- Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarSelectedItemsDuplicated.swift
- Stitch/Graph/Util/NodeSelection/CopyAndPasteNodesActions.swift
- Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7140
QA video: copy-pasting, into a separate project, both patch and layer packed/unpacked inputs/input-fields where upstream output node is / is not pasted as well.
https://github.com/user-attachments/assets/5b842ddf-edd8-4d42-965c-762f6b96957c
> Preserve input's value when pasting into project where connected upstream is absent

- Stitch/Graph/Sidebar/ViewModel/SidebarItemGestureViewModel.swift
- Stitch/Graph/ViewModel/GraphState.swift
Goal: consolidate more of our "update our UI cache" logic in a single place. `updateGraphData` seems the place.
QA video 
https://github.com/user-attachments/assets/ac03d3d2-5155-4873-98bf-3382a8d4f69a
> Update `layerDropdownChoiceCache` in `GraphState.updateGraphData` where we update other caches

- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemSwipeView.swift
We missed weak referencing the sidebar that gets used in the hover block. Fixing an issue where sound players continue playing when exiting some project after hovering in sidebar.
> Fixed retain cycle from sidebar hover state

- Stitch/Graph/Toolbar/View/CatalystNavigationBarHelperViews.swift
- Stitch/Home/View/ProjectsHomeViewWrapper.swift
Also reverts changes that were exploring possible fixes for Mac toolbar icons disappearing.
> Fixed Mac top bar color tint regression; revert icon hover removal

- Stitch/Graph/StitchAI/DatasetRecording/LLMRecordingState.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/Step.swift
- Stitch/Graph/StitchAI/GraphPrompting/DataModel/StepTypeAction.swift
- Stitch/Graph/StitchAI/GraphPrompting/UI/EditBeforeSubmitModalView.swift
- Stitch/Graph/StitchAI/StitchAISystemPrompt.swift
The main change in here is new logic that given each new node ID from Stitch AI, creates a new ID ensuring uniqueness. Steps have a new protocol function that will mutate properties given some node ID mapping.
> Fixed Stitch AI issue where new nodes could overwrite existing ones

- Stitch/Graph/Edge/Util/EdgeUtils.swift
- Stitch/Graph/Edge/Util/PortDragActions.swift
- Stitch/Graph/Edge/View/EdgeDrawingView.swift
- Stitch/Graph/Edge/ViewModel/EdgeDrawingObserver.swift
- Stitch/Graph/LayerInspector/EdgeDraggedToInspector.swift
- Stitch/Graph/Node/Port/View/PortView.swift
- Stitch/Graph/Node/Port/ViewModel/NodeRowViewModel/PortUIViewModel/OutputPortUIViewModel.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/TextField/PreviewTextFieldLayerUtils.swift
- Stitch/Graph/View/GraphBaseView.swift
The perf issue here is largely on main but merging for Chris's branch to ease rebase conflicts.
The main fix is extra render cycles on port views caused by drag gesture state changes. Drag gestures used immutable data and are frequently updated on drag. The fix here is using a view model approach.
Before:
https://github.com/user-attachments/assets/5e008eb0-90bc-4b0e-8fc2-ccdd1ccf0d68
After:
https://github.com/user-attachments/assets/41b72dc1-027e-41ff-a27d-46452288827a
> Improved edge drag performance

- Stitch/Graph/LayerInspector/LayerPortAddedToCanvas.swift
Fixes and issue where the new edge dragging support for layer inspector inputs would invalidate new connections should existing canvas inputs exist on the graph. Same fix for both pack and unpacked fields.
> Fixed new edge creation with pre-existing layer inputs

- Stitch/Graph/Edge/Util/EdgeUtils.swift
- Stitch/Graph/Edge/View/ActivelyDrawnEdge.swift
- Stitch/Graph/LayerInspector/EdgeDraggedToInspector.swift
- Stitch/Graph/LayerInspector/LayerInspector3DTransformInputView.swift
- Stitch/Graph/LayerInspector/LayerInspectorGridInputView.swift
- Stitch/Graph/LayerInspector/LayerInspectorPortView.swift
- Stitch/Graph/Node/Port/View/LayerInspectorRowButton.swift
- Stitch/Graph/Node/Port/View/PortView.swift
- Stitch/Graph/Node/Port/ViewModel/Layer/LayerInputObserver.swift
Hat tap @ellbosch for greatly improving the input detection area: now includes the spacing between rows etc. 
This branch also resolves an existing bug on `development` where we could attempt to add an individual field for a non-multifield input.
> Edge dragged to inspector: smarter determination of when we're hovering over 

- Stitch/Graph/Node/Port/Model/Field/FocusedUserEditField.swift
- Stitch/Graph/PrototypePreview/Layer/View/GeneratePreview.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/TextField/PreviewTextFieldLayer.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/TextField/PreviewTextFieldLayerUtils.swift
Fixes an issue where keypresses intended for the prototype would be picked up by graph shortcuts used for graph editing (like node shortcuts).
Adds two new focus states:
1. General prototype window focus
2. Prototype field layers
Tracking the latter enables us to de-focus text fields in the prototype, which would previously remain in focus with other selections in the app.
> New prototype focus state for disabling graph shortcuts

- Stitch/App/Shortcut/InsertNodeCommands.swift
- Stitch/App/Shortcut/ProjectsHomeCommands.swift
- Stitch/Graph/Gesture/Util/GraphUICursorSelectionActions.swift
- Stitch/Graph/LayerInspector/FlyoutUtils.swift
- Stitch/Graph/Node/Patch/Type/Interaction/Keyboard/KeyPressActions.swift
- Stitch/Graph/Node/Port/Model/Field/FocusedUserEditField.swift
- Stitch/Graph/Node/Port/View/NodeInputOutputView.swift
- Stitch/Graph/Node/Port/View/PortView.swift
- Stitch/Graph/Node/Util/Movement/NodeMovedAction.swift
- Stitch/Graph/Node/Util/NodeCreatedAction.swift
- Stitch/Graph/Node/Util/NodeDeletedAction.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/TextField/PreviewTextFieldLayerUtils.swift
- Stitch/Graph/Sidebar/Util/Gesture/LegacySidebarActions.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarItemSelectionActions.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemSwipeView.swift
- Stitch/Graph/Sidebar/ViewModel/LayersSidebarViewModel.swift
- Stitch/Graph/Sidebar/ViewModel/ProjectSidebarObservable.swift
- Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
- Stitch/Graph/Util/NodeSelection/NodeSelectionUtil.swift
- Stitch/Graph/ViewModel/GraphUI.swift
- Stitch/Graph/ViewModel/StitchDocumentViewModel.swift
Cleans up logic by moving state handling to `reduxFocusedField`.
There were a few issues I saw where selection state wasn't resetting properly. This PR should both improve functionality and clean up code.
> Focus state fixes for port and sidebar selection

- Stitch/Graph/Node/Patch/Type/Interaction/Keyboard/KeyPressActions.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/TextField/PreviewTextFieldLayerUtils.swift
Recent changes broke old keypress detection which automatically failed if any focus state exists. The new logic requires the prototype to be in focus.
This is an improvement from past logic which didn't require prototype preview logic. Now our behavior equals Origami's.
> Improved keypress detection logic + regression fix

- Stitch/App/Customization/AppThemeActions.swift
- Stitch/App/Shortcut/InsertNodeCommands.swift
- Stitch/App/Shortcut/PatchNodeShortcutKeys.swift
- Stitch/App/Shortcut/ProjectsHomeCommands.swift
- Stitch/App/StitchApp.swift
- Stitch/App/View/AppSettingsView.swift
- Stitch/App/View/StitchRootView.swift
- Stitch/App/View/ViewUtil/StitchHostingController.swift
- Stitch/App/ViewModel/StitchStore.swift
- Stitch/Graph/Edge/Model/EdgeStyle.swift
- Stitch/Graph/Node/Patch/Type/Interaction/Keyboard/KeyPressActions.swift
- Stitch/Graph/Node/Patch/Type/Interaction/Keyboard/KeyboardNode.swift
- Stitch/Graph/Node/Util/NodeCreatedAction.swift
- Stitch/Graph/View/Util/EnvironmentValues.swift
- Stitch/Home/View/ProjectsHomeView.swift
https://github.com/user-attachments/assets/95ae0ccc-5a36-45b2-9410-f19b7555c954
> "Require Option for Shortcuts?" setting

- Stitch/App/Shortcut/InsertNodeCommands.swift
Regression from cleaning up the patch shortcuts.
> Do not disable patch shortcut when input selected

- Stitch/Graph/Node/Util/NodeCreatedAction.swift
> Persist when 'node inserted upstream via shortcut'

- Stitch/App/Shortcut/InsertNodeCommands.swift
- Stitch/App/Shortcut/PatchNodeShortcutKeys.swift
Resolves some funkiness around layer group creation from the Option + G command.
> Rely on existing Cmd+G shortcut

- Stitch/App/Shortcut/PatchNodeShortcutKeys.swift
In the future an enum of all our shortcuts would be a good idea, so we don't miss any.
> Fix 'option not required' shortcuts for pack, unpack and splitter

- Stitch/App/Shortcut/PatchNodeShortcutKeys.swift
- Stitch/Graph/Node/Patch/Type/Interaction/Keyboard/KeyPressActions.swift
Pack and Unpack shortcuts always require Command and never use Option.
> `CMD+P` shortcut for Pack, `CMD+U` shortcut for Unpack

- Guides/Layer.md
- Stitch.xcodeproj/project.pbxproj
- Stitch.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Stitch/Graph/Menu/InsertNodeMenu/Model/InsertNodeMenuOption.swift
- Stitch/Graph/Menu/InsertNodeMenu/Model/InsertNodeMenuState.swift
- Stitch/Graph/Menu/InsertNodeMenu/Util/InsertNodeMenuActions.swift
- Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuNodeDescriptionView.swift
- Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuSearchResults.swift
- Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuSizeReadingData.swift
- Stitch/Graph/Node/Model/GraphCopyable.swift
- Stitch/Graph/Node/View/NodeTag/CanvasItemMenuButtonsView.swift
- Stitch/Graph/Node/View/NodeView.swift
- Stitch/Graph/PrototypePreview/Layer/Util/LayerNodesSorting.swift
- Stitch/Graph/Sidebar/Model/GroupCandidate.swift
- Stitch/Graph/Sidebar/Util/LayerGrouping/SidebarLayerData.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupCreated.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarGroupUncreated.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarListItemSelectionHelpers.swift
- Stitch/Graph/Sidebar/Util/ListModification/SidebarSelectedItemsDeleted.swift
- Stitch/Graph/Sidebar/View/SidebarFooterView.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemGestureRecognizerView.swift
- Stitch/Graph/Sidebar/View/SidebarItem/SwipeView/SidebarListItemSwipeView.swift
- Stitch/Graph/Sidebar/ViewModel/ProjectSidebarObservable.swift
- Stitch/Graph/Sidebar/ViewModel/SidebarItemGestureViewModel.swift
- Stitch/Graph/Sidebar/ViewModel/SidebarItemSwipable.swift
- Stitch/Graph/Util/GraphUIActions.swift
- Stitch/Graph/Util/KeyBindingActions.swift
- Stitch/Graph/Util/NodeSelection/NodeDuplicationActions.swift
- Stitch/Graph/ViewModel/GraphState.swift
This PR adds new popovers for nodes and layers.
Some other housekeeping:
* StitchViewKit has been removed as a dependency
* `InsertNodeMenuOptionData` struct has been removed in favor of just using the underlying enum
> "About" popover for patches and layers

- Stitch/Graph/Node/Util/NodeCreatedAction.swift
Regression caused from recent changes which enforce layers be added to visible nodes before the sidebar.
> Fixed regression with new layer groups

- Stitch/App/FeatureFlags.swift
Why didn't our Xcode Cloud `Stitch AI Reasoning` work here? The `Stitch AI Reasoning` build scheme had worked locally...
> Enable training-example button

- Stitch/Graph/Node/Layer/Type/MaterialLayerNode.swift
Resolves https://github.com/StitchDesign/Stitch--Old/issues/7285
> Do not show nonsense inputs on Material layer

- Stitch/Graph/Node/Model/RowData/LayerInputType.swift
- Stitch/Graph/PrototypePreview/Layer/View/Type/TextField/PreviewTextFieldLayer.swift
> Default enable spellcheck; Use placeholder color that shows up against common white prototype background

- Stitch/Graph/LayerInspector/Model/LayerInspectorSection.swift
- Stitch/Graph/Node/Layer/Type/Text/TextFieldLayerNode.swift
> Separate inspector section for TextField-specific inputs

- Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenu.swift
- Stitch/Graph/Menu/InsertNodeMenu/View/InsertNodeMenuSearchBar.swift
- StitchTests/openAIRequestTests.swift
- TestFlight/WhatToTest.en-US.txt
The issue was caused from changes which simplified state controller the insert node menu's appearance.
> Fixed regression where logs alert doesn't appear
